### ISSUE TITLE
passive energy generation halts when too many upgrades are acquired and cancelled

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#100]
I was attempting to use testing mode to get the most energy efficient, powerful laser possible with the existing upgrade arsenal. After I was finished getting my upgrades (I cancelled most because they did not contain laser tech), I tried to crouch and use Inductive Charging to generate energy, but it was not working. Keep in mind my laser energy efficiency was below the normal value, and I was not using my laser at the time. I checked the pause menu, recorded my energy level before crouching, and after crouching, and it did not change. This is not a common occurrence, but I thought I would mention it. I also did not have any other upgrades other than laser tech (and inductive charging), and my field was Negative Mass.

**Comment by Masbirb** [comment]
Could you please send over the build link.

**Comment by Masbirb** [comment]
Also this issue 100 hooray

**Comment by 3xionDev** [comment]
the build is the current one hosted on the website

**Comment by landgreen** [comment]
not sure how to fix this
