### ISSUE TITLE
broken clock map.

### ISSUE THREAD

**Issue by Loiccoder** [landgreen/n-gon#108]
This is my first issue report but i have encountered it a few amount of times (more than one) and it completely throws a game
i was playing on experiment mode having fun, and then it loaded clock map.
but inmediately as i spawned in, it was all buggy and has no collision. I will provide as much information as i can.
I do not remember the name of the map i was playing before, but at first sight it was like the previous map fused into clock.
<img width="1440" alt="Screenshot 2023-10-31 at 3 42 59 PM" src="https://github.com/landgreen/n-gon/assets/107321961/645b8d22-d839-4b9a-a223-e120f12264a6">
<img width="1440" alt="Screenshot 2023-10-31 at 3 43 13 PM" src="https://github.com/landgreen/n-gon/assets/107321961/93b4dd8e-51d0-425c-9274-3169d2a2de77">
hope the images work.

the dark gray objects dont have collision, and i spawn with and endless loop of falling to the void, which forced me to get into testing.
ignore the blocks i am standing on and the weird blocks on the "trap" room. i added them myself in testing.
I will provide more info
<img width="1432" alt="Screenshot 2023-10-31 at 3 44 34 PM" src="https://github.com/landgreen/n-gon/assets/107321961/7da18b14-a536-4c60-a72c-3444e47428ad">
thanks for teaching me how to look at console btw.
more info:
banned maps: dojo, yingYang, stereoMadness, tlinat, staircase, ruins, ace, cantilever, superNgonBros. ( if landgreen is interested on why i banned them, i would love to discuss it.)
seed: 74886
[build url](https://landgreen.github.io/sidescroller/index.html?&seed=74886&gun0=nail%20gun&gun1=shotgun&gun2=mine&gun3=missiles&gun4=foam&gun5=harpoon&gun6=super%20balls&gun7=drones&gun8=spores&gun9=wave&gun10=grenades&gun11=laser&tech0=arsenal&tech1=active%20cooling&tech2=pigeonhole%20principle&tech3=desublimated%20ammunition&tech4=Newtons%201st%20law&tech5=collider&tech6=reaction%20inhibitor&tech7=refrigerant&tech8=accretion&tech9=anthropic%20principle&tech10=strong%20anthropic%20principle&tech11=Bayesian%20statistics&tech12=cross-disciplinary&tech13=paradigm%20shift&tech14=options%20exchange&tech15=needle%20ice&tech16=ceramics&tech17=needle%20gun&tech18=stress%20concentration&tech19=crystallizer&tech20=thermoelectric%20effect&tech21=polyurethane%20foam&tech22=laser-mines&tech23=electrostatic%20induction&tech24=cavitation&tech25=ideal%20gas%20law&tech26=relativistic%20momentum&tech27=diffuse%20beam&tech28=free-electron%20laser&tech29=bremsstrahlung&tech30=cherenkov%20radiation&tech31=Meissner%20effect&tech32=tessellation&molMode=1&field=perfect%20diamagnetism&difficulty=2) (pretty fun)
i am playing on safari (i recognize its buggy)
I dont know what im doing.

**Comment by Loiccoder** [comment]
forgot to say that as i started taking screenshots the dark gray elements of the previous map dissappeard, i dont know how. but they are not here anymore, the only thing remaining is the slime. im pretty sure at the start clock was missing dark gray sections, but then it swapped.

**Comment by kgurchiek** [comment]
Thanks for reporting it, I'll work on fixing it

**Comment by landgreen** [comment]
I see the fix in the pull requests.  I don't understand the issue, but I can put that fix in the next patch.

**Comment by kgurchiek** [comment]
The issue is that array.splice actually affects the original array instead of just returning a new one, so the map would mess up the boss spawning list

**Comment by landgreen** [comment]
oh cool, so maybe that solves the other pending issue: "Issue with boss spawning"

**Comment by kgurchiek** [comment]
Yeah I'm pretty sure that's what the issue was, since they had community maps enabled
