### ISSUE TITLE
Pulling the lever on biohazard with enthalpy spawns a lot of health power ups

### ISSUE THREAD

**Issue by Loiccoder** [landgreen/n-gon#110]
Yea its self explanatory...
it does happen consistently, this is my second issue report.
<img width="1440" alt="Screenshot 2023-11-01 at 3 53 26 PM" src="https://github.com/landgreen/n-gon/assets/107321961/59464928-327c-4db1-95a3-b3ae77cdcfc1">
_do not show this to quenching users_

once again thanks for the wonderful game!

**Comment by Loiccoder** [comment]
update:
<img width="1440" alt="Screenshot 2023-11-01 at 4 08 35 PM" src="https://github.com/landgreen/n-gon/assets/107321961/483d3acd-0ad2-4347-a345-92742ee3649a">
**I ate it all >:)**

**Comment by landgreen** [comment]
I don't fix small bugs on community maps, but if someone else makes a fix I'll add it.

**Comment by Loiccoder** [comment]
accidentally closed it

**Comment by Ant-Throw-Pology** [comment]
Fix found...?

Change 
![image](https://github.com/landgreen/n-gon/assets/115495738/2981b3d0-e2c1-4117-8bc2-5395aaa75d34)

to
![image](https://github.com/landgreen/n-gon/assets/115495738/b5867ee8-69d1-48ef-b1e8-70dd5cccdd78)

**Comment by Ant-Throw-Pology** [comment]
Reason being all the mobs and all the cages are damaged when the boss spawns (lines 13700 and 13702), and the boss's cage is damaged with 5 hit points (line 13705)

**Comment by landgreen** [comment]
ok sounds good
