### ISSUE TITLE
the 7 second stuck at map check can softlock on some maps.

### ISSUE THREAD

**Issue by Loiccoder** [landgreen/n-gon#111]
Im addicted to this game I don't care ive reported an issue just an hour before this i just want the game to improve.
Since checking m being stuck in a map  every 7 seconds it was bound to have some issues, either techincal wise or gameplay wise, the changelog even is insecure

<img width="455" alt="Screenshot 2023-11-01 at 4 51 18 PM" src="https://github.com/landgreen/n-gon/assets/107321961/bbb6a1f4-7fbc-4ec4-9f47-ac731da1d92b">

> A rare case of an insecure changelog

I was playing in the community map RUN, and i managed to enter the final parkour sections, where the blocks flash collition on and off.
before they added this update, whenever you are inside the block that just appeared, m usually clipped out of the block in less than a second. This happened to me now, and my luck made it so the second that i was inside the block was the 7 second interval, sending me back to spawn, softlocking me from further progression.
<img width="1440" alt="Screenshot 2023-11-01 at 4 47 02 PM" src="https://github.com/landgreen/n-gon/assets/107321961/93d7552d-2528-469e-92ca-92bae08bc849">
> Help me Step-m im stuck

i guess this can happen with other maps such as temple

**Comment by kgurchiek** [comment]
In my opinion, that check should be optionally enabled in the map code like freefalling so that it doesn't break community maps

**Comment by landgreen** [comment]
I'll see if I can add a way for the check to see if you are stuck for over 4 seconds.
