### ISSUE TITLE
Interest in game design

### ISSUE THREAD

**Issue by MemeCake789** [landgreen/n-gon#112]
Hi there! I am a big fan of this game and wanted to create a game similar to it. I have done some learning into matter.js and I was just wondering how you made the game and how each file is used. Thanks!

**Comment by landgreen** [comment]
Well, n-gon isn't written in a way you would want to copy.  I was just messing around when I came up with the general file structure.  I'm surprised it works at all.

A good starting point for web based games is this template project I wrote for the CS class I teach:
https://codepen.io/lilgreenland/pen/zoZNVX
It has the JS HTML CSS code for making graphics and animating them.  In the JS section there are key and  mouse inputs.  It also has an animation loop at the bottom.
