### ISSUE TITLE
some balancing/gameplay suggestions for n-gon.

### ISSUE THREAD

**Issue by Loiccoder** [landgreen/n-gon#113]
i wasn't sure at all if it was possible to suggest stuf here but i saw a few quality of life suggestions and i guess they are possible.

this is a bunch of text but the titles and first sentence are enough ti understand so landgreen please just read this whenever

1. Reduce foam Damage
I am not implying that foam is overpowered or unbalanced, it's stats are fine, but if you were to decrease the base damage it would make foam tech more powerful.
foam is a high fire rate, short range, slowing weapon, i mostly use it as a secondary weapon, when i have a single target primary weapon i usually pull out the foam when im overwhelmed, i use it for its slowing, area of effect, and firerate, not for its damage.
when i have foam as a primary weapon it is quite fun by itself, it feels a weapon really dependant on ammo management, I like the high fire rate to basically just shoot a wall of foam and overwhelm the enemies. however foam kills them quickly and a lot of foam is wasted, and i feel punished by firing a lot, since i should have optimally just clicked once and waited for the enemies to die. foam usually kiils non boss mobs quite quickly. but if the damage of foam was heavily reduced, it would:
A) encourage you to waste more ammo, making ideal gas law and other techs more powerful
B) make you need more damage, so surface tension, aerogel or others are more desirable.
otherwise shotgun with foamshot is just a straight upgrade over foam gun, since one shot of foam is all you need.

2. Radioactive defense
every time i chose irriadated drones early in the game is a guaranteed loss, since im taking damage from shooting drones, all of the radiative upgrades aren't useful until you get water shielding, i just played a run were on the first level a boss dropped two tech, so i got irriadated drones, and prayed to god that the second tech was water shielding, and it was and it was a fun run where i managed to defeat the boss twice (i died inmeditely after that) my suggestion is that by default m already has a bunch of radioactive defense by default.

3. Make laser ignore fire rate
one of my favorite combos is [Pigeonhole, generalist, and active cooling](https://landgreen.github.io/sidescroller/index.html?&seed=24867&gun0=nail%20gun&gun1=shotgun&tech0=active%20cooling&tech1=pigeonhole%20principle&molMode=3&field=field%20emitter&difficulty=1) which is quite fun because of the high fire rate but when the chose gun is laser i know its going to be difficult, since high fire rate laser means that it drains energy quicker, to a point where it becomes a point and click game withc a click cooldown, sure it increases dps but its just not worh it. funnily enough before this i thought laser already ignored fire rate, i didn't have any evidence, i thought of that intuitively.
![shortateentionspam](https://github.com/landgreen/n-gon/assets/107321961/eb5c287d-216d-4091-9893-0ee3d4a0dbaf)

> here have a subway surfer's image to help your attention spam. thanks for reading all of that if you did.

4.fixing the super determinisim all guns soft lock.
So when you [have all guns and superdeterminsm](https://landgreen.github.io/sidescroller/index.html?&seed=78049&gun0=nail%20gun&gun1=shotgun&gun2=super%20balls&gun3=wave&gun4=foam&gun5=drones&gun6=spores&gun7=grenades&gun8=missiles&gun9=harpoon&gun10=mine&gun11=laser&tech0=heuristics&molMode=0&field=field%20emitter&difficulty=1) you softlock as soon as you pick up a gun power up. but this might change other gamplay aspects.
originally if you have all guns and pick up a gun power ups it gives you ammo, but now it allows you to research and cancel to make cancel upgrades more powerful. I have various ideas to fix this, here are some.
A) it is replaced with junk tech.
B) it transforms int a tech pwoer up/field
C) has an option to gain ammo.
if case A or B are the ones chosen then in the botoom left corner it should say "since you have all guns equipped your gun power up has been converted into regular/junk tech.
if its C then the option is called (gain x ammo) with a description saying that "you already have all guns so this is your only option"

here are some "quicker" ones
5.learning names
(yes there is more)
Im just a level 2 geek so far, so i dont have enough skills to understand all of the code of n-gon, the only things i understand are the comments and some if's. And in the mobs page it says the name of all mobs, but i don't know which is which, so it would be cool to have a way for player sto find it out. a few options could be
A) junk tech: e.g spawn 10 (mob name goes here) or replace all mobs with (name goes here)
a curious player (like me)would click that and go "oh so thats how its called"
or also someone can make a community map based on waves of mobs, and on the message system it says the mobs the waves are made of.

some tech ideas:
more techs that involve removing them like null hypothesis, my idea is of a tech that if you have paradigmic shift it gives you 5 tech in your pause menu that if removed heal you to full or gives you damage for a limited time, like a get out of jail free card.

also add more tech that improve tungsten carbide, give that guy some love.

thanks for the wonderful grame that is criminally free!

**Comment by landgreen** [comment]
thanks:

foam damage reduced 10%, ammo increased about 10%
fixed - super determinism all guns soft lock by just exiting out of gun menu
JUNK tech: spawn by mob type 
    added to my todo list
