### ISSUE TITLE
 Help with game mechanics issue in my game similar to yours

### ISSUE THREAD

**Issue by MemeCake789** [landgreen/n-gon#115]
## Hello there,

I am currently developing a game similar to yours and I am facing an issue with the game mechanics. I have created a manager that detects if the player is touching a wall and allows the player to jump while midair. However, there are several issues with this approach. For instance, the player can jump on the side of the wall and get launched into the air, or somehow stand below a wall.

To fix this, I generated a hitbox on top of all the walls, and only allow the player to jump if they are on the hitbox. While this is better, there are still some issues with it. For example, if the player is falling from a high area and lands on the hitbox, they can jump. Or if the player is on the corner of two walls, they also can't jump.

I was wondering if you could provide some insight into how you tackled this problem in your game. Thank you.

Here's the link to the game I'm working on: [https://github.com/MemeCake789/Delta](https://github.com/MemeCake789/Delta)

**Comment by landgreen** [comment]
press T to enter testing mode in n-gon and you can see the outline of the player hit boxes I used
essentially I made a small foot hitbox on the player that doesn't trigger from sides.
If you haven't unlocked Testing mode enter this command into the console to force an unlock: 
lore.unlockTesting()

My hotbox isn't perfect at high speeds you can jump off walls and other shenanigans, so I try to limit the max speed in other ways.
