### ISSUE TITLE
Issue with Missile launch system junk tech

### ISSUE THREAD

**Issue by corneeme** [landgreen/n-gon#116]
the junk tech missile launch system, when paused keeps counting down its timer, so when unpaused it will shoot massive amounts of missiles, I'm not complaining about the bug, it is just something I noticed, documentation below

![image](https://github.com/landgreen/n-gon/assets/93950611/0290b74f-27d4-49e5-97c2-be9764ec1ae9)

**Comment by landgreen** [comment]
The general rule is that JUNK tech should have some minor bugs.  They are JUNK so it is intentional and in keeping with the story.
