### ISSUE TITLE
Grappling Hook coupling effect is undefined

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#117]
![image](https://github.com/landgreen/n-gon/assets/90143063/72e5a23d-1d6c-499d-8d3d-f79d5c79facf)

**Comment by landgreen** [comment]
see patch notes

"grappling hook is now a field  (work in progress)
  reworked physics to allow faster speeds, but more control
  improved rate of power up grabbing
  more player control to hook retraction rate
  changed hook shape and field image graphics
  grappling hook field **coupling**, more tech, bug fixes, and general polish to be added soon"

**Comment by Masbirb** [comment]
my idea for a coupling effect is maybe it could be +1 IX when blocks are destroyed per coupling so coupling has a use on it

**Comment by landgreen** [comment]
but any suggestions for the coupling effect?

**Comment by kgurchiek** [comment]
Oh, I didn't see the "coming soon" at the very end, sorry

**Comment by kgurchiek** [comment]
Maybe coupling effect could be shooting faster, and then just hitscan once it reaches a certain speed

**Comment by Masbirb** [comment]
I was thinking something that uses the fact that it destroys blocks

**Comment by Masbirb** [comment]
> +1 IX?

I mean it would create one of those ice crystal things when it destroys a block

**Comment by landgreen** [comment]
oh right I forgot  ice-9

**Comment by Masbirb** [comment]
> oh right I forgot ice-9

Thanks for telling me how to pronounce it

**Comment by landgreen** [comment]
it's from the book [cat cradle](https://en.wikipedia.org/wiki/Cat%27s_Cradle)

**Comment by kgurchiek** [comment]
I think something to do with destroying blocks would make sense since it's a unique mechanic to that field, maybe exploding them into nails? Similar to ice-9 on perfect diamagnetism, you could have increased amount of nails shot out

**Comment by Masbirb** [comment]
I'll give it a read

**Comment by landgreen** [comment]
cool,  it's a strange book but I liked it.
