### ISSUE TITLE
Temporary crash when taking entanglement

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#118]
It only froze for a bit as if it crashed, but then returned to normal.![image](https://github.com/landgreen/n-gon/assets/90143063/6a1f6e8c-0988-48e7-9e3d-b65741a8a61c)![image](https://github.com/landgreen/n-gon/assets/90143063/5fb876e5-b7f9-43be-b713-1d2f2e0d6ef5)

**Comment by kgurchiek** [comment]
This wasn't my bug, but the person that had it didn't have a GitHub account

**Comment by landgreen** [comment]
OK, thanks
I can't test this but the console error message is detailed so I just added a check for the error and it will just skip forward instead of crashing,  I hope.
