### ISSUE TITLE
saving null?

### ISSUE THREAD

**Issue by aerosoll** [landgreen/n-gon#120]
i want to reinstall n gon for the new update but i cant save null :( 
is there a way to save it (maybe like across comps as well)

**Comment by Ant-Throw-Pology** [comment]
Do you mean like cloning the repo as a zip file?

Because if so, the local storage data is the same across all file:// URLs, because they have the same origin

So if you download the new update, it'll keep the local storage data (which includes banned levels, lore status, entanglement stuff, etc)

**Comment by aerosoll** [comment]
ty!! also do u know how to advance in the lore status?? like idk how to get to the undefined room again

**Comment by kgurchiek** [comment]
You can get back to it multiple tomes the same way you got there the first time

**Comment by landgreen** [comment]
lore.unlockTesting();
localSettings.loreCount = 5 //this sets what conversation is heard (0-5)
tech.giveTech("tinker"); //show junk tech in experiment mode
