### ISSUE TITLE
Grappling Hook suggestion: block grappling

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#121]
Grappling Hook deleting blocks is incredibly annoying, I think it would make more sense (and be more fun) if it stuck to the block and pulled it back to you. Once it fully retracts, you'd automatically hold the block. Then you could make deleting blocks a separate tech with some sort of advantage, like blowing it up, giving energy, etc. It would also be pretty cool if it also automatically pulled mobs' corpse blocks to you when it killed one.

**Comment by landgreen** [comment]
That...

 actually is a great solution.  I only delete the blocks because I couldn't make the normal pick up system work.
