### ISSUE TITLE
Suggestion for a feature: Hawking Evaporation

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#122]
So you know how black holes slowly evaporate away and then explode? Well, this can be accelerated to occur sooner than expected. I chatted with some people about this in the Discord server and they agreed that I should post it here. Basically, my idea is than when M kills a blackHole enemy, a small animation plays of the blackHole evaporating away and at the end of the animation it generates a small explosion that does moderate damage to both M and surrounding enemies. It would be useful for large crowds that contain blackHole enemies.

edit: upon being reminded, the general consensus is that it should deal radiation damage to the player, instead of causing an explosion

**Comment by Masbirb** [comment]
Maybe it should not do explosion damage but radiation damage

**Comment by kgurchiek** [comment]
I think making it do radiation damage would be unique enough to be its own feature and would he more of a contribution to the game, rather than just being thermal runaway with an animation

**Comment by kgurchiek** [comment]
This could also "fix" black holes being boring in even the slightest high energy builds, even just inductive charging is enough to make black holes ignorable (unless you get completely swarmed by several of them). Adding even just some small damage when they die would make them still a bit interesting when you have decent energy generation

**Comment by 3xionDev** [comment]
Completely slipped my mind. We discussed this in the server didn’t we, guys? Yeah, rad damage is the better bet.

**Comment by landgreen** [comment]
ok I added this to my todo list
