### ISSUE TITLE
Suggestion for a Feature: Zipline

### ISSUE THREAD

**Issue by corneeme** [landgreen/n-gon#123]
I was thinking through some ideas for tech when one popped out to me, Ziplines. M would place a zipline point where he is at for a 10% energy drain, then shoot another point to the destination, like the mouse pointer, on the zipline you could add damage or defense or something like that for energy drain, and until you place another zipline the other one will stay there and still be usable but will disappear when you run out of energy.

**Comment by kgurchiek** [comment]
That would work great as a tech for Grappling Hook

**Comment by corneeme** [comment]
yeah, but I'm not sure what buff you should get on the zipline

**Comment by kgurchiek** [comment]
I think it would make sense to "zap" enemies when they cross it and deal some damage, maybe also slow them down while they're going over it

**Comment by corneeme** [comment]
yeah. that would make sense, kinda like cosmic tunneling from wormhole

**Comment by kgurchiek** [comment]
Yeah that's what I was thinking, and riding the zipline could also fulfill people's desire for a portal gun tech for wormhole

**Comment by corneeme** [comment]
maybe when a mob goes through the zipline it stuns them but when you pass through them it deals damage and drains energy faster

**Comment by corneeme** [comment]
yeah... huh neer thought about that before

**Comment by 136166** [comment]
Maybe that 'Gun' can be like those 'bluebull' mobs that charge at you? maybe you jump into a deployable Railgun? leave it there and use it again???

**Comment by corneeme** [comment]
yeah, thats kinda what I thought where it stays there until you deploy another or run out of energy

**Comment by kgurchiek** [comment]
Yeah I was imagining it would stay there and you could use it multiple times

**Comment by corneeme** [comment]
do you think it is worth suggesting?

**Comment by Whyisthisnotavalable** [comment]
I think this could be a thing map makers use, but not as a tech

**Comment by kgurchiek** [comment]
But it makes sense to go with grappling hook, and could still be a map feature as well

**Comment by corneeme** [comment]
maybe as a map feature, it wouldn't let you go through mobs and would know you off if you hit them but as a field tech it would zap mobs as you go through them

**Comment by landgreen** [comment]
It's a cool idea but the complexity of the key presses doesn't work with the simplicity of n-gon inputs.

**Comment by corneeme** [comment]
oh 😭
