### ISSUE TITLE
Suggestion for Weapon

### ISSUE THREAD

**Issue by 136166** [landgreen/n-gon#124]
Coilgun: fire a set of 'arrows', similar to the Flechette gun. Just an Idea. Tech idea: multistage

**Comment by 3xionDev** [comment]
I'm not sure that coilgun is the best name, but it's an idea. I feel like coilgun would be a tech for this gun, in which it makes you fire an extremely fast, bouncy, and heavy projectile. Either way, I'd like to see this added.

**Comment by 136166** [comment]
Or, it would be an 'Arrow' Gun with coilgun tech.

**Comment by Masbirb** [comment]
Could work as a nail gun tech because Flechette was likely merged with mini-gun to make the nail-gun

**Comment by Masbirb** [comment]
It would be a good guntech though

**Comment by 136166** [comment]
Another idea: APFSDS shot: when hitting a Mob, APFSDS shot splits into two small Rivets and a dart, similar to fletchettes.

**Comment by 136166** [comment]
Actually, that could be a new Grappling Hook tech: combine Coilgun, APFSDS and Grappling hook. Increased speed and 15% Recoil & launch power for Coilgun, APFSDS just for hitting more stuff, apply those to Grappling Hook. I was thinking of the firing animation to be like the 'Railgun' weapon for the N-gon Ancestor, [Mech](https://scratch.mit.edu/projects/14005697) when firing.

**Comment by landgreen** [comment]
this overlaps with Needle gun and rail gun

**Comment by 136166** [comment]
okay...
