### ISSUE TITLE
Radon-222

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#127]
Foam particles are now raced with radon that emits radiation -75% foam damage. requires foam, not Aerogel

**Comment by Masbirb** [comment]
The radiation would be similar to irradiated drones.

**Comment by 136166** [comment]
Another Foam Tech Idea: HE Shells: fire shells that travel to cursor location, then explodes in Foam. Also explodes if touching Mob.

**Comment by Masbirb** [comment]
"Type US3980139A canister" may be a better name because that is a US firefighting bomb

**Comment by landgreen** [comment]
Foam already is a damage over time effect so switching it to radiation wouldn't have chance in mechanics.
