### ISSUE TITLE
Excess energy isn't visible with Metamaterial Cloaking

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#128]
When using Metamaterial Clocking, the energy bar is invisible if you have energy above your max.

**Comment by 3xionDev** [comment]
you are indeed correct, the energy bar disappears. I seem to have found another bug while testing this; dynamo-bots do not work with cloaking

**Comment by landgreen** [comment]
Hiding the energy bar is an intentional stylistic choice, and also it looks ugly with the clocking field graphics.
