### ISSUE TITLE
Cloaking boss strobe bug

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#129]
The bug happens when the cloak boos spawns after a level has been loaded for some time but the boss has not yet spawned where when the cloak boss spawns its cloak turns into strobe light where it repeatedly appears and disappears.

**Comment by kgurchiek** [comment]
I've also had a strobe effect with the time boss. When you weren't within its effect, the white circle would flash. I only had this once and haven't tried to reproduce yet, but it might be worth noting that the one time this happened was the one time I played on a high frame rate monitor, but I did have the fps cap set to 60

**Comment by landgreen** [comment]
it's a known quirk, if you are capping fps the timeSkip boss flashes.  It's considered just how a mob that slows time would look if you were also slowing time.

**Comment by kgurchiek** [comment]
So it's intentional or just a bug that works out?

**Comment by landgreen** [comment]
It's not a bug, but it was unplanned.
