### ISSUE TITLE
Suggestion: a way to not shoot grappling hook

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#130]
It's kind of frustrating trying to pick up power ups that are right next to you while you have grappling hook, especially if you have a lot and you have to manually shoot each one on the ground and end up dragging yourself all over the place. There should be some way to pick up power ups without shooting the grappling hook, maybe make it not shoot if you're crouching (only if you're actually holding input.down, not if you're forced to crouch from a low ceiling or big drop)?

**Comment by Masbirb** [comment]
What if rupture gave increased suck so you wouldn't have to hurt yourself to get items

**Comment by 136166** [comment]
Or the pick-up effect could be on all the time?
