### ISSUE TITLE
Major visual glitches with Circular Symmetry

### ISSUE THREAD

**Issue by mRoNiOnN** [landgreen/n-gon#131]
Circular symmetry is the upgrade with a prerequisite of whichever junk tech removes your legs and makes you a floating spaceship head, and it makes it so that the camera rotation is locked to the player rather than the level. It's pretty hard to ignore that on the edge of the screen, every frame is placed on top of each other so that you can see the enemies and everything else being painted on the screen as you rotate and move around.
I think that this might be caused by a white background being drawn each frame being the size of the screen/viewport/whatever you call it, and when you rotate the level, the background gets rotated so that the edges of the screen might not be covered by it. It might be fixable by making the background a square twice as wide as the screen.
I could also see this as a feature, as it gives the game a sense of breaking as you keep getting junk tech. You start to get that feeling of "Oh gosh what the frick is this". What I'm trying to say is maybe that was intentional and it fits the devs vision.

**Comment by landgreen** [comment]
yep JUNK can't have bugs.
