### ISSUE TITLE
Final Boss Damage Scaling

### ISSUE THREAD

**Issue by sulplife** [landgreen/n-gon#133]
While I understand the final boss is meant to be strong, certain attacks seem to be a guaranteed hit against certain fields. One of the worst offenders for this is the lasers, where the boss rotates while shooting purple beams out of the corners. 

Most fields have ways of circumventing this move: Gravity and Grapple Hook can move along with the beams, Time Dilation and Wormhole can bypass them, Pilot Wave can use blocks to block it, and Perfect Diamagnetism can stun lock. But a lot of fields that are otherwise decently strong essentially sentence you to death for using them. 

Even with 50%+ defense, the laser will take around 20% health every time on Medium difficulty, this means that people who use Metamaterial Cloaking, Standing Wave, etc. are forced to get Unified Field Theory or build heavily into defense (which leaves them with nearly no opportunity to increase damage).

The attacks could be changed to depend on the field/guns a player has to make it feel fairer, it's not very fun to create a high energy build only for it to be negated by a massive black hole that constantly spawns enemies.

**Comment by landgreen** [comment]
Cloaking is immune to lasers.

**Comment by kgurchiek** [comment]
You don't need a field to counter it, when the laser comes I just walk on the ground to move along with it until they go away for a second, and then I go back to where I was before
