### ISSUE TITLE
Suggestion: grappling blocks

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#134]
I made a quick mod where the grappling hook is able to grapple onto blocks (it only grabs them when you retract the hook). It turns out to be very fun, it would be cool to have in-game. https://github.com/landgreen/n-gon/assets/90143063/417c49e7-cea0-4509-83af-fe659ef6b03e

**Comment by Whyisthisnotavalable** [comment]
Cool

**Comment by landgreen** [comment]
hmmm  that looks cool and fun.  I'd need to try it out to see if it elevates gameplay.  If you can use this to do skillful things it might worth it.

**Comment by kgurchiek** [comment]
I think the thing it helps with most is getting over ledges that have no roof. Normally it can be hard to do that if it isn't very tall so you can't get much momentum to propel yourself over, so this way you could toss a block up to grab on to midair and get over. (Also it's cool to feel like Thor and throw something that propels you into flight)

**Comment by corneeme** [comment]
yeah, I can thnk of some really useful applications for this
