### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by romdomin** [landgreen/n-gon#135]
I've been searching all over for a discord server and all the links are invalid. I vividly remember being in it once, however, I believe I left. I was wondering if I could get a new link to it?

**Comment by Loiccoder** [comment]
The official discord server has closed, however there is a community server unavailable. Contact Cornbread2100 in discord for the link.

**Comment by Whyisthisnotavalable** [comment]
> I've been searching all over for a discord server and all the links are invalid. I vividly remember being in it once, however, I believe I left. I was wondering if I could get a new link to it?

It's in the community level tlinat

**Comment by kgurchiek** [comment]
If anyone else stumbles upon this issue and wants it, here's the invite: https://discord.gg/3jR4KZmekS

**Comment by 3xionDev** [comment]
Shall we close this?

**Comment by NV4s** [comment]
No because it will help those looking for a server easily
