### ISSUE TITLE
add Xbox 360 controller support

### ISSUE THREAD

**Issue by boymcboysbrother** [landgreen/n-gon#137]

**Comment by landgreen** [comment]
I wrote the code for this already, but I found that n-gon with a game controller doesn't work well enough, so I removed the support.

**Comment by kgurchiek** [comment]
Hi bocboysbrother, I recently made a mod for this that I think works very well, and it should work on any past version or any updates to come: https://github.com/kgurchiek/n-gon-controller

I only have an Xbox One controller to test it with, so let me know if it all works. Also, if you haven't already, I'd recommend checking out the community-run discord server, there are other great mods there, and it's a great place to discuss the newest updates, your favorite tech, or anything else n-gon-related: https://discord.gg/ReTSxdWw4K

**Comment by boymcboysbrother** [comment]
hi kgurchiek, thank you for the mod! the xbox 360 firmware stays the same for all controllers exept origional xbox. only difference is xbox 360 and xbox one wireless capabilites use different firmware. anyways, thanks.
