### ISSUE TITLE
not an issue, just some 3d models of m

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#138]
![Screenshot 2023-12-21 7 29 28 PM](https://github.com/landgreen/n-gon/assets/88562716/9a18aa4b-b228-42a3-b429-14dd146f2e1d)
![Screenshot 2023-12-21 7 29 13 PM](https://github.com/landgreen/n-gon/assets/88562716/1c5c8894-99e0-4ffe-b47b-a30a3013badc)
i'm going to 3d print these, do you want one landgreen /j

**Comment by landgreen** [comment]
Yeah, I'd like one!  Is there a 3-D printer file you can add so I can print this?

**Comment by 3xionDev** [comment]
@landgreen yeah sure, lemme just get it ready to print so you don't have to deal with ugly supports and all that

**Comment by 3xionDev** [comment]
some assembly might be required (just some superglue to attach m's head to the body, and then the body to the base)

**Comment by landgreen** [comment]
cool, no hurry I will not have access to a 3-D printer for a few weeks, but I do have some super glue.

**Comment by 3xionDev** [comment]
@landgreen alright, getting the file ready now. several other people requested the file in the discord server also so i need to fine tune it so it works with most printers

**Comment by 3xionDev** [comment]
@landgreen here it is! 
[m.zip](https://github.com/landgreen/n-gon/files/13747461/m.zip)
slice it as you please.

**Comment by 3xionDev** [comment]
@landgreen WARNING: BE SURE TO PRINT IT WITH BRIM DISABLED, OTHERWISE YOU WILL **_NOT_** HAVE A GOOD TIME CLEANING THE PRINT UP

**Comment by landgreen** [comment]
I finally got my printed player model.  I don't have a 3-D printer, but a student of mine made it, and I glued and sanded it.

thanks!

**Comment by 3xionDev** [comment]
no problem. Everything turned out okay? I made some mistakes when preparing it to print.

**Comment by landgreen** [comment]
yeah, turned out fine.  I had to spend some time getting rid of the support stuff and glue a couple things, but it didn't take too long.

**Comment by 3xionDev** [comment]
Yeah, supports on the legs were a problem since i forgot to place them on their face. Happy to know it turned out okay though! What color did you print it in?

**Comment by landgreen** [comment]
The student who printed it choose white, which is good.  Although, dark grey legs would be cool.

**Comment by 3xionDev** [comment]
You could definitely print the legs separately in dark grey, along with the base in regular grey. The legs are really small and it would be super quick to print in dark grey. You could also paint the parts as you like, since the parts are white.

**Comment by 3xionDev** [comment]
@landgreen If it's not too much trouble, could I get a picture of the print as well as the model of the printer it was made off of? I want to see if the print quality carries between printers.

**Comment by landgreen** [comment]
Reality 3 ender neo?  I think
https://photos.app.goo.gl/m7iAfp9AroaKsnSq8

**Comment by 3xionDev** [comment]
Ah, Creality Ender 3 NEO. It looks like it was...printed in the wrong direction? The layer lines are facing up, whereas on mine they're sideways because I printed it on its side. I thought I formatted the file to print like that. Did you have to remove supports from under the little raised platform that `m` is standing on?

**Comment by AnnonymousNerd87** [comment]
This is why I love n-gon, everyone is so wholesome and sincere!

**Comment by AnnonymousNerd87** [comment]
You asked if Landgreen wanted one as a joke, then had a meaningful, wholesome, sincere conversation. Only small indie communities can do that without dissolving into chaos, and I love it! This game is the whole reason I made my GitHub account, I made it just to join in on these conversations

**Comment by 3xionDev** [comment]
@AnnonymousNerd87 Yeah, I guess that makes sense. The n-community is pretty nice.
