### ISSUE TITLE
Junk tech idea

### ISSUE THREAD

**Issue by 136166** [landgreen/n-gon#140]
Bullet Black Hole: Make all bullets gravitate towards you (and add some more for fun)
Just an idea! so all bullets, regardless of affiliation, hurts you and all of them come towards you as well. Spawn some more as well.

**Comment by kgurchiek** [comment]
That could be pretty cool if they also did a spiral orbit instead of just going straight to you

**Comment by 3xionDev** [comment]
![tys](https://github.com/landgreen/n-gon/assets/88562716/80ad6dbd-7504-4404-bf4b-cfd90bf3fc36)

**Comment by 136166** [comment]
???
