### ISSUE TITLE
Induction furnace formatting

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#142]

**Comment by kgurchiek** [comment]
What's the issue? It looks fine to me

**Comment by Masbirb** [comment]
![image](https://github.com/landgreen/n-gon/assets/146036333/a7370dda-1cc7-4fc1-b923-c2b8854c15ec)

**Comment by kgurchiek** [comment]
What browser are you using, and is your text size increased? It fits fine for me on Safari![image](https://github.com/landgreen/n-gon/assets/90143063/bf6deb3b-9906-441b-a114-90e13d5d4330)

**Comment by Masbirb** [comment]
Firefox

**Comment by kgurchiek** [comment]
Yep, just checked and it does that on Firefox for me too

**Comment by kgurchiek** [comment]
Maybe it could be shortened to "harpoon/grapple"?

**Comment by Masbirb** [comment]
Or kerning so it is slightly shorter

**Comment by landgreen** [comment]
Thanks for reporting this.  I tend to only test on chrome.  Last time I check Safari was just a mess, but generally firefox is better.

I switched to a  harpoon/grapple to make the text line shorter.
