### ISSUE TITLE
Hilbert space inconsistency

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#145]
Hilbert space which is now a skin is not disabled by having another skin

**Comment by NV4s** [comment]
Cool

**Comment by landgreen** [comment]
oh yeah I caught that too.  It's in next patch.

**Comment by NV4s** [comment]
Tbh I wish this could stay, it's pretty cool.

**Comment by NV4s** [comment]
Note the glitch only works if you choose a skin first (that isn't Hilbert Space) and then choose Hilbert Space. If you choose Hilbert first, it acts like a normal skin.
