### ISSUE TITLE
Negative research

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#146]
![Uploading 297211923...]

**Comment by landgreen** [comment]
I think I allow negative research if you eject a tech that gave you research.  If the game crashes of something I'd love to know, but negative research is ok until we find crashes.  I think...

**Comment by Masbirb** [comment]
It didn't crash so it was just weird and nothing else

**Comment by landgreen** [comment]
I think I fixed this it was some logic issues with bot fab code.
