### ISSUE TITLE
Tungsten hexafluoride Tech idea

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#147]
Foam slow down mobs twice as much and slowly pulls them towards the ground 
+30% foam damage
Half foam velocity
Foam is now effected by gravity 
Requires a source of foam and not aerogel

https://en.m.wikipedia.org/wiki/Tungsten_hexafluoride

**Comment by 3xionDev** [comment]
Foam is already affected by gravity

**Comment by Masbirb** [comment]
I would be fine with the damage bonus being cut

**Comment by Masbirb** [comment]
> Foam is already affected by gravity

I guess this would increase the effect of gravity on the foam

**Comment by landgreen** [comment]
this is a good idea I'll add to the list

**Comment by Masbirb** [comment]
The list grows every longer and every part of the list looks good
