### ISSUE TITLE
Tech/Skin Suggestion: Evolution/Adaptation

### ISSUE THREAD

**Issue by NV4s** [landgreen/n-gon#150]
Stats: 
For every level you beat, you get a random tech, skin, or bot.
+22% to Junk Tech

Comment down what I should improve on this since it is a bit bland.

**Comment by Masbirb** [comment]
Have you seen the tech many wourlds

**Comment by Masbirb** [comment]
This is just a better version of that tech

**Comment by NV4s** [comment]
Not really since you don't lose previous techs and you automatically get 1 random one.
