### ISSUE TITLE
Start a discussions

### ISSUE THREAD

**Issue by Ender-Ghost-Craft** [landgreen/n-gon#151]
its weird to ask questions in issues

**Comment by Ender-Ghost-Craft** [comment]
also on the last level, after completing with null, I reset right as I got T, is there anything I missed?

**Comment by NV4s** [comment]
There are 5 diff dialogues for doing null do you need to do null 5 times for this

**Comment by kgurchiek** [comment]
you unlock testing after the first one, but you do have to keep getting to `null` to get the other dialogues
