### ISSUE TITLE
Controls/How to play

### ISSUE THREAD

**Issue by Zyph4444** [landgreen/n-gon#154]
When you click controls on the start page ether the description or instructions are too big or should be shifted down so you can escape the control menu. Mainly I am saying that once I click on controls i cannot click on game settings because I can't escape the control settings

**Comment by landgreen** [comment]
I think your vertical pixel count must be below 600, or you are zoomed in.
seems more likely that you are zoomed in though.  ctrl-0  on PC to reset zoom I think.
