### ISSUE TITLE
Razzle Dazzle camouflage, field tech, skin tech

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#155]
Skin tech, 
This summons several fake mech units that enemies will likely target instead of you when you  uncloak  
When you take damage you shoot out several distractions drones then enemies will retarget 
Requires dazzler, meta material cloaking, no other skin

**Comment by Masbirb** [comment]
This has minimal community feed back so it would likely need changes

**Comment by landgreen** [comment]
I've looked into adding mobs distractions like this, but I gave up because it required a bit too much code to be rewritten.

**Comment by kgurchiek** [comment]
Would you use it if I made a pull request to add support for alternate targets?

**Comment by landgreen** [comment]
It's not about the time it would take to write the code.  Adding multiple mob targets would slow the game down, and making mob vision more complex has too many edge cases, so it wouldn't ever be perfect.  Players would get confused by inconsistent and unpredictable mob behaviors.
