### ISSUE TITLE
tech problem

### ISSUE THREAD

**Issue by Firereader05** [landgreen/n-gon#157]
I had grenades and got the 1500% ammo per pickup and now I can't get any more ammo.

**Comment by Masbirb** [comment]
You forgot to read the down side of that tech

**Comment by Masbirb** [comment]
You can only have that much ammo stored with that tech

**Comment by Firereader05** [comment]
I had 48 and couldn't get more than 48.

**Comment by Firereader05** [comment]
sorry I got the math wrong, I thought it was 150 ammo not 15 ammo.
