### ISSUE TITLE
recommend using the official site

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#160]
I recently met someone who played n-gon, but they only played it on an unblocked games site using a version that was at least four years old. He had no way of knowing that there was an official site to play on that gets updated. You should add some sort of message that lets players know there's an official site if they aren't playing on landgreen.github.io, maybe just a message on the top left of the start screen so that it isn't too annoying if you're just playing on a mod, but still enough to be noticed.

**Comment by landgreen** [comment]
I considered it, but I noticed that the about section links to the primary github.  Also I can't really add code to al the old versions of the game.

**Comment by kgurchiek** [comment]
I noticed that too, but the average player often doesn't even look through the settings, and if they do they aren't very likely to want to look at the source code anyway. Even if you can't add it to past versions, it'll only get more popular over time, and I imagine more sites will add the game in the future
