### ISSUE TITLE
Rebar production

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#167]
The railgun now shoots heavy high damage rebar that takes longer to charge
You can jump off fired rebar until it falls off after 30 seconds
Pins hit mobs to walls
Requires railgun, Harpoon

**Comment by Masbirb** [comment]
The pin feature according to corn bread could work like this

**Comment by kgurchiek** [comment]
[insert jeopardy music]

**Comment by Masbirb** [comment]
make the bar have an array of what it’s attached to and the mob has a reference to the bar then the mob can check if the bar is attached to anything else, and if it’s attached to a map element, just set its velocity to 0 and disable its movement otherwise the mob carries the bar around just like it does spores and the bar carries blocks if they are in the array and you could pick it up like a block with everything they still have attached and the piece of rebar lasts another 30 seconds

**Comment by Masbirb** [comment]
![image](https://github.com/landgreen/n-gon/assets/146036333/8034debf-147a-4ea9-a885-9a628b4b110d)

**Comment by landgreen** [comment]
The pinning to the map might be easiest to write for needle code, which already penetrate mobs.
I have wanted a rebar gun since half-life 2.

**Comment by uliltra** [comment]
half life mentioned

**Comment by 136166** [comment]
Sounds like a good idea to help new platformers!
