### ISSUE TITLE
Tinker effect is NOT kept between sessions

### ISSUE THREAD

**Issue by Erisfiregamer1** [landgreen/n-gon#17]
if you reload, the TInker effect is lost, despite it saying it persists through sessions. Please fix.

**Comment by landgreen** [comment]
Do your other settings persists through sessions?  You might have local storage disabled.

**Comment by landgreen** [comment]
I'm not sure, maybe you can try the chrome cookies setting:
Block third-party cookies
    not
Block all cookies (not recommended)

**Comment by Erisfiregamer1** [comment]
All cookies are enabled. What's going on here??
------- Original Message -------

**Comment by landgreen** [comment]
I'm not sure,  my other testers say tinker makes JUNK tech show up in the experiment menu for future visits
