### ISSUE TITLE
Minor Bug

### ISSUE THREAD

**Issue by TheFurrySlayer** [landgreen/n-gon#171]
I was just playing N-gon, and I got shotgun. I noticed that when I threw a block the shotgun cooldown on my cursor appeared, and it was as if I had used my weapon (which I hadn't). I'm guessing that this is caused by the shotgun cooldown code somehow  interacting with the block throwing code.

**Comment by landgreen** [comment]
yeah, we generally call something a bug if it breaks the game in some way.  This is just the game doing what it does.  You can't fire your gun right after throwing a block.
