### ISSUE TITLE
"Copy last build" button

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#173]
After death, there should be a button to copy the experiment link for the build you ended with in the last run. Most of the time that I want to share a build I want my final build before death, and it's annoying to keep copying the link every time I pick up a tech to make sure I get the full build when I die

**Comment by landgreen** [comment]
sharing builds is just so complex it never seems to copy correctly, so I stopped investing time in it.

**Comment by landgreen** [comment]
but the last build link is already in my todo list, I think.

**Comment by NV4s** [comment]
Me waiting for lore updates
