### ISSUE TITLE
idea: better cycling through fields on pause menu

### ISSUE THREAD

**Issue by HurricaneBeryl** [landgreen/n-gon#175]
when you get unified field theory, instead of having to click on the field itself to cycle, maybe there could be two buttons to cycle forwards or backwards, so if you accidentally skip the field you want to get to, you won't have to click like 15-20 times to get back there. (you dont have to follow the attached image exactly, its just a concept)

![negative2](https://github.com/landgreen/n-gon/assets/66543758/0f8b7696-275d-4729-8629-b86ba394ecaa)

**Comment by landgreen** [comment]
ok why not.

**Comment by landgreen** [comment]
<img width="391" alt="Screenshot 2024-02-29 at 7 58 43 PM" src="https://github.com/landgreen/n-gon/assets/21106570/7150bea6-0708-432a-af11-75eac32f2a9b">

**Comment by landgreen** [comment]
live now on current build

**Comment by HurricaneBeryl** [comment]
ooo i like that
