### ISSUE TITLE
(Bug?) Negative Research

### ISSUE THREAD

**Issue by jo9182** [landgreen/n-gon#176]
I was playing some N-gon on why? difficulty, y'know, daily dose of suffering and all that, and I paused and noticed I have negative research. I have gone through multiple alternate realities, which likely has something to do with it.
Build URL: [N-gon](https://landgreen.github.io/sidescroller/index.html?&seed=231648&gun0=spores&gun1=laser&gun2=mine&tech0=desublimated%20ammunition&tech1=zoospore%20vector&tech2=boom-bot&tech3=boom-bot%20upgrade&tech4=piezoelectricity&tech5=torpor&tech6=induction%20brake&tech7=quenching&tech8=%CE%A8(t)%20collapse&tech9=mass%20production&tech10=unified%20field%20theory&tech11=residual%20dipolar%20coupling&tech12=reinforcement%20learning&tech13=supercritical%20fission&tech14=MIRV&tech15=cordyceps&tech16=spherical%20harmonics&tech17=spherical%20harmonics&tech18=electronegativity&tech19=electronegativity&tech20=bremsstrahlung&tech21=pair%20production&molMode=3&field=standing%20wave&difficulty=5)

**Comment by jo9182** [comment]
Not the most professional way of writing an issue, but I'm running off of very little sleep currently.

**Comment by landgreen** [comment]
you get negative research if you gained research from a tech, you spend that research, then you lose the tech that gave you research.

**Comment by jo9182** [comment]
Alright, thank you.
