### ISSUE TITLE
Idea: Multiplayer Battles (and other suggestions)

### ISSUE THREAD

**Issue by The-Rock-21** [landgreen/n-gon#178]
I looked at the other suggestions and one of the suggestions for multiplayer would take too long. So I have a simpler suggestion. 
**Main Suggestion** - Multiplayer Battles
- 2+ Players
- Private rooms where it generates a random join code and you can play with friends
- You battle your friends
- The host can decide how many guns, techs, and ammo everyone would get
**Additional Suggestions** (This is other stuff I thought of)
1. Multiplayer Speedruns - Private room with randomly generated join code. 2+ players. Play with friends and try to beat them by completing the game first (Null Room or just defeating the final boss) (Maybe you could add a function where hosts can sort levels)
2. Hide-and-Seek - Private room with randomly generated join code. 2+ players. One (or two) players are seekers. They can't see through walls like in subway map, but hiders can. Only seekers have guns and can oneshot hiders. Both seekers and hiders will always have field emitter. You'll probably have to make entire new maps. 
3. Juggernaut - Private room with randomly generated join code. 3+ players. It's like Multiplayer battles and Hide-and-seek rolled into one with several twists. One player is overpowered and a random assortment of guns with infinite ammo (Maybe too overpowered?). The host can decide how many guns and tech they get. Other players either have to defeat the boss or survive long enough. (Host decides how long a match lasts) Players start with field emitter but can get other fields (You'll probably have to nerf the fields in this mode). Players also have to find guns and tech to defeat the juggernaut.
**These are just additional suggestions. My main hope is that you can add multiplayer battles. Maybe you can add public rooms later on. You should also add spectator mode so that you can watch as your friends beat you or you can laugh as you watch your friends struggle with the game >:)**

**Comment by corneeme** [comment]
that could be a lot of fun!

**Comment by kgurchiek** [comment]
the main problem with multiplayer is that it would require a server. The best free vps I know of is from Oracle Cloud, which can give you a permanent 8gb ram vps for free, and you have to opt-in to any payments so you won't accidentally lose money. The problem with that is that eventually as the game grows you'd need more servers, so unless you do a sponsorship with a hosting service you'd have to spend money on more hosts

**Comment by The-Rock-21** [comment]
> The main problem with multiplayer is that it would require a server. The best free vps I know of is from Oracle Cloud, which can give you a permanent 8gb ram vps for free, and you have to opt-in to any payments so you won't accidentally lose money. The problem with that is that eventually as the game grows you'd need more servers, so unless you do a sponsorship with a hosting service you'd have to spend money on more hosts

Maybe we could do like a limit? Or maybe like first come first serve? I honestly have no idea how vps or hosting services work though so it might now work

**Comment by jo9182** [comment]
> The main problem with multiplayer is that it would require a server. The best free vps I know of is from Oracle Cloud, which can give you a permanent 8gb ram vps for free, and you have to opt-in to any payments so you won't accidentally lose money. The problem with that is that eventually as the game grows you'd need more servers, so unless you do a sponsorship with a hosting service you'd have to spend money on more hosts


If it does grow large enough it could run off of donations, in the meantime, it could have a queue system.
Eaglercraft used a relay system until it eventually got taken, maybe use something like that?
You could also just start by using LAN, I know plenty of people who would love to just have this implemented.

**Comment by kgurchiek** [comment]
I think the best solution would be to limit the amount of players that can play at once and make a queue that people wait in until someone leaves. The problem then would be that people would leave their computer after getting in the queue when they get bored and be afk when they get in, so there would be a lot more inactive players than in a first-come-first-serve system. No matter what system you use you'd also have to limit the amount of games a single person can play, until they get sent back into the queue, otherwise afk players or bots would fill up the servers and no one would be able to play

- selfhosting servers on the client with webrtc could be a good idea, but that would mean you'd only get to play with your friends instead of actual online matchmaking, because officially supporting custom servers in a public list or random matchmaking would be a bad idea, since people could always just mod or entirely rewrite an n-gon client that hosts a server that lets them cheat or could even have something nsfw. Selfhosted servers would also mean that it would be a horrible experience for everyone if the one person that happens to be selected as host happens to have a slow connection.

**Comment by landgreen** [comment]
I encourage ya'll to make a multiplayer version, but I'm just gonna focus on single player.

**Comment by jo9182** [comment]
Now I just gotta get smart enough to actually start making it, where would I even start?

**Comment by corneeme** [comment]
you could work on a local two-player version first

**Comment by interpolation-0** [comment]
peer to peer could also be a viable option through webrtc

**Comment by interpolation-0** [comment]
but as kgurchiek said modifying the client to host a botched server is also an issue

**Comment by jo9182** [comment]
@interpolation-0 
Refer to @kgurchiek 
That could be a viable option, but if the host computer has a bad connection, everyone suffers.

**Comment by interpolation-0** [comment]
but high ping is also an issue

**Comment by jo9182** [comment]
@interpolation-0 
The inputs would need to be transferred to the host and the positions of everything would need to be transferred back to the other players (Assuming the host computer is doing the heavy lifting)

**Comment by kgurchiek** [comment]
now that I've been challenged I'll work on a p2p multiplayer mod, I think just playing the game co-op instead of a pvp game would work better, so I'll probably do that first

**Comment by kgurchiek** [comment]
but for the reasons I mentioned it'll just be for playing with friends, not full multiplayer matchmaking

**Comment by kgurchiek** [comment]
> the data transferred doesn't have to be very large
> 
> what info needs to even be transferred?
> 
> 

the host would have to handle all mobs, bullets, collisions, etc, and send that to all the other players

**Comment by AnnonymousNerd87** [comment]
I think it would be a great idea, but it doesn't fit with how I see n-gon, so I think Landgreen should focus on teaching and n-gon's current state and ideas, not multiplayer. 
Landgreen's to-do list is already so huge and awesome, at this rate we'll get Half-Life 3/Rainworld/Noita/Sci-fi in no time!

**Comment by jo9182** [comment]
@AnnonymousNerd87 
Yeah, he isn’t working on it, another dude in the thread is.
https://github.com/kgurchiek/n-gon-multiplayer

**Comment by AnnonymousNerd87** [comment]
also I generally don't like pings, because they clog my mail
I have had bad experience with my school email getting hundreds of messages from canvas that I can't opt out of, so it has soured my experience with pings

**Comment by AnnonymousNerd87** [comment]
you can still use them, but use them sparingly
