### ISSUE TITLE
Bug: Game Freeze

### ISSUE THREAD

**Issue by The-Rock-21** [landgreen/n-gon#179]
Edit: It seems I wasn't specific enough, let me elaborate. I was playing around with testing mode and there is this command in testing mode where if you click G, you can get every single gun (laser, super ball, shotgun, etc). I then spawned a bunch of tech and started to use them. When I have a lot of tech, and when I pick up a gun, my game just freezes, kind of. I can still move around and pick things up but the screen just stays frozen. It seems to happen randomly. It has happened to me several times
![Screenshot 2024-03-06 6 59 47 AM](https://github.com/landgreen/n-gon/assets/101891804/fa291e24-ddd3-42bd-a8f3-cfd0ca450793)
![Screenshot 2024-03-06 7 00 15 AM](https://github.com/landgreen/n-gon/assets/101891804/ee289748-01bd-4242-8f8a-532b3d24b490)
I can move around and pick things up but it might not be obvious.

**Comment by 136166** [comment]
By what means did you get all the guns?

**Comment by landgreen** [comment]
hmmm I can fix any bug I can produce.  So we need the recipe to make the bug again.  having all the guns doesn't seem to be enough, but if you figure out how to make it occur repeatedly please let me know.

**Comment by The-Rock-21** [comment]
I eidted my comment to be more specific

**Comment by oriaura1** [comment]
if you it ctrl+minus, and then ctrl+plus, it fixes it for me but i still don't know what causes it.

**Comment by landgreen** [comment]
I might have found this bug,  the game crashed because it was drawing circles that had a negative radius.  It only happens late game because you need some crazy values to get it to occur.  I'm gonna close this bug.
