### ISSUE TITLE
Just an Idea. More linked sites to this project.

### ISSUE THREAD

**Issue by billybobj1** [landgreen/n-gon#181]
Can there be more than one linked site to this project?  
Because the only link to the project for me is blocked.

**Comment by jo9182** [comment]
You could easily make your own GitHub page of this if you’d like to.

**Comment by jo9182** [comment]
You could also download the entire project as a zip file, and then open index.html

**Comment by kgurchiek** [comment]
or you could go to https://cornbread2100.com/n-gon-loader
