### ISSUE TITLE
community feedback wanted: confirm close tab?

### ISSUE THREAD

**Issue by landgreen** [landgreen/n-gon#182]
Should I comfirm that you want to close or reload the page?
Is this annoying or does it save your run when you accidentally close out?

window.onbeforeunload = function (e) {
        return "Please click 'Stay on this Page' if you did this unintentionally";
    };
<img width="391" alt="Screenshot 2024-03-07 at 5 52 54 PM" src="https://github.com/landgreen/n-gon/assets/21106570/8d9c0d64-8a70-474a-b89a-b449990b6eea">

**Comment by kgurchiek** [comment]
I think it's a good idea, I've accidentally hit ctrl while playing several times, which closed out my game when I pressed W

**Comment by landgreen** [comment]
yeah I think make it an option, but what should the default be?  ON or OFF

**Comment by kgurchiek** [comment]
What if it's off by default but there's a junk tech that enables it so people know it exists? A lot of people never even check the settings tab, so maybe if the tech says in the subtext that it's in settings more people will notice

**Comment by landgreen** [comment]
A JUNK tech sounds good.
Also I can run code when you try to exit.
What should the JUNK tech do each time you cancel exiting the game?

For example I can spawn power ups when you try to exit but cancel.
I'd want something fun and maybe strong in certain situations, but normally just dumb.

**Comment by landgreen** [comment]
ok I'm thinking each time you cancel you get +20% damage but you have a 1 in 5 chance to close the game tab?

**Comment by kgurchiek** [comment]
20% chance to send you to a different version? Or maybe to send you to planetesimals?
