### ISSUE TITLE
(Bug?) Testing mode is locked in why difficulty.

### ISSUE THREAD

**Issue by jo9182** [landgreen/n-gon#183]
Testing mode remains locked in why difficulty even after collecting all of the undefined and completing the final level, is this intentional?

**Comment by oriaura1** [comment]
I have the same thing it appears to be intentional. it gives a message "testing mode is disabled for this difficulty".

**Comment by kgurchiek** [comment]
testing mode being disabled for why mode is definitely intentional, but I assume the softlock it causes was overlooked

**Comment by landgreen** [comment]
ok I changed it so you can go past the final boss if you win on why mode.
