### ISSUE TITLE
How do you make community levels?

### ISSUE THREAD

**Issue by BannanaPants** [landgreen/n-gon#184]
I noticed that you can enable community levels but I don't know how to make my own. I can't find a level creator mode or information in the respiratory to make it. Can someone please explain how you make one to me?

**Comment by kgurchiek** [comment]
Here's a quick rundown:
download the source code and open it in a code editor of your choice. I personally used VS Code to make mine. The go in `level.js` (in the `js` folder) and find "`template() {`. That is the function that creates a basic template level. To easily test out the level, I'd recommend copying it into `initial()` (the first level).

If you need any more explanation or help it'll be a lot easier to communicate on the community discord server, there's a dedicated channel to map-making with plenty of people to help you: https://discord.gg/bJdKZUYT

**Comment by corneeme** [comment]
I also remember in a old "issue" someone made a link to help with that type of stuff, I think it might've been in the arena issue

**Comment by kgurchiek** [comment]
@corneeme are you talking about this? https://n-documentation.glitch.me/

**Comment by corneeme** [comment]
oh yeah! I have been looking for that, thanks

**Comment by AnnonymousNerd87** [comment]
should this issue be closed as stale/solved or should we keep it for new players?

**Comment by corneeme** [comment]
lets leave it open it could be helpful in the future
