### ISSUE TITLE
game locked at 30fps in browser

### ISSUE THREAD

**Issue by oriaura1** [landgreen/n-gon#185]
when loading the file through the index.html on chrome os the game seems to be moving slowly. i have turned on the performance junk tech and it says it is constantly going at 30fps. i have the limit fps to no cap, and even after restarting my device, clearing my cache, and updating the file the issue persists.

**Comment by jo9182** [comment]
Just to comment, I don’t have this issue when running it through a downloaded zip file on my Chromebook.

**Comment by oriaura1** [comment]
alright, i was posting it because others might have the same issue,. if you don't it's probably my chromebook. thanks!
