### ISSUE TITLE
[Bug] Broken Experiment Mode + Time Dilation(?)

### ISSUE THREAD

**Issue by sulplife** [landgreen/n-gon#186]
Clicking on any tech, switches the name and description with another tech. No idea what causes it and it persists after restarting the tab. For example, clicking on Nitinol swaps it with Tungsten Carbide, locking all skins and displaying Tungsten Carbide's picture with Nitinol's description and name. 

Time Dilation also doesn't work properly, removing the velocity from every projectile (including enemy ones) which causes all bullets to fall down immediately after the field is deactivated. Needle Nail Gun specifically is extra bugged, it fires all the shots again after the field deactivates. The needles fired while time is stopped fall to the ground like everything else but then are fired again right afterwards.

Last "bug" has been in the game for a while so it probably is intentional but when firing missiles with the MIRV tech while time is stopped, the missiles will all be fired at once from N once time resumes instead of how it works normally without the MIRV tech.

I will try to replicate the bugs on a different computer later and can attach videos if needed.

Example of the first bug:

![Screenshot 2024-03-13 09 16 26](https://github.com/landgreen/n-gon/assets/103660736/2ce6b99b-e294-4190-9026-0df83e9def45)

![Screenshot 2024-03-13 09 16 43](https://github.com/landgreen/n-gon/assets/103660736/8786b7a7-9b76-4f1b-bda4-d424344c55e2)

**Comment by landgreen** [comment]
Thanks, that's a huge bug.  I guess I didn't ever use the experiment mode.  I am posting a fix right now
