### ISSUE TITLE
Time dilation cancels bullet velocity

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#187]
Time dilation cancels the velocity of bullets, so if you shoot while using TD or shoot and then use it most bullets will get stuck in midair and despawn or fall straight to the ground, depending on the bullet type

**Comment by landgreen** [comment]
I can't reproduce this bug with time dilation and any gun.  I didn't have any tech.

**Comment by kgurchiek** [comment]
https://github.com/landgreen/n-gon/assets/90143063/2597aa0d-5bfd-43ac-8f13-1e68b2eef7b9

I'm using Firefox

**Comment by The-Rock-21** [comment]
That doesn't seem to be happening to me

**Comment by landgreen** [comment]
Thanks for the video.  This looks like a problem with upgrading to the new 0.19 version of matter.js physics engine.  I was testing on the 0.18 physics engine.  There aren't any performance gains with 0.19 so unless there is some large changes in matter.js I'll just stay at 0.18.
