### ISSUE TITLE
Random unused momentum?

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#188]
While working on multiplayer I noticed there are several times in harpoon's code where a "momentum" variable is created, but I couldn't find anywhere it's used. Is this a remnant of something scrapped or am I just missing something?

example: bullet.js line 1516: `const momentum = Vector.mult(Vector.sub(this.velocity, player.velocity), (m.crouch ? 0.0001 : 0.0002))`

**Comment by landgreen** [comment]
looks to me like it's use in the next two lines
                        const momentum = Vector.mult(Vector.sub(this.velocity, player.velocity), (m.crouch ? 0.0001 : 0.0002))
                        player.force.x += momentum.x
                        player.force.y += momentum.y

**Comment by kgurchiek** [comment]
oh I'm stupid, I forgot that I deleted that part for the client-side code🤦‍♂️. Thanks for the help
