### ISSUE TITLE
Updating and old zip files

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#192]
This isn't an issue for most players, but because my school has n-gon blocked I have to use the index.html file to open it instead of the browser version, and it can be kind of a pain to download and delete it every time an update comes out
I'm fine with losing my undefined and tinker but my drive isn't very organized and organizing it can take some time
I wouldn't know how to fix it but for anyone else who is affected maybe we can crowd source ideas for a minor qol fix

**Comment by corneeme** [comment]
you could always fork this repo and then make a link from there but the problem with that is that they could block Github, preventing you entirely, it might be a bit tedious, but its the better option in the long run

**Comment by oriaura1** [comment]
for the most part schools won't block github because you need it for some projects in certain courses.

**Comment by AnnonymousNerd87** [comment]
its not as much about being worried that github might get blocked, its just a mild annoyance of deleting and downloading a new file every time. I know github won't be blocked anytime soon, and I don't care about undefined, and actually like the optional challenge it provides, I'm just too lazy to take 30 seconds to delete and download a new file about once a week ;)

**Comment by 136166** [comment]
N-gon, blocked? Interesting...

**Comment by RustyBust** [comment]
I mean, some people might treat it as a game, or play it during class.

**Comment by epicgranol** [comment]
im pretty sure ur tinker and undefined dont get lost i think but idk

**Comment by AnnonymousNerd87** [comment]
Sorry I vanished over spring break, I was away from my computer for a while. (as most people should be!)

N-gon has been blocked at my school for a full year now, but due to an oversight in Lightspeed (the 'service' my school uses), and it being classified as games and not an overall block list, you could open the tab outside of school when sites classified under games **are** allowed, then just don't reload the page for school hours to keep it open. Recently, probably because most people only saw it as a great game and nothing more, it was reclassified as Security.proxy. As you may guess, Security.proxy is never allowed. (another aspect may be that some students were using alternate methods such as s2bot4scratch to 'unblock' anything allowed by google itself, up to and including porn. so for the people who just used s2bot for n-gon, it got some bad press)

A main reason that people are playing n-gon or even know it exists is that three years ago coolmathgames was blocked because the 8th graders were playing it in class, causing an effect best explained in marvels spider man, wherein a leader of a crime syndicate was arrested, resulting in "anyone with a crowbar and some ego" rising up to attempt to take his place, causing crime rates to multiply nearly tenfold. People started to make their own game sites, some of which are still up today. This also gave people the idea of a 'universal unblocker', a site/app/security bypass to remove/bypass/hide from Lightspeed entirely. N-gon was 'found' one and a half years ago, and was treated by everyone as just another game website, to be used until blocked. But I liked the game, more than its simple mechanics, and enjoyed watching it grow and evolve over the years to come. Now I'm here, on one of the most positive communities on the internet!

Sorry for posting something so serious on April fools, but today was the first day I could get on my computer

oh and the two paragraph post yeah that too XD

**Comment by AnnonymousNerd87** [comment]
oh and tinker and undefined only save on the website, not the file

**Comment by AnnonymousNerd87** [comment]
so if you clear your cookies it doesn't save

**Comment by kgurchiek** [comment]
all saved data (tinker, lore, entanglement, game count, etc.) are saved in localStorage, which is different for each domain, meaning your n-gon progress won't be there if you use a different file or website

**Comment by 136166** [comment]
Yeah, when you clear the Cookies, there is no more 'undefined' or 'tinker' or anything.

**Comment by AnnonymousNerd87** [comment]
@landgreen, I noticed the update, n-gon isn't the only thing that's blocked, its actually any url starting in landgreen.github.io 
![Screenshot 2024-04-03 1 19 44 PM](https://github.com/landgreen/n-gon/assets/164103476/2cc140e8-4ae0-47d7-80dc-6b8ec829f48c)
not crucial because I use the zip file, but if that was the intention then you would have to change the entire url

**Comment by landgreen** [comment]
oh I wasn't trying to get around the blocks from your schools.  I just wanted the name to be n-gon instead of sidescroller.

**Comment by AnnonymousNerd87** [comment]
I know, just informing you

**Comment by AnnonymousNerd87** [comment]
I kind of don't want too much to change around the url because if n-gon becomes too popular github itself might be banned and that would suck.

**Comment by creator1116** [comment]
I have hosted n-gon on vercel  here is the like I hope this solves your problem https://n-gon-rouge.vercel.app/

**Comment by creator1116** [comment]
@AnnonymousNerd87 just to notify you did you notice that your ip is visible in the screenshot above
![image](https://github.com/landgreen/n-gon/assets/133981966/90f8fdfa-9d28-48c7-8ac3-31d84f6a8bca)

**Comment by AnnonymousNerd87** [comment]
I deleted it, thanks, I never knew

**Comment by AnnonymousNerd87** [comment]
can you delete your comment @creator1116 ?

**Comment by AnnonymousNerd87** [comment]
this proves the internet is a hive mind / infinite monkey theorem

**Comment by creator1116** [comment]
yay I am definitely part of it

**Comment by creator1116** [comment]
also comment deleted

**Comment by creator1116** [comment]
by the way just saying this website should solve your problems: interstellar-pro.vercel.app
sorry if you think I use vercel too much but I'm broke and vercel is free :D

**Comment by AnnonymousNerd87** [comment]
aaaaaaaah about blank cool

**Comment by AnnonymousNerd87** [comment]
I've used that before with other stuff like aaronos

**Comment by AnnonymousNerd87** [comment]
is it a proxy or just another game darksite

**Comment by AnnonymousNerd87** [comment]
thanks!

**Comment by AnnonymousNerd87** [comment]
I forked the repo and made my own (Dumb) n-gon!
https://github.com/AnnonymousNerd87/AnnonymousNerd87.github.io

**Comment by creator1116** [comment]
Nice!

**Comment by creator1116** [comment]
Do you have matrix?

**Comment by AnnonymousNerd87** [comment]
what's matrix, like a matrix of numbers or the movie?

**Comment by Masbirb** [comment]
> Sorry I vanished over spring break, I was away from my computer for a while. (as most people should be!)
> 
> 
> 
> N-gon has been blocked at my school for a full year now, but due to an oversight in Lightspeed (the 'service' my school uses), and it being classified as games and not an overall block list, you could open the tab outside of school when sites classified under games **are** allowed, then just don't reload the page for school hours to keep it open. Recently, probably because most people only saw it as a great game and nothing more, it was reclassified as Security.proxy. As you may guess, Security.proxy is never allowed. (another aspect may be that some students were using alternate methods such as s2bot4scratch to 'unblock' anything allowed by google itself, up to and including porn. so for the people who just used s2bot for n-gon, it got some bad press)
> 
> 
> 
> A main reason that people are playing n-gon or even know it exists is that three years ago coolmathgames was blocked because the 8th graders were playing it in class, causing an effect best explained in marvels spider man, wherein a leader of a crime syndicate was arrested, resulting in "anyone with a crowbar and some ego" rising up to attempt to take his place, causing crime rates to multiply nearly tenfold. People started to make their own game sites, some of which are still up today. This also gave people the idea of a 'universal unblocker', a site/app/security bypass to remove/bypass/hide from Lightspeed entirely. N-gon was 'found' one and a half years ago, and was treated by everyone as just another game website, to be used until blocked. But I liked the game, more than its simple mechanics, and enjoyed watching it grow and evolve over the years to come. Now I'm here, on one of the most positive communities on the internet!
> 
> 
> 
> Sorry for posting something so serious on April fools, but today was the first day I could get on my computer
> 
> 
> 
> oh and the two paragraph post yeah that too XD

Same thing happened at my school 
Don't block the common game sites or you will start an arms race as I called it

**Comment by RustyBust** [comment]
> Same thing happened at my school
Don't block the common game sites or you will start an arms race as I called it

Same

**Comment by creator1116** [comment]
> what's matrix, like a matrix of numbers or the movie?

no like matrix chat

**Comment by creator1116** [comment]
its a free and open-source discord alternative

**Comment by AnnonymousNerd87** [comment]
this seems mostly resolved. Thanks to all the people who contributed!
