### ISSUE TITLE
very minor issue, just mild classification issue

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#193]
N-gon is a rouge-like, not rouge-lite. Rouge-lites include metaprogression, like Hades, while rouge-likes feature permadeath. N-gon is a rouge-like because only undefined and tinker save between runs, with undefined being essentially devtools and tinker being junk. 
Additionally, I feel that labeling n-gon as a side scroller can be somewhat misleading because traditionally, side scrollers feature a linear moving camera that isn't influenced by player actions, like jetpack joyride. 
I don't think this should be classified as an issue because it is so minor but I don't have discord so this is my best option.

**Comment by jo9182** [comment]
By definition this game is a sidescroller; a sidescroller is a 2d game in which the camera follows a player in a side view (e.g. dead cells is technically a side scroller).

Undefined would count as permanent progression, same for some of the junk techs that have permanent effects. You also gain more techs at the beginning of each run based on how far you got in the previous. There is technically N-gon lore.

**Comment by AnnonymousNerd87** [comment]
Well just because n-gon has lore and a select few aspects of metaprogression doesn't mean it isn't a rouge-like. Games like Noita and Splunky are considered rouge-likes, and both have more lore than n-gon. About that side scroller comment, I was going off of the finer definition, not just the camera angle, but after checking some sources I can tell I am of the minority. I was thinking of a more specific type of camera movement that wasn't influenced by player input, but checking the Wikipedia page told me that it was a sub-category.

**Comment by kgurchiek** [comment]
ig entanglement and the extra tech for doing well in previous games are technically metaprogression, but since they only affect the game immediately after and have no long-lasting effects I wouldn't really call it that.

**Comment by AnnonymousNerd87** [comment]
I didn't even know entanglement was related to death, I thought it was just a random event. Also the tech for doing well in previous runs makes tech rarer later on in the run so it is almost detrimental.

**Comment by AnnonymousNerd87** [comment]
plus it isn't "progression", its just a small one-off boost

**Comment by kgurchiek** [comment]
entanglement is supposed to be your "corpse" from the last game, it spawns in the same map and position you died at and has all of your previous run's tech

**Comment by AnnonymousNerd87** [comment]
Huh, I never knew that. I always thought it was some random sci-fi lore thing showing the universe falling in on itself, but I guess entangling your corpse from one universe with another universe would cause that.

**Comment by landgreen** [comment]
> I didn't even know entanglement was related to death, I thought it was just a random event. Also the tech for doing well in previous runs makes tech rarer later on in the run so it is almost detrimental.

tech chance scales by level not by how much tech you have, so getting early tech isn't detrimental

I do regret naming the folder sidescroller, but I don't want to change it so that people can find it.  I kinda see n-gon as what ever game type I'm currently playing.  Right now that's Balatro. So, n-gon is a deck builder with cool combos and synergies.

**Comment by kgurchiek** [comment]
What if you rename it to n-gon and then redirect /sidescroller to the new /n-gon page?
