### ISSUE TITLE
{Major Bug} Bonus from Heals, Research, Ammo doesn't reset between runs

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#195]
I beat a run with 0 undefined on normal, lots of max health using Quenching + Heals, started a new run with community maps enabled on normal and one of the tech I got in the tech boost had Heals with 31 Heals. This could be game breaking if abused. 
![Screenshot 2024-03-22 2 23 21 PM](https://github.com/landgreen/n-gon/assets/164103476/9f0045de-a130-4058-881d-151c50eb5f3d)

**Comment by AnnonymousNerd87** [comment]
Second screenshot after taking path integral;
![Screenshot 2024-03-22 2 28 23 PM](https://github.com/landgreen/n-gon/assets/164103476/8228bb76-b3fa-41b3-b372-736765c19af2)

**Comment by landgreen** [comment]
good catch, I never play 2 games in a row.

I'll fix in next patch, thanks

**Comment by jo9182** [comment]
Gonna be honest, I thought that was an intended feature.
