### ISSUE TITLE
3 research instead of 1 at run start

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#196]
after dying to tilinat (the maze level), I reset the run and got the gun, Heals, and THREE research. I had ansatz so maybe it was giving more? I don't know what caused this one. 
![Screenshot 2024-03-22 3 00 01 PM](https://github.com/landgreen/n-gon/assets/164103476/7ea32f2b-e2f7-4b86-98de-65b48e2d1b8d)

**Comment by jo9182** [comment]
Research at the start of a run varies on how far you got and how much research you had in the previous run, this is normal.

Just so you aren’t surprised by it later, the heals, research, and ammo powerups (the ones you get from research) are also upgraded between runs.

**Comment by AnnonymousNerd87** [comment]
ok, I just never got more than 1 before without getting the tech boost
