### ISSUE TITLE
laser energy drain typo

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#199]
the displayed energy drain for laser is multiplied by 600 when it should be multiplied by 6,000 (60 fps x 100 energy)

**Comment by landgreen** [comment]
Where is this text?  laser gun?  a tech?

**Comment by landgreen** [comment]
my laser gun says "drains 1.68 energy per second"

**Comment by landgreen** [comment]
ok I figured out what you meant,  thanks.
