### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TRudenko22** [landgreen/n-gon#20]
I just want to say that this project is amazing. I love all the physics concepts you've implemented and I *absolutely* adore the Wikipedia links. Thank you for making this. I thoroughly enjoy playing n-gon when I have a spare hour or 2.

**Comment by Yaron-Ha** [comment]
Ehm that's not an issue, maybe contact Landgreen in the Discord?

**Comment by landgreen** [comment]
Thanks! I teach physics so I have to make it kinda educational.
