### ISSUE TITLE
closed loop

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#200]
Power ups spawned by techs will automatically be absorbed
+5% dupe

**Comment by Masbirb** [comment]
Despite the day this was posted on this is not a joke suggestion
It solves a very real problem in the game where CERTAIN techs spawn so many power ups  that it can take 30 minutes to spawn alone

**Comment by Masbirb** [comment]
An alternative tech I came up with is 
Phagocytosis
When 3 power ups are all touching each other they become one power up with the value 4 of that power up

**Comment by AnnonymousNerd87** [comment]
sounds like a good JUNK tech, maybe too minor for tech and could have some minor bugs/annoyances such as wasting damage power ups or field power ups if you already have a field

**Comment by landgreen** [comment]
I think people have fun picking up spawned tech.  It's a bit of a reward.

**Comment by Masbirb** [comment]
> I think people have fun picking up spawned tech.  It's a bit of a reward.

You have a point but once you start collecting power ups that spawn in amounts that reach scientific notation it stops being fun and just take a long time to spawn and hold down spacebar
Ammo has this problem the worst though
