### ISSUE TITLE
Collision invincibility by default

### ISSUE THREAD

**Issue by ultracodez** [landgreen/n-gon#202]
Can we have invulnerability after a collision by default? I just played against the power up guy who steals your tech and I got cornered, had all my tech stolen and killed because my gun was too weak without anything, I couldn't escape without any tech, and the bot kept slamming me in a corner where I couldn't leave :/

**Comment by landgreen** [comment]
You currently get 1/2 a second of invulnerability after a collision.
How long do you think it a good length of time to be invulnerable?
(also I was considering making you intangible as well but I haven't coded that)

**Comment by AnnonymousNerd87** [comment]
I feel like the tech stealer boss is too extreme in most runs, with you either losing almost all your tech or just disintegrating it in under a second depending on your build. it forces you to go glass cannon or lose your build and I feel that it doesn't scale well with lower difficulty because nerfing the damage doesn't nerf the tech stolen.

**Comment by landgreen** [comment]
I should probably reduce the powerUpBoss health a bit and add a 1/2 second boss invincibility like the baby version has.

**Comment by kgurchiek** [comment]
I personally don't feel like only certain builds can counter powerupBoss, you can pretty easily counter it with most fields. Any field that can deflect (especially perfect diamagnetism) can prevent it from hitting you at all, and even if the field doesn't deflect or you're out of energy it isn't too hadd to just juke it out and dodge it

**Comment by ultracodez** [comment]
@kgurchiek  the issue arrives when you're using an energy based weapon. I was using nail gun with the infinite ammo ice upgrade with time duration. In this scenario it's impossible to defend yourself and deal damage at the same time.

Personally I think the boss is well balanced, I think a half second of intangibility would be good enough. I haven't ñooked at the code yet but perhaps I can help implement this by taking some code from metamaterial cloaking.

P.S. an awesome tech would be if you could become intangible during time dilation (a debuff to balance this if too OP would be it doesn't stop time but instead allows you to go to a higher-dimension [intangible but time doesn't stop])

**Comment by landgreen** [comment]
I should mention that powerUpBoss spawns an extra heal and ammo, so it should be a bit harder then other bosses.

**Comment by kgurchiek** [comment]
@ultracodez even without a field, you can just get the boss to move back and forth trying to attack you so that you can easily jump over it to dodge the attacks without having to use your field

**Comment by ultracodez** [comment]
@kgurchiek Yeah, I know but in this specific scenario, especially in small maps like the acid one with the teleporter, if you get cornered you are just screwed with no possible escape and/or counterplay

**Comment by AnnonymousNerd87** [comment]
> @kgurchiek the issue arrives when you're using an energy based weapon. I was using nail gun with the infinite ammo ice upgrade with time duration. In this scenario it's impossible to defend yourself and deal damage at the same time.
> 
> Personally I think the boss is well balanced, I think a half second of intangibility would be good enough. I haven't ñooked at the code yet but perhaps I can help implement this by taking some code from metamaterial cloaking.
> 
> P.S. an awesome tech would be if you could become intangible during time dilation (a debuff to balance this if too OP would be it doesn't stop time but instead allows you to go to a higher-dimension [intangible but time doesn't stop])

that time dilation tech is useless because boson composite does the same thing but better

**Comment by corneeme** [comment]
it could be by default in easy mode
