### ISSUE TITLE
Simulation speed is dependent on refresh rate

### ISSUE THREAD

**Issue by radixerus** [landgreen/n-gon#203]
Usually my refresh rate is 60fps, but recently i discovered my new monitor can go up to 120. It's been lots of fun playing games with my buttery smooth frames, but I can't play n-gon because at 120 frames, the game is twice as fast. I hope this isn't an impossible engine bug like it so often is, but if it is I won't cry about it. Or, at least I won't _tell_ you i cried about it.

**Comment by kgurchiek** [comment]
there's a frame rate cap option in settings
