### ISSUE TITLE
(Tech Suggestion) Positive Void Coefficient

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#204]
Whenever `m` enters a pool of slime, a deadly pulse of radiation is emitted, pushing enemies away and damaging them. 

Theoretically used to deal with hordes of mobs that are herding the player into slime. 

Yes, I just watched Chernobyl, how could you tell?

**Comment by Masbirb** [comment]
Maybe when ever M is irradiated because slime is only in like 10% of maps

**Comment by AnnonymousNerd87** [comment]
maybe whenever m is subjected to dot so it also applies to things like the electric tech and black holes, but all of it has a cool down (1-5 sec?)

**Comment by landgreen** [comment]
Too situational.  sorry.

**Comment by creator1116** [comment]
how about slightly nerfing the ability but making it a field
