### ISSUE TITLE
Missile Upgrade Idea: Guided missile

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#205]
this upgrade would make all missiles follow the mouse allowing the player to guide the missile.

**Comment by Masbirb** [comment]
May need another reason to get this but it is currently sounds like a alright tech but does so little I would never take it

**Comment by Masbirb** [comment]
Maybe missiles can stay in the air for longer

**Comment by creator1116** [comment]
maybe like anti-shear topology? 30%?

**Comment by Masbirb** [comment]
Probably a bit more

**Comment by Masbirb** [comment]
In addition you are giving up the very good missile default homing so it may need a much better buff like it gains something the longer you keep a missile in the air

**Comment by creator1116** [comment]
or maybe the missiles last forever until they collide with an enemy. the longer you keep a missile in the air the more damage it does?

**Comment by landgreen** [comment]
drones are guided
I don't pan to extend this to missiles mostly to not reward fighting bosses from around a few corners.
