### ISSUE TITLE
Tech: Special Relativity

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#209]
Energy generation increases in exponential proportion to your velocity

Not higgs mechanism, nitinol (maybe)

**Comment by landgreen** [comment]
good ideas.  might be a while though.  I'm in a map making phase of development.

**Comment by AnnonymousNerd87** [comment]
I just finished a math test and am bored waiting for a response to my issue with wave so I'm going to code this in Dumb n-gon, be back in a bit
