### ISSUE TITLE
Not an issue just a discord server

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#210]
it recently came to my attention that all the invite links to the community discord had expired so I made a new discord server
https://discord.gg/ucYyCk4n

**Comment by Masbirb** [comment]
The real one is here

https://discord.gg/zC7gEPagQU

**Comment by creator1116** [comment]
> The real one is here
> 
> https://discord.gg/zC7gEPagQU By real I mean more active and old
the invite is invalid
at least it says that for me so can you re-send it
