### ISSUE TITLE
picking up a white power up (they're called "entanglements" I believe) will sometimes freeze the game, making you reload in order to continue playing

### ISSUE THREAD

**Issue by nbnbnbnbnbnbnbnbnbnbnb** [landgreen/n-gon#214]
Sometimes (maybe like 1/3 of the time), when you grab one, instead of providing you with an upgrade choice menu, it will make your camera weird, turn everything white, and freeze the game. If you try to fire, your ammo will decrease but nothing will fire. You can't move, and sometimes you slowly die (after death, the game will fade to white like normal, but never fade back in until you reload the page.) 
Is this a feature/known issue? It has cost me numerous good runs.

**Comment by nbnbnbnbnbnbnbnbnbnbnb** [comment]
this may link into issue #208, but it was marked closed/fixed 5 days ago and the bug still occurs today.

**Comment by nbnbnbnbnbnbnbnbnbnbnb** [comment]
the first screenshot shown in issue #118 is what it looks like when it crashes. But, it isn't temporary, unless you count having to reload the web page as temporary.

**Comment by 3xionDev** [comment]
i believe it's the same bug as shown in #208.

```
text += powerUps.instantTechTextTechText(choose, `powerUps.choose('tech',${choose})`)
```

It's a very easy fix, as landgreen just needs to change "instantTechTextTechText" to "instantTechText," and, looking at cornbread's screenshot, it seems like this function is referenced in "Object.normalLoop" and "cycle," both of which affect the game loop (I believe), which would cause it to freeze up. This bug will be patched in the next update.

**Comment by landgreen** [comment]
yeah this was fixed, it will show up in next patch
