### ISSUE TITLE
Suggestion: Gojo's infinity

### ISSUE THREAD

**Issue by NV4s** [landgreen/n-gon#216]
Basically, add a standing wave upgrade that slows all projectiles and lasers by dividing their speed by half every 100 milliseconds until they slow to a complete stop. Also, allow m to make mobs go splat if pushed against the standing wave and a wall/barrier.

Edit 1: Small radius but is extremely overpowered in terms of stopping projectiles and mobs (let's nerf it a little to allow laser and explosions). Also mobs take damage if pressed against the barrier (standing wave upgraded) **and** a wall.

Edit 2:
Name: Gojo's Wave
Type: Upgrade (Tech) (requires standing wave, **not** surface plasmons, spherical harmonics, expansion)
Link: [https://jujutsu-kaisen.fandom.com/wiki/Limitless#Neutral_Limitless:_Infinity](https://jujutsu-kaisen.fandom.com/wiki/Limitless#Neutral_Limitless:_Infinity)
Images: 

![satoru-gojo-hanami](https://github.com/landgreen/n-gon/assets/116988737/faf1759b-af92-4604-a093-686eaf0f3e36)
![Gojos_Infinity3-ezgif com-webp-to-gif-converter](https://github.com/landgreen/n-gon/assets/116988737/19a9f8cd-bd3c-4e29-8f77-8fe3351e211f)
![Gojos_Infinity-ezgif com-webp-to-gif-converter](https://github.com/landgreen/n-gon/assets/116988737/56cbb364-41d5-4d5d-9499-46e88ad5641a)

Effects: 
Pros
- If mobs are colliding with a wall **while** in field, mob -5% of max health every second it's being pushed
- If mobs/projectiles enter field, slow their speed by 1/2 every 500 milliseconds
Cons
- Reduces radius by 200%
- Subtract 50% Max Health
- Remove 33% Defense
- 10% Slower
+ 33% Junk Tech
**TBA**

**Comment by Masbirb** [comment]
100 milliseconds is way too fast it would mean nothing would ever move
Maybe every 100 milliseconds the speed is reduced by .1%

**Comment by corneeme** [comment]
I would like to see what that could do with other techs

**Comment by AnnonymousNerd87** [comment]
also this would be laggy and annoying to code. Maybe increase the knockback by an obscenely high number, (5x?) but disable all block effects (bremsstrahlung, ice9, etc.) and cause it to deal damage when mobs are forced into walls by it. 

I might try this in Dumb n-gon https://annonymousnerd87.github.io/

**Comment by NV4s** [comment]
In lore, the speed is divided by half which is why I wanted it. Think of a bunch of flying knives about to hit you and then just stop.

**Comment by Masbirb** [comment]
The speed of all enemies will be divided by like 1024 every second

**Comment by NV4s** [comment]
Bruh why. It should make enemies very slow in radius, not just a little slow.

**Comment by AnnonymousNerd87** [comment]
the miscommunication is that alex wants a powerful slow in a small radius, while mason wants a weak slow globally

**Comment by AnnonymousNerd87** [comment]
also I think it should be a projectile/mob repulsion field not just a slow. 

![Screenshot 2024-04-22 3 32 00 PM](https://github.com/landgreen/n-gon/assets/164103476/e3531929-6d8b-4f49-8ff3-86e1ac57b8b2)

**Comment by Masbirb** [comment]
Oh it is meant to be a small radius 
I still believe that dividing speed by 2 every tenth of a second is far too overkill

**Comment by AnnonymousNerd87** [comment]
no because the base field is 100% knockback, so an extreme slow with a small radius is necessary to fully replace the shield

**Comment by Masbirb** [comment]
> also I think it should be a projectile/mob repulsion field not just a slow. 
> 
> 
> 
> ![Screenshot 2024-04-22 3 32 00 PM](https://github.com/landgreen/n-gon/assets/164103476/e3531929-6d8b-4f49-8ff3-86e1ac57b8b2)
> 
> 

That would work fairly well

**Comment by AnnonymousNerd87** [comment]
a repulsion field is good because it gets them out of the way so you don't accidentally run into them, without just making everything except lasers useless

**Comment by AnnonymousNerd87** [comment]
it would drain energy proportional to the number of projectiles/mobs in the aoe, and their mass * speed against the field

**Comment by AnnonymousNerd87** [comment]
it works well in Noita, so it should work well in n-gon

**Comment by LinuxRocks2000** [comment]
You can already get consistent slowing radii with eddy current brake or that healing tech.

**Comment by NV4s** [comment]
There are some stuff I may remove and separate into 2 different upgrades (splat against wall and op slowing will most likely be separated)

**Comment by landgreen** [comment]
this seems similar to eddy current.
<img width="381" alt="Screenshot 2024-04-23 at 6 06 50 PM" src="https://github.com/landgreen/n-gon/assets/21106570/f001d31a-8d91-4463-a19e-99785a524c6f">

**Comment by AnnonymousNerd87** [comment]
that's why I think it should be a repulsion to be more unique

**Comment by landgreen** [comment]
repulsion is how the default shields work

**Comment by AnnonymousNerd87** [comment]
I mean a slow, consistent repulsion over a larger area, like eddie current
brake

**Comment by NV4s** [comment]
I mean maybe a field that slows enemies instead of knocking them back

**Comment by kgurchiek** [comment]
in my opinion that would make the most sense for standing wave so you can shoot the mobs as they get stuck in slo-mo in front of you

**Comment by NV4s** [comment]
That's my point that I want to have

**Comment by NV4s** [comment]
The splat effect can be an entirely different upgrade.

**Comment by landgreen** [comment]
<img width="381" alt="Screenshot 2024-04-24 at 8 39 49 AM" src="https://github.com/landgreen/n-gon/assets/21106570/cc7b6dae-d48a-4d29-aab4-ea998f0ec086">
so this effect?

**Comment by NV4s** [comment]
Yea but a permanent field that has this area of effect

**Comment by kgurchiek** [comment]
[Screencast from 2024-04-24 12-54-32.webm](https://github.com/landgreen/n-gon/assets/90143063/c4493e33-fd22-476f-b115-cbbd587b34f6)

Maybe something like this where it slowly pushes things away? (In this example it gets stronger when in an inner circle)
```js
m.harmonic3Phase = () => { //normal standard 3 different 2-d circles
    const fieldRange1 = (0.75 + 0.3 * Math.sin(m.cycle / 23)) * m.fieldRange * m.harmonicRadius * 2
    const fieldRange2 = (0.68 + 0.37 * Math.sin(m.cycle / 37)) * m.fieldRange * m.harmonicRadius * 2
    const fieldRange3 = (0.7 + 0.35 * Math.sin(m.cycle / 47)) * m.fieldRange * m.harmonicRadius * 2
    const netFieldRange = Math.max(fieldRange1, fieldRange2, fieldRange3)
    ctx.fillStyle = "rgba(110,170,200," + Math.min(0.6, (0.04 + 0.7 * m.energy * (0.1 + 0.11 * Math.random()))) + ")";
    ctx.beginPath();
    ctx.arc(m.pos.x, m.pos.y, fieldRange1, 0, 2 * Math.PI);
    ctx.fill();
    ctx.beginPath();
    ctx.arc(m.pos.x, m.pos.y, fieldRange2, 0, 2 * Math.PI);
    ctx.fill();
    ctx.beginPath();
    ctx.arc(m.pos.x, m.pos.y, fieldRange3, 0, 2 * Math.PI);
    ctx.fill();
    //360 block
    for (let i = 0, len = mob.length; i < len; ++i) {
        if (Vector.magnitude(Vector.sub(mob[i].position, m.pos)) - mob[i].radius < netFieldRange && !mob[i].isUnblockable) { // && Matter.Query.ray(map, mob[i].position, m.pos).length === 0
            mob[i].locatePlayer();
            const distance = Math.sqrt((mob[i].position.x - player.position.x)**2 + (mob[i].position.y - player.position.y)**2);
            const direction = Vector.normalise(Vector.sub(mob[i].position, m.pos));
            const fieldRanges = [fieldRange1, fieldRange2, fieldRange3].sort((a, b) => b - a);
            if (distance < fieldRanges[0]) Matter.Body.setVelocity(mob[i], { x: mob[i].velocity.x * 0.9, y: mob[i].velocity.y * 0.9 });
            if (distance < fieldRanges[1]) Matter.Body.setVelocity(mob[i], { x: mob[i].velocity.x + direction.x * 0.5, y: mob[i].velocity.y + direction.y * 0.5 })
            if (distance < fieldRanges[2]) Matter.Body.setVelocity(mob[i], { x: mob[i].velocity.x + direction.x, y: mob[i].velocity.y + direction.y })
       }
   }
}
```

**Comment by AnnonymousNerd87** [comment]
looks great!

**Comment by NV4s** [comment]
That's excellent @kgurchiek! Besides the fact that the field isn't more forced against the mob, this is mostly the idea I'm getting. Make it less flexible with aerodynamics when interacting with the field and more pushing. (My idea is to make the force more flexible than standing wave, but less flexible compared to your code addition).

**Comment by AnnonymousNerd87** [comment]
also make it drain energy based on the number and mass of mobs in the aoe

**Comment by NV4s** [comment]
@AnnonymousNerd87 What is your discord user in the n-gon discord? (The old and more active one) Also @kgurchiek , make the field drain energy proportionally based on the mass and speed of the mob coming to you (kinda like the basic field draining energy based on the mass of blocks and your output of it).

**Comment by AnnonymousNerd87** [comment]
I don't have discord bc its blocked by lightspeed

**Comment by NV4s** [comment]
@AnnonymousNerd87 That's wild. Same here, but on CKA.

**Comment by AnnonymousNerd87** [comment]
I have always had this quest for the holy grail, the one, the universal
***@***.***, but ever since reading Cory Doctorow that quest has been burning
with a vengeance. If you haven't read Little Brother yet I would highly
recommend it to anyone in the open source community.

**Comment by NV4s** [comment]
Are you considering the slowing mechanism @landgreen (the webm and code @kgurchiek made)?

**Comment by landgreen** [comment]
I considered it.
