### ISSUE TITLE
minor bug report: inconsistent wall jump

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#217]
with some jump increases (time dilation, nitinol, etc.) you can sometimes do a mini wall jump. I love this and don't want it to be patched, but its inconsistent and definitely a bug. 
[Screen recording 2024-04-22 5.05.10 PM.webm](https://github.com/landgreen/n-gon/assets/164103476/eed708bf-dff9-4966-a502-53ef6ffc553c)

**Comment by LinuxRocks2000** [comment]
That isn't a wall jump, and you can do it without td/nitinol. It's because hitting vertical walls doesn't immediately arrest velocity on the Y axis, and you can maneuver a little bit while in midair, so you can hit a wall and keep moving up (over the brim), at which point you'll be able to steer onto the block. Occasionally the jump event "bounces" just-in-time, allowing you to take a second jump very quickly after cresting the block.

**Comment by AnnonymousNerd87** [comment]
well I'm use to calling stuff like that a wall jump

**Comment by LinuxRocks2000** [comment]
Wall jumps are when you get an extra hop _while still in contact with the wall_; this is not that.

**Comment by AnnonymousNerd87** [comment]
then what do you call this?
[Screen recording 2024-04-22 5.21.10 PM.webm](https://github.com/landgreen/n-gon/assets/164103476/93623a27-b7e7-4aef-98d0-85f36a313c4a)

**Comment by LinuxRocks2000** [comment]
Oh that's really weird, looks like a real wall-jump bug does in fact exist. My apologies for doubting you.

**Comment by 3xionDev** [comment]
i've known this for a while. i actually use this most runs, namely in `reactor`, because it allows me to grab the rest of the upgrades that get stuck on top of the moving platform. again, this feels like another way to break the game and "trick" the developer, and I personally do not think it should be patched.

**Comment by AnnonymousNerd87** [comment]
more vid just to prove my **_superior intellect_**
[Screen recording 2024-04-23 7.55.58 AM.webm](https://github.com/landgreen/n-gon/assets/164103476/8120275b-cf7f-445a-8465-35e8ec0ba77c)

**Comment by AnnonymousNerd87** [comment]
Yeah I love this bug and don't want it to be patched

seems more consistent with better Fx and jumpForce (move and jump), to test this I'm adding a constant 2x multiplier to both in Dumb n-gon 
https://annonymousnerd87.github.io/

**Comment by AnnonymousNerd87** [comment]
yep, I got time dilation + nitinol and its much more consistent with the 2x bonus
[Screen recording 2024-04-23 8.12.02 AM.webm](https://github.com/landgreen/n-gon/assets/164103476/3980e136-a9f0-4674-9c66-a731a4875ecd)

**Comment by AnnonymousNerd87** [comment]
I got all the move speed bonus tech and I can tell that wall jumping is much more consistent, but because you jump so high its hard to find tall enough walls
[Screen recording 2024-04-23 8.17.24 AM.webm](https://github.com/landgreen/n-gon/assets/164103476/a8c4abc0-6b82-4b21-aa7a-5985d35dbf17)

**Comment by AnnonymousNerd87** [comment]
ok you can also chain jump in corners
[Screen recording 2024-04-23 8.20.04 AM.webm](https://github.com/landgreen/n-gon/assets/164103476/a9672000-786e-42fc-b76b-b36fdd50e93f)

**Comment by landgreen** [comment]
this is a known bug caused by the "on ground" sensor triggering if the player moves fast enough horizontally to get the sensor to touch the wall.  I don't see a reason to fix this since it doesn't really impact gameplay.

**Comment by AnnonymousNerd87** [comment]
actually can you tell me where I can change the size/location of the sensor? I'd like to make it larger in Dumb n-gon.

**Comment by AnnonymousNerd87** [comment]
cool thanks

**Comment by AnnonymousNerd87** [comment]
I buffed it up to (0, 46, 50, 6) so now all you have to do is hold towards a wall and hold w

**Comment by AnnonymousNerd87** [comment]
interesting...

**Comment by landgreen** [comment]
just tried it out.  The legs don't move right, but I could still make it a JUNK tech.

**Comment by AnnonymousNerd87** [comment]
yeah, depends on the parameters. I use (0, 46, 50, 6)

**Comment by landgreen** [comment]
I just added it to the live game with this command

    {
        name: "wall jump",
        description: "jump on walls",
        maxCount: 1,
        count: 0,
        frequency: 0,
        isJunk: true,
        allowed() {
            return !m.isShipMode
        },
        requires: "",
        effect() {
            jumpSensor.vertices[0].x += -22
            jumpSensor.vertices[3].x += -22
            jumpSensor.vertices[1].x += 22
            jumpSensor.vertices[2].x += 22
        },
        remove() { }
    },

**Comment by AnnonymousNerd87** [comment]
cool!

**Comment by AnnonymousNerd87** [comment]
oh btw how do I increase the size/radius of wave packets? I found the code 
`bullet[me] = Bodies.polygon(m.pos.x + 25 * Math.cos(m.angle), m.pos.y + 25 * Math.sin(m.angle), 5, 4, {`
and want to know what number in there is the radius

**Comment by AnnonymousNerd87** [comment]
that code is for the fire transverse section of wave code

**Comment by landgreen** [comment]
{
        name: "amplitude",
        description: "<strong>1.4x</strong> wave <strong class='color-d'>damage</strong><br><strong>1.4x</strong> wave bullet <strong>amplitude</strong>",
        isGunTech: true,
        maxCount: 3,
        count: 0,
        frequency: 2,
        frequencyDefault: 2,
        allowed() {
            return tech.haveGunCheck("wave") || tech.isSoundBotUpgrade
        },
        requires: "wave",
        effect() {
            tech.waveFrequency *= 0.66
            tech.wavePacketDamage *= 1.4
        },
        remove() {
            tech.waveFrequency = 0.2  //adjust this to make the waves much larger
            tech.wavePacketDamage = 1
        }
    },

**Comment by AnnonymousNerd87** [comment]
I mean the size of the individual pellets, not the amplitude. I should have
clarified that. oh and also I broke something in Dumb n-gon and now the
interface is working fine, but when you start the game it crashes and you
are left with a blank screen.
