### ISSUE TITLE
Junk tech idea: Nuclear Gandhi 

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#219]
https://en.wikipedia.org/wiki/Nuclear_Gandhi

ICBMs randomly spawn, with a radioactive effect upon detonation
![Screenshot 2024-04-22 9 50 50 AM](https://github.com/landgreen/n-gon/assets/164103476/8bf6373c-ac4b-4e46-bc3b-088fe75fc05b)

I know its an urban legend but it's funny that he has a 12 for build and use nukes in civ 5

**Comment by 3xionDev** [comment]
while this is funny, it doesn't really follow the scientific-ish naming scheme of most tech, and adding an entirely new projectile type for one JUNKtech is kind of overkill

**Comment by AnnonymousNerd87** [comment]
well all you have to do is add that one radioactive explosion upgrade to ICBMs

**Comment by AnnonymousNerd87** [comment]
and because its a Junk it doesn't have to follow the scientific naming of the other tech

**Comment by AnnonymousNerd87** [comment]
I mean, bounce isn't scientifically named, and its a junk tech. landgreen even considered adding coyote time to the junk tech pool, and that's just a roadrunner reference

**Comment by 3xionDev** [comment]
coyote time has become a technical term in the development community so it counts i believe

**Comment by AnnonymousNerd87** [comment]
well still, its junk for jokes and I don't feel like the name matters too
much if its junk

**Comment by 3xionDev** [comment]
you could be right. this would be an interesting tech. we'll see where our savior landgreen takes this.

**Comment by AnnonymousNerd87** [comment]
I could take it if he doesn't

**Comment by AnnonymousNerd87** [comment]
I mean, all I would have to do is add a very tiny chance each frame to
spawn an ICBM at a random position, then repeat that multiple times
