### ISSUE TITLE
Tech: Advanced Armament Technology

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#222]
kinda like UTF but for guns it would allow you to cycle your gun

**Comment by AnnonymousNerd87** [comment]
you mean UFT right? Unified Field Theory? 

Also it should require integrated armament

**Comment by creator1116** [comment]
yes

**Comment by landgreen** [comment]
you can already cycle guns with the E and Q keys.

**Comment by AnnonymousNerd87** [comment]
I think they mean like changing to any gun, even guns you don't have, but
your guntech randomizes each time.

**Comment by landgreen** [comment]
I think I understand the difference.  I'm saying the ability to get all guns already exists, so this new mechanic makes the normal, much hard, way of getting guns less interesting.
