### ISSUE TITLE
Sorry for the ping, but there's another crash issue with Dumb n-gon

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#225]
This time when the game starts the screen turns gray and all you can see is the player health bar. 
[Screen recording 2024-04-25 9.38.45 PM.webm](https://github.com/landgreen/n-gon/assets/164103476/9ead7a12-927a-4359-a382-929aed35c9f0)
It probably isn't player.js again because the health bar renders correctly, so maybe it's simulation.js or tech.js. I tried to implement the tech suggestion special relativity (the one that gives you energy regen based on speed) and I got some decent stuff done, up until I tried to implement the actual energy regen part. I didn't want it to modify field regen because that might be laggy or inconsistent, so I put it in simulation.js and tried to work it out from there in the ephemera section once every second. I didn't see any syntax errors but I don't know what could cause that crash. The only other idea I have that might cause the crash is that I implemented the tech.js wrong, but I don't see how that would cause a crash. At least I think its a crash, maybe it just doesn't render anything other than the health bar from player.js.

**Comment by AnnonymousNerd87** [comment]
nevermind I fixed it, it was just a syntax error in player.js again

**Comment by creator1116** [comment]
perfect diamagnetism crashes the game

**Comment by creator1116** [comment]
![image](https://github.com/landgreen/n-gon/assets/133981966/46e7affd-05b5-4f28-ace7-6a6ff658770b)

**Comment by AnnonymousNerd87** [comment]
I couldn't find what caused it, I'll add you as a contributor to see if you
can fix it

the temp solution is don't use perfect diamagnetism, it's not that great a
field anyway unless you're doing an ice 9 strat

**Comment by AnnonymousNerd87** [comment]
ok, I invited you, you should be able to check the code in player.js
