### ISSUE TITLE
how to enable testing mode

### ISSUE THREAD

**Issue by corneeme** [landgreen/n-gon#226]
I know there is a way to enable testing mode without getting undefined, I just don't know/remember how, help please?

**Comment by Masbirb** [comment]
You press the experiment button in the bottom right corner

**Comment by Masbirb** [comment]
There is also a command to enable testing but I can't remember it off the top of my head

**Comment by corneeme** [comment]
oh wait i meant testing mode

**Comment by corneeme** [comment]
sry!!

**Comment by AnnonymousNerd87** [comment]
you need to type in a console command, I don't know because my school blocked console commands.

**Comment by Whyisthisnotavalable** [comment]
testing.unlockTesting()

**Comment by kgurchiek** [comment]
actually it's `lore.unlockTesting()`

**Comment by corneeme** [comment]
oh thanks
