### ISSUE TITLE
Hilbert space bug

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#227]
After removing Hilbert space the effect is removed as normal but not the appearance of M

**Comment by AnnonymousNerd87** [comment]
why would anyone remove Hilbert space, you monster

**Comment by Masbirb** [comment]
Brainstorming accident

**Comment by AnnonymousNerd87** [comment]
still

**Comment by 3xionDev** [comment]
that's just a missing line of code, lemme see if I can find it. it should be the line that updates the player's appearance after getting/removing a SKINtech.

**Comment by 3xionDev** [comment]
found it. the `remove() {` function for Hilbert Space is missing the following line:
```
            if (this.count) m.resetSkin();
```
or something similar to this. it definitely involves `m.resetSkin()`, unless `anodize()` uses a different method.

**Comment by landgreen** [comment]
fixed, thanks
