### ISSUE TITLE
Field: Strange Matter Shield

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#228]
negative gravity pushes all surrounding mobs away with huge force

**Comment by 3xionDev** [comment]
this is just standing wave max radius

**Comment by landgreen** [comment]
yeah similar to standing wave

I was planning this though:

field tech: negative mass - quickly pull/teleport in all nearby blocks and then fire them away from player
  how does player triggers effect?
  auto aim 50% of blocks at mobs

**Comment by NV4s** [comment]
This was basically my idea with Gojo's infinity here: [](https://github.com/landgreen/n-gon/issues/216#issue-2257465118)
