### ISSUE TITLE
user-select: none on powerup and experiment choices

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [landgreen/n-gon#229]
# What:

Add `user-select: none;` to the `.card-text` and `#choose-grid` selectors.

# Why:

Whenever I'm in experiment selection and quickly selecting all 9 or 3 of a tech, I always get the tech card text selected, and it's annoying and looks ugly.
![image](https://github.com/landgreen/n-gon/assets/115495738/2ca556f8-4fa7-460e-942e-0953b1490adc)
Also, whenever I'm firing (using the mouse) and I pick up a tech, field, gun, etc., it (most of the time) selects all the text.
![image](https://github.com/landgreen/n-gon/assets/115495738/943788a6-303c-473c-81b7-3f73d041cf03)

Yes, I'm aware of the accessibility concerns when using `user-select: none`, but it doesn't seem like those are taken into account in most other places in n-gon.

**Comment by landgreen** [comment]
I actually added text selection to the cards a while back.  I like being about to select the text for a variety of purposes.

I've never had the issue with the text auto selecting.  Are you maybe on a track pad?

**Comment by landgreen** [comment]
maybe I could run user-select: none for the first few seconds, but then return to normal.
