### ISSUE TITLE
n-gon wiki?

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#235]
I was wondering if there is some sort of official n-gon wiki

**Comment by Masbirb** [comment]
Not official but closest we got

https://ngon.fandom.com/wiki/N-gon_Wiki

**Comment by 3xionDev** [comment]
I don't even remember the last time someone was active on the n-fandom page. There's not necessarily a need for a wiki. The game teaches what you need to know.

**Comment by NV4s** [comment]
I can make a wiki/fandom and keep it updated actively. I just wanna make sure it'll be considered official by landgreen!

**Comment by 3xionDev** [comment]
@NV4s like I said, there's not really a need for an n-gon wiki, which is probably why the other one died. the game's mechanics are made clear when they're introduced, and there's not really much left up to question.

**Comment by NV4s** [comment]
Rip
