### ISSUE TITLE
nerf sneakBoss ai

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#236]
sneakBoss (the big black respawning pentagon thing) is very unfair in my opinion. The ai is very, very aggressive, and it's almost impossible to know if there's one in the level before it attacks you. its movement speed is much faster than the player, and it does a *lot* of damage. there are multiple instances in which my run has been destroyed by a singular sneakBoss that seemingly came out of absolutely nowhere and attacked me at a speed that made it nigh impossible to dodge. it would be more fair if the speed was nerfed, the ai made less aggressive, and maybe a damage reduction.

**Comment by Masbirb** [comment]
I never had problems with sneakboss as it just gets stuck on a corner and just blare which's there for most of the level

**Comment by AnihilationPA** [comment]
Sometimes sneakBoss dies just once and is never seen again with me unless I actively search for it
But never have I had your issue

**Comment by landgreen** [comment]
sneakBoss works the same and normal sneaks.  After they die they teleport to a position in the player's last 10 seconds of history and wait until they see you.

**Comment by landgreen** [comment]
I don't see a need to nerf sneakBoss right now, It might a quirk of your play style.  I find high dps is the best defense for sneakBoss

**Comment by myschoolisass** [comment]
sneakboss usually just appears directly on top of me and instakills, but its kinda a skill issue because it only happens when you aren't moving
