### ISSUE TITLE
Are there unique Seeds?

### ISSUE THREAD

**Issue by NV4s** [landgreen/n-gon#237]
Are there any seeds that are unique or special? (The area where you type in a randomization seed to spawn a level setup)

**Comment by 3xionDev** [comment]
not really that I know of. it just randomizes the level order.

**Comment by landgreen** [comment]
it randomizes level order, tech, gun, field options, and mob types, and the horizontal flip of the levels.

**Comment by landgreen** [comment]
but I agree the seeds aren't that interesting.
