### ISSUE TITLE
Enemy Names

### ISSUE THREAD

**Issue by NV4s** [landgreen/n-gon#239]
What are the official names of all bosses and regular mobs? (I refer to them as their original shape)

**Comment by Masbirb** [comment]
Mob.js I think

**Comment by Whyisthisnotavalable** [comment]
`
    nonCollideBossList: ["cellBossCulture", "bomberBoss", "powerUpBoss", "growBossCulture"],
    // other bosses: suckerBoss, laserBoss, tetherBoss, bounceBoss, sprayBoss, mineBoss, hopMotherBoss    //these need a particular level to work so they are not included in the random pool
    randomBossList: [
        "orbitalBoss", "historyBoss", "shooterBoss", "cellBossCulture", "bomberBoss", "spiderBoss", "launcherBoss", "laserTargetingBoss",
        "powerUpBoss", "powerUpBossBaby", "streamBoss", "pulsarBoss", "spawnerBossCulture", "grenadierBoss", "growBossCulture", "blinkBoss",
        "snakeSpitBoss", "laserBombingBoss", "blockBoss", "revolutionBoss", "slashBoss", "shieldingBoss",
        "timeSkipBoss", "dragonFlyBoss", "beetleBoss", "sneakBoss", "mantisBoss",
        "laserLayerBoss"
    ],
    fullPickList: [
        "slasher", "slasher", "slasher2", "slasher3",
        "hopper", "hopper", "hopMother", "hopMother",
        "stabber", "stabber", "stabber",
        "springer", "springer", "springer",
        "stinger", "stinger", "stinger",
        "flutter", "flutter",
        "striker", "striker",
        "shooter", "shooter",
        "grenadier", "grenadier",
        "pulsar", "pulsar",
        "laser", "laser",
        "laserLayer", "laserLayer",
        "sneaker", "launcher", "launcherOne", "exploder", "sucker", "sniper", "spinner", "grower", "beamer", "spawner", "ghoster", "focuser"
    ],
    
`

**Comment by 3xionDev** [comment]
https://www.figma.com/file/JlSRzTlmrUjXDNX0rM5iJm/n-gon-mob-evolutionary-tree?type=design&node-id=0%3A1&mode=design&t=nDgNwaHtP9K8LvKz-1

This is a figma sheet of the n-gon evolutionary tree that me and a couple people are working on. It is incomplete, but it includes images of the bosses and mobs, along with their in-game names.

**Comment by landgreen** [comment]
HA!
I feel like the starter mob should be the common ancestor of all mobs.

**Comment by NV4s** [comment]
@Whyisthisnotavalable Could I get pictures of each of them (later)?

**Comment by NV4s** [comment]
Specifically the limited level and new ones

**Comment by landgreen** [comment]
replace starter with the mob name in the console to see them
spawn.starter(level.exit.x, level.exit.y)

**Comment by NV4s** [comment]
ok

**Comment by NV4s** [comment]
Don't close this as it could be useful for other people!
