### ISSUE TITLE
Final boss is "op"

### ISSUE THREAD

**Issue by YeetDragon23** [landgreen/n-gon#24]
My classmate said "why is the final boss on steroids"

**Comment by YeetDragon23** [comment]
please make the final boss easier

**Comment by Whyisthisnotavalable** [comment]
Back in the day, u could one shot final boss

**Comment by YeetDragon23** [comment]
> Back in the day, u could one shot final boss

With a harpoon, that is. I don't really know much about it anymore because I haven't played the game with final boss for a while.

**Comment by Whyisthisnotavalable** [comment]
the final boss is op on why mode, but still beatable because I've beat it before on why mode

**Comment by landgreen** [comment]
the final boss is a damage check
reactor bosses are survival checks
reservoir is a movement check

I balance the game around hard mode and normal mode.
Why mode is mostly there to not be beaten.
