### ISSUE TITLE
Healing

### ISSUE THREAD

**Issue by UnknownContinuum** [landgreen/n-gon#241]
Whenever you have negative mass or standing wave (i think) and use heal orbs at max health with quenching, you fly up in whatever direction opposite of where you are aiming

**Comment by 3xionDev** [comment]
very situational, probably won't be fixed

**Comment by myschoolisass** [comment]
this is a feature (getting moved in opposite direction of what M is obtaining powerups at)

**Comment by 3xionDev** [comment]
oh yeah, that's right, this is hard coded in. it def won't be fixed
