### ISSUE TITLE
Lag Fix #1

### ISSUE THREAD

**Issue by TheLegendary1248** [landgreen/n-gon#245]
_this is likely the first of many ill contribute_

The discord server has lately had quite a few messages about insane lag once you start become a literal deity. This is expected.
This is one fix to combat that: https://github.com/TheLegendary1248/n-gon/tree/lagfix
- [**Certain powerups are mergeable**](https://github.com/TheLegendary1248/n-gon/blob/lagfix/js/engine.js#L284)
  - Many powerup spawning techs, `interest` more infamously, easily causes the game to slow down as you reach into the thousands of powerups being in the world at once
- [**`fallCheck`ed powerups are spaced from each other**](https://github.com/TheLegendary1248/n-gon/blob/lagfix/js/engine.js#L1087)
  - this was causing about O(n^2) collisions to be calculated the following frame everytime it was called
- [**Unduplicated powerups are internally a smaller shape; octagons in my fork**]()
  - Matter.js does not have separate logic for cirlcles / circle primitives. It spends a good chunk of time on `Matter.Collision._overlapAxes()` as a result. [I found this through Firefox's profiler](https://share.firefox.dev/3QnKnTe)

It isn't complete, but it's a draft anyways
Was looking forward to hear thoughts on if this is an acceptable change 

Also here's something to read on how to use git so you don't lose your local changes again :)  https://think-like-a-git.net/

**Comment by landgreen** [comment]
I don't think lag is an issue for normal game play.

**Comment by AnnonymousNerd87** [comment]
actually with interest and supply chain dropping potentially hundreds of power ups it **can** be a problem for min/maxers like myself, but this is more of a problem with interest than big O problems.
