### ISSUE TITLE
Entanglement Problem?

### ISSUE THREAD

**Issue by RubyTheDog190** [landgreen/n-gon#248]
Hey, I was playing using the downloaded files and I realize that the entanglement powerup is kind of buggy? sometimes the moment I pick it up it freezes the screen but still shows I'm playing. 
![image](https://github.com/landgreen/n-gon/assets/145081829/d871c427-68e5-4372-99a6-778df747167c)

**Comment by 3xionDev** [comment]
Download the newest patch. This bug was fixed.
