### ISSUE TITLE
Newtons 1st Law.webp not showing up in web page, but showing up everywhere else

### ISSUE THREAD

**Issue by landgreen** [landgreen/n-gon#253]
I can't figure this one out.

Newtons 1st Law.webp the image exists in the landgreen github repo 
https://github.com/landgreen/landgreen.github.io/blob/master/n-gon/img/Newtons%201st%20Law.webp
I can also see the image on my local version version of n-gon, but it's missing when I goto the web page.

<img width="373" alt="Screenshot 2024-05-11 at 3 04 58 PM" src="https://github.com/landgreen/n-gon/assets/21106570/720dd050-e925-4e2a-a19d-3cfb0a66d5e0">
<img width="373" alt="Screenshot 2024-05-11 at 3 05 12 PM" src="https://github.com/landgreen/n-gon/assets/21106570/5acd264b-93d1-4078-9626-0c0f19858481">

**Comment by 3xionDev** [comment]
I think that's just from the GitHub pages server failing to fetch the image. I don't know why it wouldn't show the unavailable image icon though. it's possible that it's outscaling the image out of the container and that's hiding the icon, but that's a bit far-fetched. either way, this has happened to me before, and it's usually something that just resolves itself, at least for me.

**Comment by 3xionDev** [comment]
that would also explain why it's working on your local copy, since it's not using github cdn to fetch the images but instead fetching them directly from the file.

**Comment by kgurchiek** [comment]
every time I play I always notice it logs that it failed to fetch the newton's 1st law image, maybe it's a github bug?

**Comment by creator1116** [comment]
have you tried downloading the zip and playing from a local file

**Comment by AnnonymousNerd87** [comment]
tons of images don't load for me, but I have a firewall which blocks the dictionary of obscure sorrows, so its prob. on my end for those

**Comment by 3xionDev** [comment]
yes, I believe it's a github CDN issue

**Comment by AnnonymousNerd87** [comment]
maybe it's something dumb like a syntax error, I don't know how common those are for js bc I'm not as experienced in js as c but in unity I was so confused with my syntax errors in unity. not saying I think you make syntax errors very often, your code is very neat and tidy, landgreen!

**Comment by kgurchiek** [comment]
Yeah, that means it's an issue on Github's end, there's nothing wrong with the code

**Comment by 3xionDev** [comment]
shall we close?

**Comment by kgurchiek** [comment]
@landgreen have you tried deleting it and uploading again?

**Comment by landgreen** [comment]
Deleting it and uploading didn't work.  My current theory is that the image had a flaw that upset the server.  Some images are just evil.  So I plan to make a new image and upload it.

**Comment by AnnonymousNerd87** [comment]
"Some images are just evil" XD

**Comment by landgreen** [comment]
well I uploaded a completely new image and the issue persists.  So, my "evil images" theory is probably wrong.  I'll try renaming the tech next.

update tech rename worked
