### ISSUE TITLE
paradigm shift 

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#255]
I think that paradigm shift should be able to remove field and gun in addition to tech

**Comment by Masbirb** [comment]
The ability to remove fields would be so overpowered that I think it would break the entire game
There is a reason UFT doesn't give you field emitter anymore.
Paradigm shift was already among the best techs so it doesn't need another buff it may even need a nerf

**Comment by creator1116** [comment]
ok. maybe not fields. but possibly guns should be able to be removed.

**Comment by landgreen** [comment]
Paradigm shift feels very strong, but It's only really good when you have the breathing room to invest a few tech to later remove.  On why mode you have to ride the damage curve to survive.
