### ISSUE TITLE
Is it possible to get more and periodic "classic n-gon" levels?

### ISSUE THREAD

**Issue by Yaron-Ha** [landgreen/n-gon#256]
This is crucial for speedrunning, as the game still undergoes drastic changes.
Unfortunately the last classic level is over 2 years old.
Is it possible to maybe replace "classic n-gon" with "n-gon editions" where every year is considered its own edition?

Thank you.

**Comment by kgurchiek** [comment]
If you need to play old versions, you can select any old version by looking in the past commits. I also made a website to play past versions easier here: https://cornbread2100.com/n-gon-loader

**Comment by landgreen** [comment]
that loader is pretty cool, and it looks like it solves this issue.
