### ISSUE TITLE
Old saves do not work

### ISSUE THREAD

**Issue by 136166** [landgreen/n-gon#257]
You know the 'copy build URL'?
Now the old ones do not work. why?

**Comment by 3xionDev** [comment]
I'd assume it's because new upgrades have been added and some have been removed, so some old builds may be broken.

**Comment by 136166** [comment]
That should be fixed or something, because it is kind of sad and I had some good builds...

**Comment by landgreen** [comment]
load them here
https://cornbread2100.com/n-gon-loader

**Comment by landgreen** [comment]
Never mind, cornbread's loader doesn't seem to work for old saves.

Sadly my default position is to ignore my build save system.
It just has too many bugs I can't fix and it doesn't seem that interesting.
I'll leave it until it beaks, and after that I'll problem remove it.
I just have to code the stuff that keeps me interested.

**Comment by kgurchiek** [comment]
Oh I didn't realize that didn't work, I'll go add support for it

**Comment by kgurchiek** [comment]
build urls should now work

**Comment by kgurchiek** [comment]
What issues were you having with build urls in the actual game? I've never experienced any problems with it.
