### ISSUE TITLE
URL in "About" section of github page has an incorrect link

### ISSUE THREAD

**Issue by AverseABFun** [landgreen/n-gon#258]
![image](https://github.com/landgreen/n-gon/assets/81586710/a15fd1fc-739d-4b83-834d-b52fb3e5c486)

This URL should be https://landgreen.github.io/n-gon.

**Comment by landgreen** [comment]
I think you are on an old version this was fixed already.

**Comment by kgurchiek** [comment]
it was fixed in the readme but not the about section of the repo

**Comment by AverseABFun** [comment]
Yeah, @landgreen i mean in the about section of the repo. i know it's been fixed in the readme.

**Comment by landgreen** [comment]
oh ok thanks
