### ISSUE TITLE
Could there be a possible multiplayer function?

### ISSUE THREAD

**Issue by CycloKid** [landgreen/n-gon#26]
I think that maybe it could work, maybe for LAN players, because I'd want to be able to go through the game possibly allowing for more fun as well.
Some of my concepts of this could be:
- Double/Increased enemies
- More game mechanics
- 2 player co-op stories
- 2 player maps? (like fire boy and water girl)
- GAMEMODES?
- And Servers and Plugins/Mods!

**Comment by Shkeffy** [comment]
Mate.. this would take so long...

**Comment by landgreen** [comment]
I think multiplayer would be a full rewrite, maybe with a different physics engine as well.
