### ISSUE TITLE
Tech: Positive Flux Saturation

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#260]
Perfect diamagnetism's electromagnetic flux is increased to core saturation, greatly improving performance but reducing field magnitude
+30% deflection energy efficiency
+17% energy generation
Perfect diamagnetism's shield size is reduced by a factor of 2/3

**Comment by TNTiger17** [comment]
Doesn't perfect diamagnetism not drain energy when deflecting, therefore energy deflection doesn't matter for it?

**Comment by AnnonymousNerd87** [comment]
3xion have you never used perfect diamagnetism before?
