### ISSUE TITLE
Healing on subway sometimes sets health to 100

### ISSUE THREAD

**Issue by RustyBust** [landgreen/n-gon#261]
Sometimes, on the `subway` level (12 subway), my health randomly (I believe upon using the heal power-ups spawned at the beginning of the level, when already at full health?) will change to 10000/10000, allowing me to beat it and `final` quite easily.
I have no idea why this might've happened, but I have a guess that it might be related to a line of code accidentally setting the `m.health` and/or `m.maxHealth` values to equal `100` somewhere (which would be 10000%). 
Also, the health bar does update on-screen when this happens.

**Comment by AnnonymousNerd87** [comment]
I've never seen this happen before, can you provide screenshots of your build in the pause menu?

**Comment by RustyBust** [comment]
After commenting, I beat the game on that run and closed the tab. I'll try to reproduce this later today or tomorrow.

**Comment by AnnonymousNerd87** [comment]
I would try to replicate it if I wasn't focused on my nuclear science
project

**Comment by landgreen** [comment]
I didn't find anything that could cause that except a couple of unprotected lines of code in a community map.

I added this to those situations.
                        if (m.health > m.maxHealth) m.health = m.maxHealth;

**Comment by kgurchiek** [comment]
> if (m.health > m.maxHealth) m.health = m.maxHealth;
I think they said the bug affected max health as well, so that might not work

**Comment by landgreen** [comment]
I checked for maxHealth and health.

**Comment by RustyBust** [comment]
Could it be possible that I was running an old commit?

**Comment by landgreen** [comment]
maybe, but there was a potential issue for a community map.
