### ISSUE TITLE
Interest & Frequency cause the game to be unplayable

### ISSUE THREAD

**Issue by Invincible-Atlas** [landgreen/n-gon#265]
If the player has both the Wave Gun, Frequency (which gives the Wave Gun unlimited ammo, while reducing it's damage by 25%), and Interest (which spawns 6% of the players Research, Ammo, Coupling, and Health every level), upon entering a new level infinite Ammo will be spawned over time, which, despite having some practical applications, causes extreme performance issues, and makes the game virtually unplayable.

**Comment by landgreen** [comment]
You are on an older version of n-gon.  This was fixed a while back.

**Comment by Invincible-Atlas** [comment]
oh, ok. Sorry.
