### ISSUE TITLE
SKINtech: Heavy-ion fusion

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#266]
+150 max energy
+50% energy generation
-10% movement speed
-25% overall energy efficiency
add a cherenkov-esque glow to `m` to indicate fusion energy

**Comment by AnnonymousNerd87** [comment]
would be op with molecular assembler, time dilation, electronigravity,
standing wave

**Comment by AnnonymousNerd87** [comment]
see my closed issue on molecular assembler

**Comment by AnnonymousNerd87** [comment]
I like the idea, but it needs a bigger downside, preferably one big downside rather than multiple small ones

**Comment by AnnonymousNerd87** [comment]
I am doing a laser run with that tech which makes laser only turn off when you have no energy, and this tech would ruin it bc you would almost never run out with the 150 bonus max and 50% bonus regen

**Comment by AnnonymousNerd87** [comment]
the reduced efficiency is canceled out by the bonus regen, so the only downside is 10% less move speed, which is annoying but mainly for platforming maps or long jumps

**Comment by AnnonymousNerd87** [comment]
maybe remove both downsides and instead you take damage over time based on energy regen, maybe 1/10 energy you regenerate damages you 1 hp bc you don't have enough heat shielding to protect yourself from all the waste heat you are making.

**Comment by AnnonymousNerd87** [comment]
all that heating and compression gives off a decent amount of waste, about 70%, so having that reflected as damage would be in universe and awesome

**Comment by Masbirb** [comment]
The move speed may be a problem as you may not be able to do some jumps in maps so try a different downside

**Comment by AnnonymousNerd87** [comment]
that's what I said

**Comment by AnnonymousNerd87** [comment]
I feel like life drain on energy regen is cool, see my prev. comment

**Comment by Masbirb** [comment]
I would prefer if it increased move speed but you need energy to move and energy regen is decreased by your momentum.
