### ISSUE TITLE
yeah you should nerf supply chain

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#267]
just did a run on the new second difficulty setting, feels good, got lots of guns and 6 supply chain and died in subway to the lag of tens of thousands of ammo ups. I feel like instead of double ammo **per gun** it should be just triple ammo for all your guns, bc that's more reasonable than getting 5000 mines ammo on the conservative gun alongside over 200000 shotgun ammo

**Comment by AnnonymousNerd87** [comment]
there was an issue a while back about this

**Comment by landgreen** [comment]
You took supply chain 6 times?  What did you expect after supply chain #5?

**Comment by AnnonymousNerd87** [comment]
well, mine starts with like 15 ammo, so 15 * 2^6 = 960, not over 5000

**Comment by AnnonymousNerd87** [comment]
the ammo ups from the other guns were much higher, causing the ammo to
explode

**Comment by AnnonymousNerd87** [comment]
metaphorically of course

**Comment by landgreen** [comment]
I bet it's not clear to everyone, but it's the total ammo from all your guns.  I updated the text to make it more obvious.

**Comment by AnnonymousNerd87** [comment]
cool thanks

**Comment by landgreen** [comment]
I'm also adding this to next patch:

> long ongoing power up spawns, like from interest or supply chain
>   will pause new spawns until total power ups are below 200 to reduce lag
>   will stop spawning if you take damage
> 

this should add a tiny bit of skill to crazy long power up spawns, and provide a release valve for when lag takes over.

**Comment by AnnonymousNerd87** [comment]
wow, that's awesome. I think another problem is that if you hold space you
can absorb them faster than they come out, but it means that you have to
hold space for like 10 mins at 6 supply chain or many levels of interest on
ammo or coupling. This solution is great but not quite the problem I had.
Still genius though!
