### ISSUE TITLE
New gun concept: Magnetorheological ferrofluid, or MRFF

### ISSUE THREAD

**Issue by 3xionDev** [landgreen/n-gon#268]
An interesting GUNtech idea, though I suppose it wouldn't really be a range weapon in the sense of a projectile.

See, there's something called magnetorheological fluids, which are basically liquids that become extremely viscous or even solid in the presence of a magnetic field. The only problem is that they don't form spikes inline with the field lines like ferrofluids do, which would be cool as hell. So, combine the two ideas, and you get something that could very conceivably be a sci-fi weapon.

Basically, just have `m` shoot out a jet of black fluid to the cursor, which stays fixed to `m` housing. The fluid can be flung around like a flail to damage enemies, but it can also be solidified when right mouse is pressed, causing most of the fluid to be drawn to the tip, making the line of liquid that attaches the fluid to `m` very thin and causing the fluid at the cursor to become sharp, spiky and rigid.

I'm bad at explaining concepts, so I'll draw up something and post it below, but I feel like this could be a really cool gun to play with.

**Comment by 3xionDev** [comment]
![mrff-liquid](https://github.com/landgreen/n-gon/assets/88562716/2eeeb91a-1756-4aab-8aa6-87603bf145bf)
![Page 1](https://github.com/landgreen/n-gon/assets/88562716/9fc3b136-1b1c-4a3e-8b5b-0dafd9274071)
when solidified, the line of fluid connecting the "spike ball" to `m` does greatly reduced damage than it would when not solidified

**Comment by AnnonymousNerd87** [comment]
this would be a full on gun, not just guntech

**Comment by 3xionDev** [comment]
wait yeah thats what i meant

**Comment by AnnonymousNerd87** [comment]
aw man, I missed my chance to "eeerm akutchuly..."

**Comment by AnnonymousNerd87** [comment]
_**intentionally misspelled**_

**Comment by AnnonymousNerd87** [comment]
I asked an ai to draw a nerdface emoji saying "eeerm akutchuly..." and it drew this
![Screenshot 2024-06-04 7 44 54 AM](https://github.com/landgreen/n-gon/assets/164103476/13a6bd01-b94c-4d32-913c-eddc5a9e34a8)

**Comment by AnnonymousNerd87** [comment]
wait nevmind it got better

**Comment by AnnonymousNerd87** [comment]
![Screenshot 2024-06-04 7 47 06 AM](https://github.com/landgreen/n-gon/assets/164103476/c9323855-7b12-40ac-94b5-02a7fa81f08b)

**Comment by AnnonymousNerd87** [comment]
[](https://perchance.org/ai-icon-generator)

**Comment by AnnonymousNerd87** [comment]
[it's called perchance.org](https://perchance.org/ai-icon-generator)

**Comment by 3xionDev** [comment]
there would be no range cap to how long it can stretch, but the farther it stretches the thinner it gets and the less damage it does, to discourage killing things from across the map

**Comment by AnnonymousNerd87** [comment]
"we seem to have diverged from the topic" XD

**Comment by 3xionDev** [comment]
I mean, we somehow devolved from a new gun to ai-generated nerd emojis, so I'd say that's somewhat of a divergence lmao

**Comment by 3xionDev** [comment]
the only problem is that I'm not sure how well fluid physics would work using matter.js without writing a fluid engine manually just for n-gon

**Comment by 3xionDev** [comment]
@landgreen do you think you'd be able to integrate a fluid-like physics system for this? i'd be willing to help.

**Comment by AnnonymousNerd87** [comment]
use langton's ant

**Comment by AnnonymousNerd87** [comment]
it can simulate fluids if you code it right

**Comment by 3xionDev** [comment]
that would be hilarious, but langton's ant would probably be one of the least efficient algorithms for fluid simulation, at least for a game like n-gon

**Comment by AnnonymousNerd87** [comment]
yeah, but it has been done for both fluid and gas simulation on a large
scale. I mean, in the absolute gem Noita, every single pixel is simulated,
including gasses, and through some dark witchcraft, I have never once
gotten intense lag, even when using tens of thousands of projectiles and
particles. Noita doesn't use langton's ant, but it could.

**Comment by 3xionDev** [comment]
we wouldn't be truly simulating fluid, which is why I said "fluid-like." what I have in mind is more of a glorified softbody structure. it doesn't flow, but it sort of splatters and squishes when it interacts with a rigidbody and stretches thin when it gets longer. and then, of course, it turns into a rigidbody when it solidifies.

**Comment by AnnonymousNerd87** [comment]
maybe use a bunch of softbodies with drone-like ai, drones "splatter" when
they hit surfaces

**Comment by AnnonymousNerd87** [comment]
they would be connected and filled with black

**Comment by 3xionDev** [comment]
if they were all softbodies, the impact would be absorbed and they wouldn't splatter. plus, drones splatter really violently when they crash. this would just spray off a tiny bit of fluid and bend the stream around the object, sort of like multi-articulated appendages like tentacles do.

**Comment by AnnonymousNerd87** [comment]
then softbodies mixed with drones with trails, softbodies for the main
body, drones for the tiny bit of fluid

**Comment by 3xionDev** [comment]
and that is too overly complicated and not modular enough. this thing needs to be able to move quickly and also have some wobble to it. literally all it needs to be is a softbody tentacle. no need for creating different drone variants, mini-softbodies, etc just for this

**Comment by AnnonymousNerd87** [comment]
well you said softbodies wouldn't work

**Comment by 3xionDev** [comment]
I said a group of softbodies wouldn't work because the combined number of drones would distribute the impact across more area and mute the splash. A single, large softbody would probably work because it's affecting the whole structure at once.

**Comment by AnnonymousNerd87** [comment]
*ich bin kruger als du. *You don't know how soft bodies work, a softbody
*cannot* be singular, because a softbody is made of many rigidbodies which
affect each other to varying degrees, some bending more than others, all
influencing each other.

**Comment by AnnonymousNerd87** [comment]
I feel like this would be energy, for the magnetic fields, because you
don't have to keep pumping out more fluid, you just need to control the
field

**Comment by AnnonymousNerd87** [comment]
sounds good to me, what does exion think

**Comment by 3xionDev** [comment]
> a softbody is made of many rigidbodies which affect each other to varying degrees, some bending more than others, all influencing each other.

I know this, I'm saying that we can't have a big mass of softbodies comprising the final structure, it would be ideal to have a singular softbody comprising the final thing. I refer to softbody as a singular entity because it's simply easier to write "single softbody" than to say "multiple rigid-and-softbody structures combined into the final shape"

**Comment by 3xionDev** [comment]
> I feel like this would be energy, for the magnetic fields, because you don't have to keep pumping out more fluid, you just need to control the field
Actually, I was thinking both. Ammo would not specifically be needed to use the gun, and it would mainly be energy consumed to use it, but ammo would increase the amount of fluid *available to use* and decrease the stream's damage dropoff with distance, essentially extending the fluid's range. to prevent this from getting out of hand we'd either have to add an ammo cap or add a range cap.

**Comment by 3xionDev** [comment]
the whole concept is that ammo would not be *required* to use the gun, and that the gun would have a moderate damage range without any ammo, just that ammo allows more fluid to be supplied, allowing the fluid to be thicker over longer distances

**Comment by AnnonymousNerd87** [comment]
Maybe just make it like harpoon, with bonuses for ammo but the main
requirement is energy

**Comment by AnnonymousNerd87** [comment]
it uses ammo but when you stop the fluid returns to you and refunds it

**Comment by kgurchiek** [comment]
That gun sounds really fun and cool, if it isn't added I might make a mod for it

**Comment by 3xionDev** [comment]
> That gun sounds really fun and cool, if it isn't added I might make a mod for it

huge w

**Comment by AnnonymousNerd87** [comment]
sounds great, foam needs more giant death tentacles to spice things up

**Comment by AnnonymousNerd87** [comment]
(exion this would be a good time to close this issue)

**Comment by kgurchiek** [comment]
I'd wait for landgreen to respond first

**Comment by Masbirb** [comment]
We could make this be part of the only current death tentacles, extruder. Energy that you gain over max results in a ball forming around you then when you use your field you either fire a ton of extruder tentacles, a large extruder tentacle, or a extruder tentacle that randomly forks based on which one was easiest to code

**Comment by AnnonymousNerd87** [comment]
I'm not going to speak for him, but landgreen works tons, both on teaching
and this indie side project, so these giant tentacle monsters should be
confined to mods for now.

**Comment by 3xionDev** [comment]
> maybe this could be a foam upgrade

this would not do well as a foam upgrade as it changes the entire gun.

**Comment by 3xionDev** [comment]
> We could make this be part of the only current death tentacles, extruder. Energy that you gain over max results in a ball forming around you then when you use your field you either fire a ton of extruder tentacles, a large extruder tentacle, or a extruder tentacle that randomly forks based on which one was easiest to code

again, it changes the entire gun as an extruder upgrade.

**Comment by 3xionDev** [comment]
> I'm not going to speak for him, but landgreen works tons, both on teaching and this indie side project, so these giant tentacle monsters should be confined to mods for now.

bro casually just appeared in the community and started talking like he's a developer of the game, while you're not. this is a relatively simple concept to implement, even as a prototype feature. a feature such as this, which everybody seems to like, would not be done justice in a mod.

**Comment by AnnonymousNerd87** [comment]
I said I'm not going to speak for him

**Comment by 3xionDev** [comment]
> I said I'm not going to speak for him

"These giant tentacle monsters should stay in the mods because landgreen works a ton" after landgreen just completely reworked the game's difficulty system on a whim suggestion

**Comment by AnnonymousNerd87** [comment]
well, also n-gon has to be balanced, and adding a new gun or field is a lot
of balancing to do. the last time that happened (grappling hook) it took
about 3 updates as the sole focus, and given that it's taking about 40
comments to flesh it out it would be a pain to teach newer players.

**Comment by 3xionDev** [comment]
grappling hook took three updates because it was a rework of how the gun worked, to repurpose it into a field. new tech had to be created, etc etc, just so it could be considered a usable field. a new gun like this, however, really just balances itself, since damage drops off with distance, and the higher-damaging solidified version is confined to a slower-moving, small ball.

**Comment by 3xionDev** [comment]
and it's not taken 40 comments. lots of these are people arguing whether it should be in the game, or completely irrelevant things.

**Comment by Masbirb** [comment]
Your idea is very cool but sounds hard to code

**Comment by kgurchiek** [comment]
Since this is more complex than other guns are without any tech, this kinda feels like more of a late-game thing. Maybe it could have a really low chance to spawn earlier on, but it gets more common each level.

**Comment by Whyisthisnotavalable** [comment]
Literally extruder
