### ISSUE TITLE
issue; tech stealer boss ruins builds

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#269]
I just had a run on difficulty 3, pretty decent, mass production gave me lots of mine ammo, got mass energy, but then the big tech stealer (the one which can phase through walls) came and removed mass energy, causing me to die in 3 hits because mass energy was my main survivability tech. this has been mentioned in the past, but I feel like n-gon is best when you die to a large number of small enemies, or to chip damage from a larger enemy, not getting combo'd by something that is stealing your build.

**Comment by kgurchiek** [comment]
powerupBoss is pretty easy to cheese, you can just jump over it and deflect it in an emergency
