### ISSUE TITLE
Game "window" freezes, but not anything else for some reason

### ISSUE THREAD

**Issue by CycloKid** [landgreen/n-gon#27]
Sometimes when playing the game, the game "window" pauses/freezes up.
But the thing is, NOTHING else gets frozen? Maybe something to do with an error/bug that makes the window freeze, but not the gameplay.
↓ Video here ↓

https://user-images.githubusercontent.com/63879422/168129028-91874d50-5a8f-4542-8613-0674390e5bbf.mp4

**Comment by Whyisthisnotavalable** [comment]
neutron bomb breaks the game

**Comment by landgreen** [comment]
thanks for the bug report, I'm not sure what went wrong.
I wonder if time dilation got 'stuck'
if it happens again the error reports in the console would help.
