### ISSUE TITLE
ying yang vision thing remains even in other levels

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#270]
![image](https://github.com/landgreen/n-gon/assets/133981966/06e95fa4-7f1b-4385-b824-2d40c2928ecb)

**Comment by AnnonymousNerd87** [comment]
is ying yang a community map?

**Comment by AnnonymousNerd87** [comment]
yeah I haven't done those in a while

**Comment by landgreen** [comment]
This doesn't look reproducible.  If anyone finds a recipe to get this to occur let me know.

**Comment by Whyisthisnotavalable** [comment]
This happens because both unchartedcave and shipwreck don't have level.custom so it uses the level.custom from the last level.

**Comment by landgreen** [comment]
ah, that makes sense I'll fix it then.  thanks
