### ISSUE TITLE
Difficulty slider is inverted on Firefox

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#271]
![image](https://github.com/landgreen/n-gon/assets/90143063/79b91b10-b976-4eec-9caf-f773a4b2359a)

**Comment by AnnonymousNerd87** [comment]
I am on a chromebook and I thought that was how it was supposed to be

**Comment by AnnonymousNerd87** [comment]
But yeah it affects me too

**Comment by landgreen** [comment]
firefox on my mac looks correct

<img width="192" alt="Screenshot 2024-06-05 at 7 08 11 PM" src="https://github.com/landgreen/n-gon/assets/21106570/c950356d-e5e2-4ba5-97dc-92cb4e72e38a">

**Comment by kgurchiek** [comment]
I was on Debian, and I just reinstalled, so Firefox should be up to date. Chrome worked correctly on the same device.

**Comment by landgreen** [comment]
Well, I can put in a few redundant ways to tell the code to orient it the right way.   I can't test it, but maybe it will fix next patch.

**Comment by kgurchiek** [comment]
if you send the code here I can test it for you

**Comment by landgreen** [comment]
maybe this last line in the CSS
`#difficulty-slider {
    margin-top: 2.3rem;
    height: 26.3rem;
    width: 2rem;
    writing-mode: vertical-lr;
    direction: ltr;
}`


also maybe this in the powerup.js
               <input type="range" id="difficulty-slider" name="temp" type="range" step="1" value="1" min="1" max="6" list="values" dir="ltr"/>

I kinda doubt it works thouigh

**Comment by AnnonymousNerd87** [comment]
I am on chrome os, here's a screenshot
[image: Screenshot 2024-06-06 9.29.01 AM.png]

**Comment by Whyisthisnotavalable** [comment]
<img width="387" alt="Screen Shot 2024-06-18 at 4 14 02 PM" src="https://github.com/landgreen/n-gon/assets/77077277/4faedebb-2d36-446c-87f0-923a46d4c094">

is this intended?

**Comment by landgreen** [comment]
no, what OS and browser are you on?

**Comment by Whyisthisnotavalable** [comment]
macbook, brave browser

**Comment by landgreen** [comment]
does it look normal on other browsers by any chance?  That would help narrow the issue down.

**Comment by Whyisthisnotavalable** [comment]
It looks the same on other browsers.

**Comment by landgreen** [comment]
huh weird.  oh well it's jut visual.  I don't use the slider since you can click on the difficulties.
