### ISSUE TITLE
issue; ejecting paradigm shift

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#275]
I just did a laser run, got strange loop, got paradigm shift, miss clicked and instead of ejecting strange loop I ejected paradigm shift and ruined my run. Paradigm shift shouldn't be allowed to eject paradigm shift, why have I never thought of this

**Comment by landgreen** [comment]
HA, I'm assuming this is sarcastic.  Sorry!

**Comment by AnnonymousNerd87** [comment]
kindof, but it is very annoying
