### ISSUE TITLE
Bye for a while

### ISSUE THREAD

**Issue by AnnonymousNerd87** [landgreen/n-gon#276]
I will be graduating soon, and on Monday I will have to turn in my Chromebook, so I will be inactive for at least three months. 

This community has been the most wholesome I have been a part of in a while, and I love how this is a space where I am not afraid to be a true nerd. At my school I am known by many nicknames, Mr. Monologue, Dictionary.com, Encyclopedia Britannica, Encyclopedia Germanica, Fun Fact Felix, and just yapper. In this place I can be AnnonymousNerd87, defined only as who I want to be. In this place, I am a nerd who goes as far as to use the nerdface emoji gif as my profile picture! 

In my school, I am the person people go to for definitions, or fun facts, but am otherwise avoided. Here, I am a member of the community, and all previous assumptions are dispelled, leaving me as who I am. 

Landgreen has made a true indie gem, and this community has turned it into something more! 

Thank you all for building this wonderful community!

-Felix

**Comment by landgreen** [comment]
I'm sure you already know this but worrying about being a nerd doesn't happen nearly as much after high school.  Generally it's seen as a good thing.

See ya around!

**Comment by AnnonymousNerd87** [comment]
🤓

**Comment by AnnonymousNerd87** [comment]
so long, and thanks for all the fish!

**Comment by creator1116** [comment]
bye!

**Comment by kgurchiek** [comment]
Bye!

**Comment by thatlittlefrog** [comment]
byee!
