### ISSUE TITLE
[ SUGGESTION ] PWA?

### ISSUE THREAD

**Issue by Shkeffy** [landgreen/n-gon#28]
Hello, this is a GREAT game!!! I was wondering if you could somehow make it into a PWA so that it can be played offline? I think that would be awesome. Also, have you considered making more of these types of games? I absolutely *adore* this one, and would play others as well!

**Comment by Shkeffy** [comment]
Also, maybe making the 'console' at the bottom right look better formatted?

**Comment by Shkeffy** [comment]
(Getting its own website?) I'm being too much lmao.

**Comment by Shkeffy** [comment]
For the PWA thing, you can use: https://www.pwabuilder.com/.

**Comment by Shkeffy** [comment]
By the way, I am creating a 'dark mode' for it as we speak @landgreen. (I'm just so bored and this game is great)

**Comment by landgreen** [comment]
hi,  glad you enjoy the game,  just a little hobby of mine.

You can save the webpage and run that offline.  I normally use the game that way.
I'm not sure there is any value to a web app over a webpage, but 

If you have specific suggestions for CSS or anything in the in game console, I'd love to hear it.
Dark mode would be cool.  I've tried but I had trouble finding a color pallet that works, but I do think there it could be worth it.

**Comment by Shkeffy** [comment]
> hi, glad you enjoy the game, just a little hobby of mine.
> 
> You can save the webpage and run that offline. I normally use the game that way. I'm not sure there is any value to a web app over a webpage, but
> 
> If you have specific suggestions for CSS or anything in the in game console, I'd love to hear it. Dark mode would be cool. I've tried but I had trouble finding a color pallet that works, but I do think there it could be worth it.

I meant like, n 'game console' (In the bottom right), instead of writing 'm.health =+ ###', writing '### has been added to the health bar'. And, for the saving webpage and running offline,  I don't really understand that. I save it, and when I don't have Wi-Fi, it does the normal 'no wifi' thing. I can maybe try to find a good color combination; I have replit so it's literally a line of code to copy the webpage. I'll update when I find a good combination.

**Comment by landgreen** [comment]
oh, I wrote an in game console for n-gon that you could type into.  it worked as a pipeline to the real browser console.  I'll see if I can dig up that old code.

I just tested "save as" for n-gon
I then disconnected my internet and it worked fine.  Must be on OS/Browser thing
I bet there is a way for you to get it working

**Comment by Shkeffy** [comment]
Look at this so far: https://ngondark.shkeffy.repl.co/

**Comment by Shkeffy** [comment]
Kinda sucks but kinda doesn't!

**Comment by Shkeffy** [comment]
Honestly, I have *no* idea how to make the game itself black-

**Comment by Shkeffy** [comment]
If you use Replit, here: https://replit.com/join/uzjffjsvfx-shkeffy

**Comment by Shkeffy** [comment]
> oh, I wrote an in game console for n-gon that you could type into. it worked as a pipeline to the real browser console. I'll see if I can dig up that old code.
> 
> I just tested "save as" for n-gon I then disconnected my internet and it worked fine. Must be on OS/Browser thing I bet there is a way for you to get it working

If you close the tab and turn it back on after a minute, doesn't work :/

**Comment by landgreen** [comment]
well the html site doesn't work off line, but you can just save a complete copy of the website and run that off line.

**Comment by Shkeffy** [comment]
@landgreen

**Comment by landgreen** [comment]
"Open the three-dot menu on the top right and select More Tools > Save page as. You can also right-click anywhere on the page and select Save as or use the keyboard shortcut Ctrl + S in Windows or Command + S in macOS. Chrome can save the complete web page, including text and media assets, or just the HTML text."

**Comment by Shkeffy** [comment]
The thing is, it doesn't save the complete web page.

**Comment by landgreen** [comment]
does for me

**Comment by Shkeffy** [comment]
And the website fully works?

**Comment by landgreen** [comment]
yeah,  the only difference is it has it's own settings

**Comment by Shkeffy** [comment]
Eh, it's alright. I'll figure it out.

**Comment by macksonp** [comment]
Just download the source code and play with your browser offline

Kind regards,

Jackson Prater
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
