### ISSUE TITLE
initial level wrong I think

### ISSUE THREAD

**Issue by Rhystify** [landgreen/n-gon#284]
When I click to start the game, it takes me to the first level but it is not the normal initial level, it reminds me of the arena map with more obstacles. No tech spawn at all, no gun, no heals, and no research. it was not like this yesterday when I played. any help would be welcome.

**Comment by kgurchiek** [comment]
yeah, the testing level was used during development, but he forgot to remove it in the published version https://github.com/landgreen/n-gon/issues/283

**Comment by landgreen** [comment]
thanks.

**Comment by Rhystify** [comment]
Thank you so much, I really love this game!
