### ISSUE TITLE
Suggestion: log errors in in-game console

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#285]
Many people either can't or don't know to open dev tools to access the console to view error messages when they encounter a bug, so if you had it log to the in-game console on the bottom left it could help people report bugs.

```js
window.addEventListener('error', error => {
  simulation.makeTextLog(`<strong style='color:red;'>ERROR:</strong> ${error.message}  <u>${error.filename}:${error.lineno}</u>`)
});
```

**Comment by landgreen** [comment]
I looked into sending all console messages to the in-game console a year ago.  I can't remember why I didn't add it to the game. Anyways, let's add in your idea and see what happens.
