### ISSUE TITLE
add older versions of n-gon to repo

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#286]
please?
![image](https://github.com/user-attachments/assets/559d863c-4fc1-4019-a856-3da2c6a16e45)

**Comment by landgreen** [comment]
You can load any commit you want.  You can also clone the repo state of a random commit and make your own repo from it.
https://github.com/landgreen/n-gon/issues/256#issuecomment-2110052826

**Comment by kgurchiek** [comment]
the old versions aren't in the releases section, you have to go to the commit history
