### ISSUE TITLE
Two plasma jets

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#287]
<img width="579" alt="Screen Shot 2024-07-20 at 11 16 10 AM" src="https://github.com/user-attachments/assets/59746ffa-33f6-4eb6-bdb4-3ce68f77350d">

**Comment by landgreen** [comment]
thanks,

Ha, I just tried it out,  they stack to give you an extra long jet.  Maybe after I remove one I'll allow you to get this tech multiple times.
