### ISSUE TITLE
Accessibilty issue

### ISSUE THREAD

**Issue by sneakysquatch** [landgreen/n-gon#288]
Since the change to make upgrade descriptions refer to "weapons" and "upgrades" as simply colored orbs, as a colorblind person, I cannot distinguish the colors which has confused me a lot. Can you add a setting to replace the colored circles with text? When they are in the overworld, I can generally tell them apart (although it would be great if there was and option to make overworld orbs more distinct too, maybe a saturation buff?), but in descriptions, they are too tiny to ascertain what they represent. You could add a "colorblind mode" adding these features as one toggle.
Thanks!

**Comment by landgreen** [comment]
I thought about that, but I made sure each orb has different brightness in addition to color.  Fields are brighter, then tech, and guns are the darkest.  I didn't think it would be an issue, but I'd love to learn more.  What type of color blindness do you have?

**Comment by landgreen** [comment]
I could probably add an option replace the orbs with a single letter to keep spacing similar.
The full word might cause spill over.

Do you only have trouble with the big orbs,  or does ammo and research and coupling need letters too?

**Comment by landgreen** [comment]
also if you can think of something better then a letter I'm open to ideas,  maybe an emoji or a ascii shape

**Comment by landgreen** [comment]
I'm messing around to see how easy it is to differentiate.  Here is black and white.  
<img width="397" alt="Screenshot 2024-07-23 at 10 20 30 AM" src="https://github.com/user-attachments/assets/ff4049ef-51ed-48d0-9226-c668216f65fd">
Of course most color blindness isn't black and white, but I'm not sure how to simulate R-G color blindness.

**Comment by landgreen** [comment]
<img width="397" alt="Screenshot 2024-07-23 at 10 59 01 AM" src="https://github.com/user-attachments/assets/7b7cbfa2-477a-42c7-a88f-4e8cdd8aea40">
mouse over seems to work fine for the larger orbs, nor sure about smaller ones yet
