### ISSUE TITLE
typo (and difficulty discussion)

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#290]
there's two spaces between "+3" and "seconds" in the description of `6s half-life`

**Comment by landgreen** [comment]
ha, good catch.  Although html automatically converts groupings of spaces to one space.  It's still something I'd rather fix.

I've got 1.5 more weeks left before summer vacation ends.  Anything you think I should work on?

**Comment by kgurchiek** [comment]
I personally have heard a lot of complaints about the new difficulty system being worse than the older one, and it definitely does feel to me like the harder difficulty is easier than "why" mode was, so beating the hardest difficulty is no longer the great feat it used to be. I also think that they could definitely be more unique, as half of the difficulties are just stat changed, which could just be an implied passive effect for each difficulty instead. I like the difficulties that really affect gameplay like adding more bosses, spawning less tech, or increasing shielded mob chance. In my opinion every difficulty should have a unique quirk that forces you to change your playstyle and/or go-to build. Maybe the other difficulties could give mobs increased lock-on and attack speed, have a chance to deflect bullets (to make use of that deflect function which as I recall isn't currently used at all in any official content), or patrol around like a Roomba to make it harder for the player to sneak through undetected (which could discourage cheesing levels by wiping everything out with drones or pilot wave).

It would also be pretty fun if there were junk difficulties (which are unlocked by getting a junk tech, similar to tinker unlocking junk tech in the experiment menu), like playing at 2x speed or making everything have its own gravitational pull like in planetesimals.

**Comment by landgreen** [comment]
My plan was to make all the difficulties feel pretty similar to help with balance.  I didn't think someone having a hard time on normal would ever even want to try why mode.  Maybe I didn't consider how as a person plays it more they get better, and they want some variety as they progress.  I'll see if I can add some spice to the levels, but it's tough to balance being interesting vs. being annoying.

I haven't beaten n-gon on the last 2 difficulties, so I figured overall balance was good.  Have you've beat the game on the hardest difficulty?

**Comment by landgreen** [comment]
ok I came up with some ideas:
The main idea is to add in 1-2 random negative effects that only last 1 level.
<img width="531" alt="Screenshot 2024-07-30 at 9 30 09 AM" src="https://github.com/user-attachments/assets/5b8e255d-e0f3-4208-b6de-444377f893ac">

>   **random effect/phenomenon ideas:**
    if player takes too long on a level spawn mobs
    4x chance for mob shields
    mob death spawns something -  bullets,exploders,a copy of the mob that died
    mob death heals nearby mobs
    boss heals nearby mobs
    power ups are sent to next level
    a random laser every 10? seconds (like laserLayerBoss)
    after getting a tech eject one of you tech
    -2 choices
    2x ammo costs
    2x energy costs
    2x research costs
    mobs slowly regen health
    player damage is 0.25x while player is invulnerable
    exit door takes 10x time to open and while door is opening (ghosters, suckers) attack?
    can't pause, like tech: eternalism
    can't have more then 15 bullets
    all hazards: lasers and slime do 3x damage
    bots do 0.5x damage
    explosions do 0.5x damage
    lasers and radiation do 0.5x damage
    freeze effects last 0.25x time
    duplication is set to zero

**Comment by kgurchiek** [comment]
> I guess you want unbalanced and stupidly hard for the final difficulty.
_Yes_, the hardest mode should incredibly hard, and it should be very impressive to beat it. I don't know if you've ever played Doom but when people complained about the game being too easy for experienced players the developer added a mode that was so incredibly hard that he himself thought it was impossible to actually beat it without dying. While we can always make up our own challenges like "hardest difficulty but you can only take one tech", it's a lot cooler and more fun when it's an official mode.

**Comment by kgurchiek** [comment]
Also maybe some other possible effects could be significantly slower energy regen to nerf energy-dependent builds and another that makes ammo powerups give less bullets and divides the player's current ammo count by that same factor (but it's multiplied back up when the level is complete)

**Comment by kgurchiek** [comment]
> mob death heals nearby mobs
maybe for this one if the player gets damaged it also heals nearby mobs?

**Comment by kgurchiek** [comment]
maybe this is more fit for a boss than a difficulty effect but giving ablative drones to mobs would be cool

**Comment by landgreen** [comment]
cool all good ideas
I added them to my list

On eternalism I do want to point out n-gon will pause if you switch tabs.  I'm not sure if it makes the tech more or less interesting though.  Maybe I could switch it to only not pause while choosing tech, gun, fields.

**Comment by kgurchiek** [comment]
> exit door takes 10x time to open and while door is opening (ghosters, suckers) attack?

maybe to prevent people from cheesing this with perfect diamagnetism or standing wave the door could be locked until some minimum amount of those mobs have been killed?

**Comment by Whyisthisnotavalable** [comment]
how about making doors locked until the boss is beaten?

**Comment by landgreen** [comment]
I though about it, but I haven't added that in the past because sometimes the boss can be alive but not reachable, like it if ends up in the sky or below the map.

**Comment by AnnonymousNerd87** [comment]
I just got my new chromebook, and my first reaction upon reading this is
that some of these are just random "oh ok you're doing a (blank) run? I
guess you just DIE!"

also I feel like ejecting tech should ALWAYS be optional, or at least
controlled, because otherwise some stuff just kindof kills some builds,
especially mass energy.
