### ISSUE TITLE
tech suggestion: enable isStatic for blocks

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#291]
I was messing with body properties and found that if you set `isStatic` to `true` on a block it will stay completely frozen in the air when thrown, but it keeps its velocity. This makes it "bouncy" if you run into the front and will throw you a bit if you grab it again, especially if you jump just before you grab it. It was pretty fun to play with so I thought it would make a cool tech.

**Comment by kgurchiek** [comment]
Here's some gameplay I recorded with it:
https://github.com/user-attachments/assets/ef350137-4dbb-40f2-b0a7-9fa464950595

**Comment by landgreen** [comment]
Should be easy to make a JUNK tech out of this.  The isStatic tag can sometimes lead to janky physics, but it's probably fine...  Can't be worse the the wikipedia tech

**Comment by kgurchiek** [comment]
What do you mean?! Wikipedia is literally the best tech in the game!

**Comment by landgreen** [comment]
Well, I just mean it's only functional about 80% of the time, sadly I have to nerf it by 1 research next patch.

**Comment by LexLeethorMain** [comment]
ive played a lot, what is the wikipedia tech??

**Comment by kgurchiek** [comment]
a new junk tech that was just added in the latest update

> After you get a new tech you have 7 seconds to study before a quiz, 4 research if you aces the quiz.

**Comment by landgreen** [comment]
ok I made the JUNK tech.  It only took 5 minutes to write.  I'm not going to even check for bugs.  I'm sure it's fine.

**Comment by landgreen** [comment]
looks like it just kills any mobs that gets near...
hmmm might be overpowered.  What if you dropped one on the final boss.

**Comment by kgurchiek** [comment]
block damage should probably just be disabled with that tech then

**Comment by kgurchiek** [comment]
makes sense anyway since the blocks aren't moving

**Comment by landgreen** [comment]
I just tested on final boss looks like it doesn't trigger a collision interaction on the boss, and unless you get a few block damage techs it doesn't hit that hard on level 13 mobs.

**Comment by kgurchiek** [comment]
are you still able to accelerate them with pilot wave?

**Comment by landgreen** [comment]
pilot wave doesn't seem to effect it neither does plasma torch.  I think the velocity can't be changed after the throw

**Comment by kgurchiek** [comment]
What about laser with the tech that pushes blocks?

**Comment by landgreen** [comment]
laser and plasma torch are the same code

**Comment by landgreen** [comment]
someone should make a community map around these blocks

**Comment by kgurchiek** [comment]
yeah I was considering doing that, I'm still not sure exactly what I'd do. I want it to be centered around static blocks, but it also shouldn't soft-lock you if you somehow lose them or something like that.

**Comment by kgurchiek** [comment]
Can wormhole still eat static blocks?

**Comment by landgreen** [comment]
oh yeah, I forgot that blocks can't explode or be eaten...
yes wormholes eat them just fine

**Comment by landgreen** [comment]
maybe make it so new blocks spawn if the blocks get eaten,  like how in the game portal you get new cubes when the old cube dies

**Comment by landgreen** [comment]
oh hey,  what do you think about the level drawing animation?
I'm considering adding it to every new level  (not just reactor and final)
the reason is with the new random difficulty on each level I need a way to let the player know the effect is.
<img width="866" alt="Screenshot 2024-08-02 at 2 45 38 PM" src="https://github.com/user-attachments/assets/68324f14-3298-4fae-beea-a84b72765573">
