### ISSUE TITLE
interest tech + laser and other guns

### ISSUE THREAD

**Issue by JayCubby-enwiki** [landgreen/n-gon#292]
Sorry this is short, will expand when I have more time

When the current gun selected is laser (e.g.) interest doesn't give accrued ammo, only heals and research (tested with 2 guns, missile and laser). When missile is selected, ammo is given alongside the others as normal.

**Comment by JayCubby-enwiki** [comment]
![Screenshot 2024-08-01 9 18 37 PM](https://github.com/user-attachments/assets/bf8614ed-ab20-469a-a1e3-568638aca960)
Another glitch I forgot about: this mob, whose name escapes me, sometimes teleports through the wall on sewers.

**Comment by landgreen** [comment]
you are getting the correct amount of interest on the laser.  It has zero ammo, so it gives 5% of 0 = 0.

Do you think it should be an average of all your ammo instead of your current ammo?  That might be better.

**Comment by JayCubby-enwiki** [comment]
That might be a better idea, or perhaps give the ammo based on how many powerups have been picked up by _m_, regardless of whether ammo would come out of it.  
Cheers!

**Comment by landgreen** [comment]
I think I switched interest over to the average system in this recent patch.  There my be bugs though.
