### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LexLeethorMain** [landgreen/n-gon#293]
Is there a way to force the tech that makes you play planetesimals or was the tech removed. I have a project https://lexleethormain.github.io/CBGames and n-gon is included but i dont think planetesimals works right. I want to test a custom fix.

**Comment by landgreen** [comment]
you can run this in the console
tech.giveTech("planetesimals")
This only works on https://landgreen.github.io/n-gon/

A few places you can directly play it
https://codepen.io/lilgreenland/pen/jrMvaB
https://cdpn.io/pen/debug/jrMvaB?authentication_hash=dXMqBnWJnPyr
https://landgreen.github.io/planetesimals/index.html
