### ISSUE TITLE
[BUG] Picking up tech occasionally causes the game to zoom way out

### ISSUE THREAD

**Issue by Dystopia-user181** [landgreen/n-gon#294]
Picture of it happening with all the tech I have. (This is on chrome browser, if it affects the bug) 

![image](https://github.com/user-attachments/assets/d3cc55e4-18be-404c-99f3-17cc236ce635)

I attempted to reset it to normal with simulation.zoom = simulation.zoomScale = 0.3 but then I had the opposite problem where picking up tech or going to a new level would cause the screen to zoom in like crazy.

**Comment by landgreen** [comment]
hmmmmm I can't figure out how that would work.

Has it happened more than once?
Did it happen only on community maps?

**Comment by JayCubby-enwiki** [comment]
> Has it happened more than once? Did it happen only on community maps?
I have only seen it on community maps myself, I've forgotten which

**Comment by Edit5920** [comment]
It happens a lot for me and always on community maps. Also it only happens when experimenting.

**Comment by jo9182** [comment]
It happens to me occasionally. I believe it has only happened on community maps, though

**Comment by corneeme** [comment]
i had a similar problem on the map with the sword except it was when the boss on that level hit me

**Comment by corneeme** [comment]
I think I figured it  out, sometimes when you pick up a tech and scroll it will zoom you out, if that happens you can also scroll to zoom in and out

**Comment by landgreen** [comment]
ok so the bug report about 
simulation.enableConstructMode()
being left in several community maps is linked to this bug

I'm gonna call it solved good job @corneeme
