### ISSUE TITLE
Ablative drones * mass-energy equiv

### ISSUE THREAD

**Issue by JayCubby-enwiki** [landgreen/n-gon#295]
![Screenshot 2024-08-10 6 19 41 PM](https://github.com/user-attachments/assets/6f68e84d-e82c-4d07-aa9a-78a84634b28f)
Should be after losing health. 

A thought: Perhaps with the eternalism tech, allow the pause _menu_ to show up but not actually pause the game, sort of like what happens upon selecting a tech? I'm unsure as to how hard this would be to implement. Just a thought

**Comment by landgreen** [comment]
ok I changed the text to be energy when you have mass-energy.
