### ISSUE TITLE
TypeError: powerUps.field is not a function (level.js:629)

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [landgreen/n-gon#296]
Saw this error in a screenshot from a person in the community Discord server:
![image](https://github.com/user-attachments/assets/16d384c2-36bc-48ab-b1cc-b69087fed5bc)

I looked at the code, and found this:
![image](https://github.com/user-attachments/assets/d98986db-541a-4e75-9dd4-c00772e3adea)

My proposed quick and easy fix:
Change `powerUps.field()` to `powerUps.orb.field()` on line 629, like the `powerUps.orb.gun()` right after it.
*While you're at it, you may want to search the codebase for any similar errors - shouldn't take very long*

**Comment by landgreen** [comment]
thanks, fixed
I haven't check the tutorial in a while.
