### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#297]
![image](https://github.com/user-attachments/assets/a45e4ecb-7906-4107-8acd-9a320859e3e5)

**Comment by landgreen** [comment]
I caught a bug like this a few days ago.  My bug was also with rebound and super balls.
I hope my fix works, but I can't reproduce the error. I think I got it.

**Comment by landgreen** [comment]
looks like the in game console logging system errors is working well.
