### ISSUE TITLE
balance feedback on constraint and difficulty from recent patch

### ISSUE THREAD

**Issue by landgreen** [landgreen/n-gon#298]
Let me know what effects should be increased or decreased. The idea behind constraints is that they should counter builds too focused on one theme.

If the only thing you can do is bots, the constraint that slows down bots should be difficult enough that you might skip that level's boss.  Or if you have a build that requires you to pick up power ups to get damage, the 0.1x build will counter that.

**Comment by JayCubby-enwiki** [comment]
hmm... well these two constraints are fundamentally incompatible
![Screenshot 2024-08-15 8 53 10 PM](https://github.com/user-attachments/assets/e505c738-91d8-4846-a198-8606378f2b80)
