### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by porgman102** [landgreen/n-gon#299]
Is there supposed to be no audio? because this game could greatly improve with some small ambiance or like explosion screenshake and sound

**Comment by landgreen** [comment]
I don't understand why games have music.  People can just play their own music, and they can play what they want.
Sounds effects like foot steps and explosions sounds are a good idea, but just not something I have any skill at.

**Comment by kgurchiek** [comment]
I haven't really looked into how good ai has gotten at sound nowadays, but maybe you could use ai-generated sound effects like you did with tech images?
