### ISSUE TITLE
Game don't work

### ISSUE THREAD

**Issue by DeTitan** [landgreen/n-gon#3]
Hey Landgreen
I tried to play your game but whenever I click on the screen everything disappears and nothing happens afterwards. Can you look into this?

**Comment by landgreen** [comment]
I'm not sure what the problem is.  What browser are you on?  Is there an error message in the browser's console?

**Comment by DeTitan** [comment]
I'm using a Chromebook, and no there isn't an error message

**Comment by landgreen** [comment]
hmmm. I'm not sure.  If you learn anything more let me know.
