### ISSUE TITLE
New Junk tech issue

### ISSUE THREAD

**Issue by Xboi1972** [landgreen/n-gon#300]
The new junk tech stationary has an issue with the block that was thrown where is you stand on top of the block you threw you will be launched upwards. Don't know if this was intentional but if it is not please fix.

**Comment by landgreen** [comment]
This is how it works.  It's hinted at in the tech description
<img width="364" alt="Screenshot 2024-08-14 at 7 14 09 PM" src="https://github.com/user-attachments/assets/65a73381-3b46-416c-96b2-2bc1ecef653e">
