### ISSUE TITLE
Tech proposals

### ISSUE THREAD

**Issue by JayCubby-enwiki** [landgreen/n-gon#301]
1. Ice-IX tech modification titled Ice-VII -- 0.8x ice damage, 4x duration (that is, ice crystals last 4x longer)
2. Boosts also increase speed, say by 1.3x.

**Comment by landgreen** [comment]
hmmm it does seem like Ice-IX could use an increase in range
and more boost tech makes sense now that the boost graphic is so nice looking.

**Comment by JayCubby-enwiki** [comment]
I suppose you could just increase the range, but if it's a separate tech consider making the crystals square, in phase with ice-VII's crystal structure. This is a game, but it _is_  physics-themed.

**Comment by landgreen** [comment]
I added ice-VII to my todo list 
4x duration is probably a bit too much though, I'll have to test it
tech: ice-VII - 1.5x duration

**Comment by JayCubby-enwiki** [comment]
Yeah, you are probably right.
