### ISSUE TITLE
Shotgun-RivetGun

### ISSUE THREAD

**Issue by iNoobBoi** [landgreen/n-gon#303]
<img width="1121" alt="Screenshot 2024-08-25 at 22 04 17" src="https://github.com/user-attachments/assets/e20fd27f-c7a2-433a-8790-34dbb0032304">

When firing shotgun with "Rivet Gun" tech, shotgun fires rivet in addition to normal shotgun pellets.

**Comment by landgreen** [comment]
this isn't a bug...

**Comment by Invincible-Atlas** [comment]
I can see how it would be confusing, though
