### ISSUE TITLE
Level transition idea

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#305]
I'm going to add this on my next map, but I think this might fit base n-gon 
[recording.webm](https://github.com/user-attachments/assets/4a2e5f93-aebb-43df-8f25-6a67303812a6)

**Comment by landgreen** [comment]
The Circle Wipe Transition looks cool.
Or are you talking about the level select?  Also cool

**Comment by Whyisthisnotavalable** [comment]
"Level transition idea" What do you think I was talking about?

**Comment by AnnonymousNerd87** [comment]
it could mean either the circle effect or the level *select*

**Comment by TNTiger17** [comment]
A testing hub place could be cool after unlocking testing mode as a console option

**Comment by corneeme** [comment]
like somewhere you go when u start a new run with testing mode or something

**Comment by landgreen** [comment]
How would the testing hub be different from the normal initial level?
(I do already have a testing level, named "testing"  that I use for testing various things, but it's not very pretty or interesting)

**Comment by corneeme** [comment]
hm, maybe some sort of  like experiments or something that you can mess around with using testing mode, like maybe some rotating blocks, or black holes that are stuck in place that are invincible for gravity experiments

**Comment by corneeme** [comment]
and of course the level selector

**Comment by landgreen** [comment]
well, I could add a level selector power up that only shows up when you enter testing mode in the initial level

**Comment by corneeme** [comment]
hm I actually like that idea better, that seems way more n-gonish

**Comment by corneeme** [comment]
n-gony?

**Comment by corneeme** [comment]
i  give up

**Comment by landgreen** [comment]
n-great

**Comment by corneeme** [comment]
could you also add some sort of menu for  the  console commands in testing mode, I don't have console on my chromebook

**Comment by landgreen** [comment]
I tried once to make a real in game console.  I ran into issues...  can't remember, but it didn't seem like a good idea.

**Comment by corneeme** [comment]
ah  ok I get it its fine
