### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#306]
max difficulty with mass-energy equivalence makes the health bar appear but is empty

**Comment by Whyisthisnotavalable** [comment]
Pausing with the no healthbar constraint also makes it appear

**Comment by landgreen** [comment]
thanks, I this is fixed in next patch.

**Comment by landgreen** [comment]
by the way, next patch is gonna be cool.  I finally figured out how to flip the player upside down.  So I'm making a level around that mechanic.

**Comment by Whyisthisnotavalable** [comment]
can't wait to see it

**Comment by kgurchiek** [comment]
ooh that sounds really cool

**Comment by LexLeethorMain** [comment]
gravity flipping on a level would be cool, and a junk teck to flip gravity every 5 seconds would be funny

**Comment by landgreen** [comment]
The way I'm doing it it to flip the camera, which is just one line of code, and then about 60 lines of code to remove and reposition every element of the map from the bottom to the top.  So I didn't have to rewrite any physics, but it feels completely authentic.

https://github.com/user-attachments/assets/1b6f4b69-1c6b-4bdd-997e-441f58b87dfa

**Comment by kgurchiek** [comment]
doesn't Matter.js have a `gravity` property you can modify? I remember messing with it at some point and by setting a negative y gravity I could balance out the game's gravity and then flip it in another direction

**Comment by Whyisthisnotavalable** [comment]
> doesn't Matter.js have a `gravity` property you can modify? I remember messing with it at some point and by setting a negative y gravity I could balance out the game's normal gravity (so that the player just floats around), and then from there I could dynamically add to that to flip it in any direction

I did this before too, but then flipping the player upside down would make walking look like it would be walking in the other direction since the velocity is the opposite of what it's supposed to be

**Comment by landgreen** [comment]
matter.js has built in gravity, but I use my own custom gravity so I can have more control.

Sadly, flipping gravity doesn't flip the player's head and feet, jump physics, various mob physics, and probably 50 other edge cases, like buttons.
Although negative mass field is basically flipping gravity.

**Comment by kgurchiek** [comment]
Yeah I meant to combine your player flip method with the gravity swap so that it could change direction easier, I imagine the current method of redoing the map upside down would break the more complex community maps that aren't built to handle it

**Comment by landgreen** [comment]
Yeah, my method is only going to be viable on one specific level.  I don't think it would be possible to apply it to all maps without writing complex custom flip code for every map.
