### ISSUE TITLE
[BUG] Quantum Immortality resulted in an error.

### ISSUE THREAD

**Issue by jo9182** [landgreen/n-gon#308]
I believe it's just the community map "house". I haven't tested it out on any other maps, though. I also haven't tried replicating this error.
Build URL: https://landgreen.github.io/n-gon/index.html?&seed=190386&gun0=harpoon&gun1=wave&tech0=autonomous%20defense&tech1=Bessemer%20process&tech2=smelting&tech3=interest&tech4=accretion&tech5=quantum%20immortality&tech6=heuristics&molMode=2&field=field%20emitter&difficulty=6

![image](https://github.com/user-attachments/assets/5a8adcf2-117f-4234-8990-01c6e61922c5)
![image](https://github.com/user-attachments/assets/a3c04118-94b5-4cb2-bbf4-bde2aafce2c9)

**Comment by landgreen** [comment]
huh, looks like the bug is occurring in the physics engine.  That generally means some objects got moving too fast or too big. 
 Maybe something with autonomous defense?  Do you have a large number of bullets?
