### ISSUE TITLE
[BUG] No legs :(

### ISSUE THREAD

**Issue by 298A-E9E3** [landgreen/n-gon#309]
![Screenshot 2024-09-16 5 29 05 PM](https://github.com/user-attachments/assets/39f7adeb-ba37-471d-99c6-51b6b5b47a20)
As you can see, M has no legs. I don't know why this happened, I'm not using any mods or anything. After I reloaded the bug went away.

**Comment by landgreen** [comment]
did you get any junk tech on a previous run?

**Comment by 298A-E9E3** [comment]
no, I didn't

**Comment by 298A-E9E3** [comment]
Another thing I should have mentioned, it's not like I was playing with the Ship junktech; I could still run and jump and aim as normal

**Comment by 298A-E9E3** [comment]
![Screenshot 2024-09-17 10 45 59 AM](https://github.com/user-attachments/assets/576c7166-6202-4212-a4d5-c849f071c291)
It happened again. This time, on the run before the one where the bug occurred, right before I died something weird which may be related to the bug happened. I was just playing normally, when suddenly something (I don't know what) happened, and I was teleported into the floor a bit to the left of the starting door, and then I died.

**Comment by landgreen** [comment]
yeah it's gonna be something that occurred when you died.  If it happens twice we are close to understanding it.

**Comment by 298A-E9E3** [comment]
Also, apparently the bug only goes away when you reload the game. I played a bit, then died, and when I started a new run, M still didn't have legs

**Comment by 298A-E9E3** [comment]
Update: I still haven't reloaded, and I think collisions broke; I'm just falling through the floor constantly

**Comment by creator1116** [comment]
are you in level null?

**Comment by 298A-E9E3** [comment]
no, I haven't even unlocked testing mode yet

**Comment by c-rxxp-y** [comment]
I've also had this happen to me recently, mainly while testing mods. it usually occurs for me after selecting certain tech/guns/fields that I've added in experiment mode
