### ISSUE TITLE
idea (this doesn't really belong on the gh but whatever)

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#310]
the n-gon community should organize some sort of convention online. how about n-con.

**Comment by landgreen** [comment]
ha, I don't think n-gon is big enough, but the name is a gone one
n-con

**Comment by creator1116** [comment]
how a about
like a n-gon multiplayer launch party

**Comment by kgurchiek** [comment]
n-gon multiplayer isn't official, but I can host an event in the community discord server when it's done

**Comment by AnnonymousNerd87** [comment]
that sounds awesome

**Comment by AnnonymousNerd87** [comment]
n-con, hah

**Comment by corneeme** [comment]
they would wouldn't they
