### ISSUE TITLE
More of a Request

### ISSUE THREAD

**Issue by LexLeethorMain** [landgreen/n-gon#311]
I would like  n-gon to have a setting where you cna play and not have you game end if you dont have undifned or testing mode if one dont exist already. And how hard do you think it would be to remake n-gon in scratch would be a fun project

**Comment by LexLeethorMain** [comment]
multiplayer scratch n-gon could be possible

**Comment by kgurchiek** [comment]
I'm already working on a multiplayer mod

**Comment by 3xionDev** [comment]
> I would like n-gon to have a setting where you cna play and not have you game end if you dont have undifned or testing mode if one dont exist already. And how hard do you think it would be to remake n-gon in scratch would be a fun project

I think experiment mode does this already. Also, n-gon was originally ideated in scratch so this would seem kind of redundant.

**Comment by AnnonymousNerd87** [comment]
yeah, search up "mech" on scratch and you might find it

**Comment by 3xionDev** [comment]
> yeah, search up "mech" on scratch and you might find it

> I would like n-gon to have a setting where you cna play and not have you game end if you dont have undifned or testing mode if one dont exist already. And how hard do you think it would be to remake n-gon in scratch would be a fun project

https://scratch.mit.edu/projects/14005697/fullscreen/
it's listed in the version picker in the n-gon start screen

**Comment by landgreen** [comment]
yep experiment mode is endless.
