### ISSUE TITLE
some things that need a nerf

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#313]
-grenades (vacuum bomb, MIRV, ammonium nitrate)
-missiles (ICBM, launch system, ammonium nitrate, molecular assembler)
-wormhole (charmed baryons, invariant)

**Comment by AnnonymousNerd87** [comment]
grenades deal too much damage much can be hard to hit, so a damage nerf but
size buff (projectile size not aoe size, the aoe is fine) would be
appreciated

**Comment by AnnonymousNerd87** [comment]
I agree with the other 2 though

**Comment by creator1116** [comment]
update: mines
especially laser mines

**Comment by LinuxRocks2000** [comment]
noooooo no nerfingggg nerfing baaaaaddddd

**Comment by creator1116** [comment]
update : nerf linux
especially linuxrocks2000

**Comment by AnnonymousNerd87** [comment]
Mines have insane dps but low ammo, so you have to be stratigic

**Comment by creator1116** [comment]
but the insane dps is a little too insane

**Comment by creator1116** [comment]
not as crazy as the grenades tho
sometimes with the right tech i can instakill bosses with grenades

**Comment by creator1116** [comment]
can send recording if you want

**Comment by AnnonymousNerd87** [comment]
maybe a mines ammo buff and firerate nerf could work

**Comment by AnnonymousNerd87** [comment]
I just feel like for casual players mines are tough because they have such
low ammo

**Comment by N-gonplayer** [comment]
Mines are not overpowered especially compared to spores

**Comment by AnnonymousNerd87** [comment]
I agree
