### ISSUE TITLE
[BUG] Health bar sometimes shows up when using mass-energy equivalence

### ISSUE THREAD

**Issue by Invincible-Atlas** [landgreen/n-gon#314]
The healthbar sometimes appears, despite me having the mass-energy equivalence tech
![image](https://github.com/user-attachments/assets/efedda30-d004-4260-88db-c49423f7c656)

**Comment by AnnonymousNerd87** [comment]
this has already been reported

**Comment by 298A-E9E3** [comment]
Then why is it still happening?

**Comment by landgreen** [comment]
it doesn't happen to me...

But I'm running the next patch on my local version.
The next patch is coming soon, I finally got done with the new level, so in a couple days.
