### ISSUE TITLE
Idea: N-gon account.

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#316]
it has become increasingly annoying for players that play with a local file to have to restart all the lore and testing in n-gon every patch. What if a account system was introduced? this could be accomplished with something like firebase

**Comment by AnnonymousNerd87** [comment]
you could just use console commands, an account system would be
overcomplicated

**Comment by AnnonymousNerd87** [comment]
also an account system doesn't *feel* like n-gon

**Comment by coaldeficit** [comment]
copy paste your localSettings from the old files to the new ones

**Comment by corneeme** [comment]
maybe there could just be an export/import collected stuff or something

**Comment by corneeme** [comment]
idk

**Comment by creator1116** [comment]
agreed
or maybe there could be a "playerdata" file
that could be transferred over.

**Comment by landgreen** [comment]
making accounts would require a server, and that would require money which n-gon doesn't make.

you can save you settings this way
I just tested this and it worked

on the old n-gon's console type:   localStorage.localSettings
save this result to a text file or email or something

on the new n-gon's console type:  localStorage.localSettings = 
and enter in what you saved

**Comment by landgreen** [comment]
I don't have plans to add a button.  I think you could do it as a bookmarklet.  If that works for you let us know.

**Comment by kgurchiek** [comment]
This bookmarklet should work, just paste in your localSettings when prompted: `javascript:(function() { localStorage.localSettings = prompt('localSettings:'); localSettings = JSON.parse(localStorage.localSettings) })()`
