### ISSUE TITLE
[BUG] commandeer community map enables construct mode

### ISSUE THREAD

**Issue by coaldeficit** [landgreen/n-gon#317]
level.js line 18627

**Comment by creator1116** [comment]
Im pretty sure thats smth to do with level generation

**Comment by creator1116** [comment]
so like its intentional and no harm done

**Comment by landgreen** [comment]
I went looks for more of construction mode and found 4 different community levels that left it in...
<img width="1177" alt="Screenshot 2024-09-26 at 4 48 38 PM" src="https://github.com/user-attachments/assets/a88170b0-492b-42cf-8b17-1f6c23e1cb33">

I removed them all, thanks
