### ISSUE TITLE
What else should go in this list?

### ISSUE THREAD

**Issue by landgreen** [landgreen/n-gon#318]
I'd like to make this list longer.
What else should I add?
<img width="811" alt="Screenshot 2024-09-27 at 7 24 22 AM" src="https://github.com/user-attachments/assets/ff229c15-eea2-4560-9d70-b323ea94f348">

I was thinking of adding this:
//download latest version of n-gon
https://codeload.github.com/landgreen/n-gon/zip/refs/heads/master

**Comment by kgurchiek** [comment]
m.energy is in there twice

**Comment by landgreen** [comment]
woops, thanks...
by the way have you found this in game?

**Comment by kgurchiek** [comment]
Yeah, a few days ago I got a massive grey powerup on `initial` that showed the screen. What causes it to spawn?

**Comment by landgreen** [comment]
it spawns every time,  just a fun easter egg,  (maybe make your previous post more obscure)

**Comment by redacted-01** [comment]
umm Level.Setlevel("name")
replace name with the name of the level

**Comment by redacted-01** [comment]
would be useful for trying out new levels and features

**Comment by corneeme** [comment]
how do you trigger this?

**Comment by coaldeficit** [comment]
level.levels = ["clock"];
for messing with the level order, very useful for testing

**Comment by kgurchiek** [comment]
> level.levels = ["clock"];

this is Cornbread2100 and I approve this message
