### ISSUE TITLE
dark stars can't go through portals?

### ISSUE THREAD

**Issue by epicgranol** [landgreen/n-gon#319]
ok so umm this bug kind of always existed but i never really knew why!! uhh basically yep i'm pretty sure this is the case considering on the subway level the macho just doesn't appear.. i think it happens on some levels as well but i'm not sure lmao. i have entropic gravity, the tech that lets the macho go near you if you crouch, but it just doesn't appear no matter how long i crouch and how many times i do it?? erm here's an image though my explanations pretty straightforward i think uhh
![image](https://github.com/user-attachments/assets/c99d187c-21c9-43c2-bfd2-906f776cecb7)

**Comment by epicgranol** [comment]
OMG SORRY I CALLED IT MACHO AT SOME PLACES ITS DARK STARS IM SOSO SORRY ITS CS BEFORE IN LIKE IDK EARLY 2024/LATE 2023 IT WAS CALLED MACHO

**Comment by landgreen** [comment]
This is actually intentional.  Dark Matter doesn't follow you through portals.  I felt like it would feel inaccurate to have the portal just show up after you exit a portal.  I'm not super happy with this situation, but it seems better then the alternative.

**Comment by landgreen** [comment]
ok, I found the issue.  Dark matter was getting removed if it got too far away on subway.  It's fixed now.
