### ISSUE TITLE
[BUG] Error while changing realities.

### ISSUE THREAD

**Issue by jo9182** [landgreen/n-gon#320]
I was changing realities, but I'm unsure of whether it was because of Hilbert Space or Quantum Immortality. I was holding down the spacebar, if that matters.
Build URL: https://landgreen.github.io/n-gon/index.html?&seed=94600&gun0=spores&gun1=wave&tech0=inertial%20confinement&tech1=stellarator&tech2=tokamak&tech3=ablative%20drones&tech4=emergence&tech5=nematodes&tech6=working%20mass&tech7=flux%20pinning&tech8=flux%20pinning&tech9=flux%20pinning&tech10=flux%20pinning&tech11=Hilbert%20space&tech12=first%20derivative&tech13=cross-disciplinary&tech14=thermoelectric%20effect&tech15=mutualism&tech16=electric%20generator&tech17=electric%20generator&tech18=electric%20generator&molMode=2&field=molecular%20assembler&difficulty=7

![Screenshot 2024-10-02 1 30 40 PM](https://github.com/user-attachments/assets/7220eaea-2041-4078-8878-9f822685613b)
![Screenshot 2024-10-02 1 30 32 PM](https://github.com/user-attachments/assets/bfc9cb09-e028-4576-bc8d-a3f3e7132f71)

**Comment by jo9182** [comment]
After I unpaused, it appeared that the game hadn't frozen as my health was depleting from enemies and I could still fire my weapons, it's just that nothing displayed except what you see in the screenshot. The errors vanished upon me switching weapons.

**Comment by jo9182** [comment]
![Screenshot 2024-10-02 1 39 07 PM](https://github.com/user-attachments/assets/9914dbbe-57f7-45fd-b034-e4ff2fb18c98)
Here's this if it's also relevant.

**Comment by landgreen** [comment]
I just want to say that n-gon has some great crashes.  The visuals are fun.  I'll look into the bug.

**Comment by AnnonymousNerd87** [comment]
yeah, I'm glad it isn't just the white screen of death

**Comment by creator1116** [comment]
you can sometimes get a white screen of death

**Comment by corneeme** [comment]
but it just isn't as visually appealing, and less boring

**Comment by Ant-Throw-Pology** [comment]
The only reason the recursive view effect happens is because the error every frame causes `ctx.restore` to not be called, causing the camera transformations to be applied over and over again.

The error detection code should probably be changed:
Remove
```js
window.addEventListener('error', error => {
    simulation.inGameConsole(`<strong style='color:red;'>ERROR:</strong> ${error.message}  <u>${error.filename}:${error.lineno}</u>`)
});
```
...because the 'error' event doesn't really work on file:// URLs (it just has a message of 'Script error' and no useful properties) which many people will be playing on (because the github.io site is blocked, they download the repo to play locally)

Replace the loop functions
```js
normalLoop() {
    try {
        simulation.gravity();
        Engine.update(engine, simulation.delta);
        simulation.wipe();
        simulation.textLog();
        if (m.onGround) {
            m.groundControl()
        } else {
            m.airControl()
        }
        m.move();
        m.look();
        simulation.camera();
        level.custom();
        powerUps.do();
        mobs.draw();
        simulation.draw.cons();
        simulation.draw.body();
        if (!m.isBodiesAsleep) mobs.loop();
        mobs.healthBar();
        m.draw();
        m.hold();
        level.customTopLayer();
        simulation.draw.drawMapPath();
        b.fire();
        b.bulletRemove();
        b.bulletDraw();
        if (!m.isBodiesAsleep) b.bulletDo();
        simulation.drawCircle();
        simulation.runEphemera();
    } catch (err) {
        simulation.inGameConsole(`<strong style='color:red;'>ERROR:</strong> ${(error.stack && error.stack.replace(/\n/g, "<br>")) || (error.message + ` <u>${error.filename}:${error.lineno}</u>`)}`);
    } finally {
        ctx.restore();
        simulation.drawCursor();
    }
},
testingLoop() {
    try {
        simulation.gravity();
        Engine.update(engine, simulation.delta);
        simulation.wipe();
        simulation.textLog();
        if (m.onGround) {
            m.groundControl()
        } else {
            m.airControl()
        }
        m.move();
        m.look();
        simulation.camera();
        level.custom();
        m.draw();
        m.hold();
        level.customTopLayer();
        simulation.draw.wireFrame();
        if (input.fire && m.fireCDcycle < m.cycle) {
            m.fireCDcycle = m.cycle + 15; //fire cooldown       
            for (let i = 0, len = mob.length; i < len; i++) {
                if (Vector.magnitudeSquared(Vector.sub(mob[i].position, simulation.mouseInGame)) < mob[i].radius * mob[i].radius) {
                    console.log(mob[i])
                }
            }
        }
        simulation.draw.cons();
        simulation.draw.testing();
        simulation.drawCircle();
        simulation.runEphemera();
        simulation.constructCycle()
    } catch (err) {
        simulation.inGameConsole(`<strong style='color:red;'>ERROR:</strong> ${(error.stack && error.stack.replace(/\n/g, "<br>")) || (error.message + ` <u>${error.filename}:${error.lineno}</u>`)}`);
    } finally {
        ctx.restore();
        simulation.testingOutput();
        simulation.drawCursor();
    }
},
```
...to have a `try...catch...finally` with `ctx.restore` in the `finally` block, so it always gets called

`level.start()` (in `cycle`) should probably also have a `try...catch` around it to catch any errors from initializing a level

**Comment by landgreen** [comment]
well...  this seems like an improvement,  but I like the way it crashes... It's cool.

**Comment by AnnonymousNerd87** [comment]
agreed

**Comment by landgreen** [comment]
I made some changes that slow down the rate and frequency of switching realties.  I hope has fixed this bug.  Let me know if it occurs again.
