### ISSUE TITLE
what did I do wrong

### ISSUE THREAD

**Issue by bobsburgers72** [landgreen/n-gon#321]
![Screenshot 2024-10-03 2 47 38 PM](https://github.com/user-attachments/assets/ae356578-6da1-43f6-9331-9357fab974df)

everytime I paused this error message would pop up and I lost like half of the junk tech I got when I entered the first level

**Comment by corneeme** [comment]
its the map, I've seen that before but I never noticed the junk tech thing, its whenever the boss hits you

**Comment by landgreen** [comment]
gonna blame this bug on JUNK and ignore it.
