### ISSUE TITLE
tech: Spring Loaded

### ISSUE THREAD

**Issue by redacted-01** [landgreen/n-gon#322]
requires: _not tungsten carbide_ nitinol
+1.5 Jumping
basically you hold your jump button and a bar fills up the more filled the bar is when you release, the higher you will jump. if the bar fills up before you release then it resets. the higher you jump the more energy you use.

**Comment by redacted-01** [comment]
edit: if you have no more energy left, you cannot use this

**Comment by redacted-01** [comment]
edit:
Requires: _not inductive charging, piezoelectricity_

**Comment by AnnonymousNerd87** [comment]
This is just a worse nitinol, you could do the same thing with either
nitinol or lorenz transformation
