### ISSUE TITLE
Editor not removed

### ISSUE THREAD

**Issue by Zizz7d7** [landgreen/n-gon#323]
in one of the community levels the editor is still turned on...
![OMG](https://github.com/user-attachments/assets/33391bd5-b937-41ee-a22a-9bedb06769b4)
`24062:       };
 24063:       simulation.enableConstructMode() //landgreen if you see this can you remove im probably gonna forget
 24064:       for (let i = 0; i < spawn.bossTypeSpawnOrder.length * Math.random(); i++) {`

**Comment by landgreen** [comment]
I think I caught those in the patch from yesterday.  You might be 1 patch behind.
