### ISSUE TITLE
[BUG] Fast Firing

### ISSUE THREAD

**Issue by Invincible-Atlas** [landgreen/n-gon#325]
https://github.com/user-attachments/assets/ef0d896c-d8c5-479b-be08-3913c2c859cb

As you can see from this video, M is shooting really fast. I am using the most recent version of N-Gon, without any mods. Right before recording this video, I was messing around in experiment mode, and I gave myself 9X heuristics. However, it seems to be only the fire rate that transferred over; after recording this video I picked up a tech, and there were no junktech options, despite researching twice.

**Comment by landgreen** [comment]
thanks I got it fixed for next patch.
