### ISSUE TITLE
Bring Back Images

### ISSUE THREAD

**Issue by NV4s** [landgreen/n-gon#326]
Self-explanatory but here are some reasons:

1. It's easier to memorize and understand tech better with images instead of text
2. Using brainstorm is now significantly harder to the point it's nearly impossible to know which tech you are choosing (on time) on a non-touch screen device
3. Images can always be disabled and have automatically been the case when starting on a new device making this update useless
4. Hosting the images could potentially just be done locally in the downloads instead of outsourcing it to MidJourney (if money was also a factor)
5. I think the images were stylistic but could be improved in your view if we try generating it with other AI or use different prompts

#BringBackImages
#RemoveCantilever

**Comment by kgurchiek** [comment]
I agree, adding images was one of my favorite updates to the game. Since most tech don't have unique in-game visuals, the tech images served as a way to visualize what the tech would look like, which made it more interesting and immersive.

**Comment by landgreen** [comment]
oh ok.  I removed images mostly to see if people cared.  If two more people say they want them back I'll return them next patch.

I removed them for a few reasons:
match the style in n-gon
some people kinda hate generative AI in games and I want to avoid that hate
to reduce the total n-gon size (although images are only about 1/3 of the total size)

**Comment by kgurchiek** [comment]
A lot of people were complaining in the community Discord, at least 4 or 5 were complaining the moment the patch notes dropped.

**Comment by kgurchiek** [comment]
Also, regarding the ai images complaints, I personally see nothing wrong with it. From my experience a lot of people that hate ai don't have much reason other than that it's a "trend" to hate on it and/or they're scared of it. It's completely unreasonable for an indie game dev that isn't making money from their game to pay an artist for 400 images, I see nothing wrong with using AI for this. In my mind this is the perfect use of ai-generated images: not being framed on a wall and marveled at, just being used as an asset with a functional purpose in a situation where it wouldn't be feasible to hire an artist.

**Comment by NV4s** [comment]
AI wasn’t a problem, it’s that I heard it was removed due to the AI not
working out.

**Comment by Masbirb** [comment]
I would enjoy images back or at bare minimum make it so you can view techs 3 (or more) wide instead of just 1 wide with no images

**Comment by AnnonymousNerd87** [comment]
also from a pure visual standpoint the images look awesome and feel like
they truly represent the tech shown. For example, accretion disc showing
the accretion disc of a black hole looks really cool, and it feels like you
are slowing down how fast you consume powerups in order to get that 1.07x
damage buff. I don't know if that was a good description, I just love how
the images look.

**Comment by corneeme** [comment]
The main reason I didn't like images was because they were so big, so  if  you found a different way to present them I would be on board

**Comment by NV4s** [comment]
Hopefully they come back next update revamped

**Comment by corneeme** [comment]
definitely

**Comment by Invincible-Atlas** [comment]
yeah, the size was always really annoying; they could probably be hosted on a free cdn.

**Comment by circle-gon** [comment]
I tried having the images, but I personally really hated them because they were so big compared to everything else. If the images were scaled down to be around the same size as the tech boxes, I would definitely enable them since they are very cool.

**Comment by landgreen** [comment]
ok images are back.

I agree the images seem very large, but I can't think of a good way to make them smaller.
I could make new shorter images, but that would take too long.  
I could shrink the size of the images, but that would add in empty space on the sides, and I don't think that would look good.

**Comment by AnnonymousNerd87** [comment]
Thanks

**Comment by corneeme** [comment]
maybe you could put them on the left side of the tech, and resize it  to be square
