### ISSUE TITLE
n-gon website

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#327]
I think that n-gon should have a domain of its own. 
![image](https://github.com/user-attachments/assets/79e2291d-8447-4601-bd7e-4b598e3ac763)
i can buy it for the first few years (maybe)

**Comment by creator1116** [comment]
not https://www.n-gon.game/ because its like 288 dollar per year

**Comment by NV4s** [comment]
Nah

**Comment by corneeme** [comment]
that would be cool, idk tho, i kinda like the GitHub link

**Comment by AnnonymousNerd87** [comment]
it would temporarily solve the issue of n-gon being blocked (because my
school just blocks all github pages made by landgreen)

**Comment by AnnonymousNerd87** [comment]
although I just download the zip so it doesn't matter much to me

**Comment by NV4s** [comment]
The only reason I don't like this idea **as much** is that schools block websites to the point that we need to download the zip to play n-gon. Adding a website is just like the github page getting blocked in school.

**Comment by landgreen** [comment]
I like having n-gon on github.  It seems more in line with the n-gon style.

Please don't play n-gon during class, although I can't understand how are your teachers not noticing that you are playing.
Although maybe you are just playing a game at home on a school computer.  That doesn't seem like a big deal.

**Comment by AnnonymousNerd87** [comment]
I never play during class

**Comment by JayCubby-enwiki** [comment]
> I think that n-gon should have a domain of its own. ![image](https://private-user-images.githubusercontent.com/133981966/375105618-79e2291d-8447-4601-bd7e-4b598e3ac763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NTQxNTksIm5iZiI6MTcyODk1Mzg1OSwicGF0aCI6Ii8xMzM5ODE5NjYvMzc1MTA1NjE4LTc5ZTIyOTFkLTg0NDctNDYwMS1iZDdlLTRiNTk4ZTNhYzc2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMDU3MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTc5ODA0OWQ0MmQ3ODY2NzM0ZGU2OGMyNDMwZGZjMDcwYzliZWZkZDg3M2YzOThkZDY4Njc3ZWMyZTg1NDVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FtTaSJtay2uA3AKLg5YXdOh80lKyNEXf474Jk5HnWEQ) i can buy it for the first few years (maybe)

You could just host a mirror yourself.
