### ISSUE TITLE
Not Working on Chrome Browser

### ISSUE THREAD

**Issue by SilverHallo** [landgreen/n-gon#328]
When I try to play the game at https://landgreen.github.io/n-gon/, I cannot play no matter where I click.
My current Chrome OS is Version 93.0.4577.10. The previous version selectable in the "Older Versions" tab is still playable.

**Comment by AnnonymousNerd87** [comment]
huh. this is a new one.

**Comment by AnnonymousNerd87** [comment]
what do you mean by "cannot play"?

**Comment by landgreen** [comment]
does it work in incognito mode?
did you reboot?

**Comment by JayCubby-enwiki** [comment]
@SilverHallo -- version 93 is really really behind the current chrome version. I've had issues with only 10 versions behind. Expect issues.
