### ISSUE TITLE
Having too much tech breaks the game

### ISSUE THREAD

**Issue by UnknownContinuum** [landgreen/n-gon#329]
![image](https://github.com/user-attachments/assets/a6e31647-cc1f-470d-9bb7-a76b2d2b117a)
I did this by holding y down and it breaks, but going to the next level fixes it.

**Comment by landgreen** [comment]
yeah...  but which tech

**Comment by UnknownContinuum** [comment]
I'll have to check. might be conflicting tech

**Comment by landgreen** [comment]
I've had similar issues with many worlds
something about taking a ton of tech at once can led to a bad interaction, but it's pretty hard to find.

**Comment by AnnonymousNerd87** [comment]
this is the kind of thing that would break any game, even n-gon. Not
completely surprised something like this would happen eventually.

**Comment by landgreen** [comment]
giving up on fixing this.  we need to focus on bugs with more predictable patterns
