### ISSUE TITLE
Arena fix

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [landgreen/n-gon#332]
Arena (by Whyisthisnotavalable, aka Richard or Destiny) currently does not remove the 'sword' gun after you finish the map.
It has some broken code that *looks* like it does ([level.js:34485](https://github.com/landgreen/n-gon/blob/master/js/level.js#L34485)), but it does not.
I found a potential fix for the issue:
![image](https://github.com/user-attachments/assets/1c65e16e-7caf-4ea4-817d-b714e31feac9)
This involves moving the check to see whether the level has actually ended, instead of just checking whether the player is in the right position.

**Comment by Whyisthisnotavalable** [comment]
That won't work because the level.custom changes every level so it won't detect if it is a different map

**Comment by kgurchiek** [comment]
Doesn't the drawAndCheck also handle moving to the next level, meaning after you go to the next one it will still run the rest of the cycle on the previous map?

**Comment by Ant-Throw-Pology** [comment]
`level.exit.drawAndCheck()` eventually calls `level.nextLevel()`, which sets some variables (including `level.onLevel` and `simulation.clearNow`) that make the map change [at the start of the next frame](https://github.com/landgreen/n-gon/blob/master/js/index.js#L2065). My fix checks those variables, between when they are set and when the next map happens.

**Comment by Ant-Throw-Pology** [comment]
the check should probably actually be
```js
const oldLevel = level.onLevel;
level.exit.drawAndCheck();
if (level.onLevel !== oldLevel && simulation.clearNow && !isUsingSwordMod) {
    // ...
}
```

I would also suggest adding a feature where you can set `level.onExit` in your map and it will be called once the map ends, just to not have to deal with checks like these. (Just make sure to reset it after calling it, and make sure it exists before calling it)

**Comment by landgreen** [comment]
I don't normally edit community maps, but it looks like this wasn't getting fixed so I added it in.
