### ISSUE TITLE
Lore Error

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#333]
I think this was on the second lore step.
![image](https://github.com/user-attachments/assets/18644ba4-8808-47c1-a53a-0cf012651f7e)

**Comment by Ant-Throw-Pology** [comment]
See if you can reproduce it, then see what the values of `lore.chapter` and `lore.sentence` are

**Comment by landgreen** [comment]
I'm testing the chapters and it works for me.  There must some other additional thing that broke it.

**Comment by dotbot123** [comment]
![image](https://github.com/user-attachments/assets/cfbda0cd-5382-4477-a5ed-3c8a8d299cce)
this happened at lore level 2

**Comment by c-rxxp-y** [comment]
ik im a modder and should know this but what are the lore levels? is it like the conversation after you beat the game with all the undefined?

**Comment by AnnonymousNerd87** [comment]
each (successful) run with max undefined increases your lore level by 1

**Comment by AnnonymousNerd87** [comment]
the conversation is different depending on lore level

**Comment by landgreen** [comment]
ok fixed
