### ISSUE TITLE
Inverted world 

### ISSUE THREAD

**Issue by N-gonplayer** [landgreen/n-gon#337]
![Screenshot 2024-10-24 10 52 20 AM](https://github.com/user-attachments/assets/cc3e10a5-30ce-4a2c-82b6-ac0520b85106)
World is permanently upside down after quantum immortality death.

**Comment by landgreen** [comment]
buttons don't work then?

**Comment by N-gonplayer** [comment]
> buttons don't work then?

They don't.

**Comment by landgreen** [comment]
I'm having trouble producing this bug.  Does anyone know the recipe?

**Comment by N-gonplayer** [comment]
> I'm having trouble producing this bug. Does anyone know the recipe?

I've tested this and as long as you die while the gravity is changing the bug will happen. The orientation of the world after that is seemingly random.

**Comment by landgreen** [comment]
ok I got the bug, and I was able to test that I did in fact fix it.
