### ISSUE TITLE
random number generator isn't random

### ISSUE THREAD

**Issue by radixerus** [landgreen/n-gon#339]
Every time n-gon is played/refreshed, the randomly selected constraints are actually the exact same. It's especially annoying because that constraint is "no healing" which means for the entire first level I'm at super low health. This might be affected by me playing on an offline HTML file, but I still think it should be fixed.

**Comment by smallbigman** [comment]
it is for both versions

**Comment by landgreen** [comment]
yeah I noticed that too, I was fixed in the last patch.  Oct 20th
