### ISSUE TITLE
Just a little orbs

### ISSUE THREAD

**Issue by smallbigman** [landgreen/n-gon#340]
![Screenshot 2024-10-25 7 25 47 PM](https://github.com/user-attachments/assets/7e6fb9cd-0c40-483e-92b9-242af572dc50)

**Comment by landgreen** [comment]
broken image :(

**Comment by smallbigman** [comment]
basically I was playing around with the interest tech

**Comment by smallbigman** [comment]
fixed it

**Comment by landgreen** [comment]
cool, thanks reporting this issue here on my github in the place where you report game issues.
