### ISSUE TITLE
[rework] stereoMadness by Richard0820 is too overpowered

### ISSUE THREAD

**Issue by smallbigman** [landgreen/n-gon#341]
stereoMadness doesn't really feel like stereo madness I think we should delete the orb that follows you and make the spikes one shot like the original (unless it will be copy righted maybe just nerf the orb its kinda annoying you could maybe make the orb be able to get blocked or maybe make the orb have collision to the obstacles)

**Comment by Whyisthisnotavalable** [comment]
too bad

**Comment by Whyisthisnotavalable** [comment]
it was supposed to be that hard

**Comment by smallbigman** [comment]
> it was supposed to be that hard

got it

**Comment by c-rxxp-y** [comment]
You should change it to be a wall of one hit kill entities slowly following you so it makes you go forward like in the real game. The orb as of right now only really works if you stall every few seconds.

**Comment by N-gonplayer** [comment]
> it was supposed to be that hard



> You should change it to be a wall of one hit kill entities slowly following you so it makes you go forward like in the real game. The orb as of right now only really works if you stall every few seconds.

Problem with the ball is it makes the level un-fun. The wall idea doesn't have to be any easier, I usually ban the level anyway if I'm doing a community maps run.

**Comment by Whyisthisnotavalable** [comment]
will you close this? I'm not interested in changing the map

**Comment by smallbigman** [comment]
I just figured out how to do it
