### ISSUE TITLE
how do I unlock this part of the lore?

### ISSUE THREAD

**Issue by smallbigman** [landgreen/n-gon#342]
![Screenshot 2024-10-27 3 34 34 PM](https://github.com/user-attachments/assets/07ae81a9-8f17-4701-b5f9-97b6c2c7bb02)
![Screenshot 2024-10-27 3 35 02 PM](https://github.com/user-attachments/assets/813393d9-5bc8-4494-8872-44470cabeeeb)

**Comment by landgreen** [comment]
This area is for report bugs and stuff with n-gon.  I'm not sure this is an issue.

But I'll just say you should win the game with the "undefined" tech and you'll start unlocking lore.
