### ISSUE TITLE
[IDEA] n-gon unofficial DLCs 

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#347]
DLCs could include themes related to seasons holidays and more. If anyone is interested in working together you can DM me on discord. another cool thing that could be done is compiling a list of n-mods (not the people, just mods for n-gon)
(dragonfire_16)

**Comment by c-rxxp-y** [comment]
unrelated, but lets definitely move all ideas for n-gon to a dedicated discussion section, that way landgreen doesnt get flooded with non-issues in the issues section
