### ISSUE TITLE
License change?

### ISSUE THREAD

**Issue by creator1116** [landgreen/n-gon#349]
i may be wrong, but shouldn't n-gon have a AGPL license instead of a GPL license, because n-gon is a WEB based application.

**Comment by landgreen** [comment]
Interesting, I didn't know about AGPL.

AGPL- "It is intended for software designed to be run over a network, adding a provision requiring that the corresponding source code of modified versions of the software be prominently offered to all users who interact with the software over a network."

My primary purpose of having a software license is to let people know it's OK to use my code, and that they can't sue me if the code is bad.  I think GPL should be fine for those purposes, but I don't have a strong opinion.  I'm open to hear other opinions.
