### ISSUE TITLE
Proposal: Synchronization gear

### ISSUE THREAD

**Issue by JayCubby-enwiki** [landgreen/n-gon#350]
Inspired by https://en.wikipedia.org/wiki/Synchronization_gear

Link movement speed to fire-rate, or perhaps damage to fire rate (or vice versa).

**Comment by JayCubby-enwiki** [comment]
Oh, and Higgs mechanism could lock velocity only for the duration of firing (and resume the pre-firing velocity). That'd be neat

**Comment by landgreen** [comment]
I've looking into this mechanic, but I've avoided linking fire rate to movement speed, because you learn to jump to increase your velocity.

**Comment by kgurchiek** [comment]
What if it's only based on horizontal velocity?

**Comment by landgreen** [comment]
yeah I considered this, I'd have to adjust the 3 current SPEED tech to be horizontal as well, and I just have more interesting things to work on.
