### ISSUE TITLE
suggestion for field tech

### ISSUE THREAD

**Issue by corneeme** [landgreen/n-gon#354]
I'm not sure what I would call this but it's a field tech for perfect diamagnetism. It would make perfect diamagnetism be basically a placeable bubble, with a slightly smaller size than the normal arc, maybe like 1/2 speed or dmg inside it to account for an invincible shield, would require not Meissner effect.

**Comment by c-rxxp-y** [comment]
I already added this in my mod, its called einstein's shield, but its a full field not just tech. C-rxxp-y.Github.io/n-gon-enhanced


Sent from my Apple Watch

**Comment by landgreen** [comment]
well it's a great idea, and it seems cool in your mod.
But, I think I'm not going to add it because I want to keep the identity of the standing wave and perfect diamagnetism separate.

**Comment by AnnonymousNerd87** [comment]
also this should be in discussions instead of issues because landgreen is a
full time teacher who doesn't need even more spam

**Comment by corneeme** [comment]
ah sorry just  got used to this
