### ISSUE TITLE
Random field/fieldtech idea i had.

### ISSUE THREAD

**Issue by thesatelliteever** [landgreen/n-gon#355]
A field/fieldtech that lets you grab and throw living mobs, dealing damage to them if they collide with any solid object (walls, blocks, or other mobs.)

**Comment by c-rxxp-y** [comment]
Cool idea, but lets keep any non-issues in discussions please (if landgreen doesn't add it, Ill try to implement it into my mod)


Sent from my Apple Watch

**Comment by kgurchiek** [comment]
Maybe this could be a grappling hook tech that lets you grab mobs like blocks, but it would use way more energy. It would also be cool if throwing a mob allowed you to damage other mobs with it.

**Comment by c-rxxp-y** [comment]
That would be fire


Sent from my Apple Watch

**Comment by 3xionDev** [comment]
> Cool idea, but lets keep any non-issues in discussions please (if landgreen doesn't add it, Ill try to implement it into my mod)

@c-rxxp-y please stop minimodding the issues. everyone has always used the issues tab, nobody wants to use the discussions tab, and it's annoying. I do not believe that landgreen even checks the discussions tab, anyway.

**Comment by AnnonymousNerd87** [comment]
nolan that's why we use discussions, so landgreen isn't cluttered

**Comment by creator1116** [comment]
> > Cool idea, but lets keep any non-issues in discussions please (if landgreen doesn't add it, Ill try to implement it into my mod)
> 
> @c-rxxp-y please stop minimodding the issues. everyone has always used the issues tab, nobody wants to use the discussions tab, and it's annoying. I do not believe that landgreen even checks the discussions tab, anyway.

agreed

**Comment by 3xionDev** [comment]
> nolan that's why we use discussions, so landgreen isn't cluttered

first of all, please don't call me Nolan, we're not on a first name basis here.
second, did you not read what I wrote? landgreen doesn't check the discussions tab and overcomplicating the bug/suggestion system with discussions will only clutter things and make them more confusing. there are only a couple of people here who actually want to make this switch, so please stop trying to push it on everybody.

**Comment by c-rxxp-y** [comment]
@creator1116  shut the fuck up you failure

**Comment by AnnonymousNerd87** [comment]
First, sorry person who commented before cornbread, I'm using email so I
can't see your github, second, landgreen has said to use discussions for
suggestions

**Comment by AnnonymousNerd87** [comment]
You should treat landgreen as if he was *your* science teacher
