### ISSUE TITLE
Addition to testing mode controls

### ISSUE THREAD

**Issue by XtheGxmerz0** [landgreen/n-gon#356]
I think that there should be an option in testing mode to reset the lore (lock testing mode, etc.) for people who dont want the temptation or people who missed the lore in the null level (me)

**Comment by AnnonymousNerd87** [comment]
you could use a console command, but dev mode is blocked by my school so I
can't

**Comment by c-rxxp-y** [comment]
if this was added as a real in-game thing, it would have to have an "are you sure?" button. although landgreen doesn't generally add stuff that is easily done in the console

**Comment by landgreen** [comment]
Clearing the cookies/cache will reset your lore progress.
