### ISSUE TITLE
tech translucent carries over when you die

### ISSUE THREAD

**Issue by corneeme** [landgreen/n-gon#358]
when you die with the tech translucent, the effect of not being able to see your bullets when you shoot
[Uploading Screen recording 2024-11-13 3.59.56 PM.webm…]()

**Comment by landgreen** [comment]
this is a JUNK tech, so they are intended to have "bugs".  At least simple to fix ones like reloading the page.

**Comment by corneeme** [comment]
oh  i didn't realize it  was a junk tech, whoops
