### ISSUE TITLE
Many worlds needs a nerf

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#359]
Every time I use many-worlds it's practically a free win, I always end up with incredibly powerful builds with a ton of bots that allows me to simply walk right through every level and kill finalBoss without pressing a button, even on the hardest difficulty. I get that the point of the tech is that even if you're entering an alternate reality your amount of tech keeps increasing with each new level, but your bot count shouldn't persist. It feels like a few months ago when mass production was added and you could just get bot fabrication and spam research for a free win.

**Comment by landgreen** [comment]
yeah, you are 100% right.
I've been meaning to looking into the bot build up for a while.
I just checked and it's basically just a logic bug in the code where the bots aren't removed properly.
So, next patch you will have zero bot build up unless you have a non removable tech that gives bots.

Another large buff for many worlds is that "remove" tech has gotten really strong, but I'm going to leave that in for a bit of strategy in tech choice.

**Comment by landgreen** [comment]
is there still a mass production and bot fabrication issue?  I forget.

**Comment by AnnonymousNerd87** [comment]
yeah, mass production keeps increasing linearly, faster than bot
fabrication, so it speeds up instead of slowing down over time

**Comment by AnnonymousNerd87** [comment]
I never use it bc its boring

**Comment by landgreen** [comment]
I just tested the bot production rate
mass prodcution + bot fabrication
after each new tech # of total bots = 4 8 13 17 21 26 30 35 40 44 49 53
looks like it's a solid 4-5 bots per tech, which is good, but doesn't have to be nerfed since this is just good synergy

**Comment by AnnonymousNerd87** [comment]
but compared to standard bot gameplay you're getting 4-5 *times *the # of
bots, and its even more brainless because you don't even have to choose
tech, you just research every time

**Comment by landgreen** [comment]
yeah, I had similar thoughts.  It's a fine combo, but should be quite so good considering it's not complex.
research ramp lowered by 1
and fabrications cost ramp is increased to (+1 per 4)-->(+1 per 3)

**Comment by AnnonymousNerd87** [comment]
ye, this also helps indirectly nerf bayesian statistics + mass production
I feel like mass production on its own is fine, but has some combos which
need balancing
Another two combos are (that harpoon tech I'm forgetting the name of that
increases harpoon size and damage by ammo) + mass production, and 1st
ionization energy + mass production
that latter one needs a nerf bc its very boring and you just don't die to
anything except tech stealer

**Comment by QuantumTechnicalLabs** [comment]
Maybe nerf mass reduction by making players unlock mass production of ammo, heals, and research independently?
