### ISSUE TITLE
Interest needs a nerf cap of X ammo and X etc 

### ISSUE THREAD

**Issue by Alpha30811** [landgreen/n-gon#361]
So I always use a save and it is broken with a interest+mass production combo
Another,
Quintessential coupling and the above in late game 
There are so many more in the game maybe less from the tech

**Comment by c-rxxp-y** [comment]
Its not really "broken", i think once you get mass production ammo isn't an issue once you reach a certain amount, so intrest giving 6% doesn't necessarily affect gameplay (unless I'm mistaken)


Sent from my Apple Watch

**Comment by AnnonymousNerd87** [comment]
ye especially with harpoon and bessemer process/UMPWE

**Comment by AnnonymousNerd87** [comment]
Mass production + harpoon + bessemer process
or
mass production + bayesian statistics
or
interest + (any tech that lets you get tons of research [optional]) +
quintessence

**Comment by AnnonymousNerd87** [comment]
capitalism is overpowered in this game

**Comment by Alpha30811** [comment]
> Its not really "broken", i think once you get mass production ammo isn't an issue once you reach a certain amount, so intrest giving 6% doesn't necessarily affect gameplay (unless I'm mistaken)
> […](#)
> Sent from my Apple Watch

Yes but it’s too much. It can’t spawn anymore until I “eat” them once that happens it grows exponentially

**Comment by c-rxxp-y** [comment]
That's true, i think it doesn't really need to be nerfed. Like @landgreen said, its just one of those powerfull combos. Like printer and chain reaction; you can print a ton of blocks then explode them all with grenade tech chain reaction for massive damage. Its fun in easier difficulty, but when mob health is boosted in higher difficulties its a real strategy


Sent from my Apple Watch

**Comment by AnnonymousNerd87** [comment]
ye, I feel like the only true broken combos are the ones that go true
infinite, (like the old options exchange + eject + mass production) or are
a free win once you get them, which n-gon thankfully has very few of.

**Comment by Invincible-Atlas** [comment]
Slightly unrelated, but something that I think might help would be a button in testing mode that allows you to clear`powerUps.powerUpStorage`
