### ISSUE TITLE
Interferometer is frustrating to play on

### ISSUE THREAD

**Issue by Invincible-Atlas** [landgreen/n-gon#365]
The map interferometer is super frustrating to play on. It feels more like I'm playing a rage game like Getting Over It, not N-Gon. I would recommend adding, at the very least, a few platforms so that when you inevitably fall you don't lose all your progress.
PS: I may have gotten the name wrong, so just in case I did, the map I'm talking about is the one with the lasers that are sometimes covered by the rotating platforms, and the button that reverses gravity all the way at the top.

**Comment by landgreen** [comment]
This is intended. "reservoir", "factory", "interferometer" are all hard.
They are added in late game and intended to be there to make sure every run has a level that requires the player to complete a platforming challenge.

But I have been thinking of doing a tiny nerf to interferometer's platforming.
