### ISSUE TITLE
Idea: Scanner field

### ISSUE THREAD

**Issue by 136166** [landgreen/n-gon#366]
The everytime you activate the field, scan where light reaches for mobs, their health value, etc. Zooms out whilst scanning. Can get with some the-more-distance-you-have-the-more-damage-you-deal tech. I think it would just be interesting, and nice if sniping. 

Possible tech: 
1. Microwave scan. Scan shows enemy through a wall.
2.  Spectrum scan. Shows enemy colour.

**Comment by c-rxxp-y** [comment]
Interesting idea, but enemy health bar is usually shown after dealing any damage, and there is no line-of-sight or shadows, so you could see a mob through a wall anyways


Sent from my Apple Watch

**Comment by 136166** [comment]
That's kind of odd.

**Comment by c-rxxp-y** [comment]
yeah most of your idea is just plain game mechanics. Like the creativity tho- Thomas BoydOn Nov 28, 2024, at 11:11 PM, 136166 ***@***.***> wrote:﻿
That's kind of odd.

**Comment by 136166** [comment]
...

**Comment by 136166** [comment]
Oh, well. I just thought it would be nice for it to zoom out so you could snipe the enemy with a railgun.

**Comment by c-rxxp-y** [comment]
if you play my modded version at https://n-gon-enhanced.verve.app you can find a gunTech that allows you to zoom in and out while using a gun I added (sniper)I’ll work on incorporating this into the railgun as well- Thomas BoydOn Nov 29, 2024, at 3:42 AM, 136166 ***@***.***> wrote:﻿
Oh, well. I just thought it would be nice for it to zoom out so you could snipe the enemy with a railgun.
