### ISSUE TITLE
softlock on aerie

### ISSUE THREAD

**Issue by bobsburgers72** [landgreen/n-gon#367]
that one junk tech can cause you to get softlocked on maps like aerie because you cant move where you aim to pick up blocks
![Screenshot 2024-11-28 4 33 35 PM](https://github.com/user-attachments/assets/538af4bf-0b4b-4381-9be8-3537ca896c2b)

**Comment by landgreen** [comment]
I would like to fix soft locks for normal tech, but JUNK should be buggy, this is intended.
