### ISSUE TITLE
marginal utility.

### ISSUE THREAD

**Issue by bobsburgers72** [landgreen/n-gon#368]
i was just trying to get marginal utility for drones and the effects of marginal utility for the other guns just stayed and
![Screenshot 2024-11-29 7 20 45 AM](https://github.com/user-attachments/assets/57ba641a-d7fd-45f8-b4b6-aafdf4e53343)

**Comment by Ant-Throw-Pology** [comment]
yet another tech that isn't removed properly...

**Comment by landgreen** [comment]
I looked at the code and I can't find an issue.

Can you give more detail on how you got the tech "marginal utility".
Was this experiment mode? a normal game? console commands?  testing mode?  community maps?
Also did you get marginal utility and then die and get it again?

**Comment by bobsburgers72** [comment]
i was using experiment mode because I was just testing stuff out and I discovered this by accident

**Comment by landgreen** [comment]
oh ok thanks
I can see how the bug could occur in experiment, but I don't think it can extend to the normal game.
I'll see if there is an easy fix.
