### ISSUE TITLE
soft lock on tutorial/training

### ISSUE THREAD

**Issue by Xygard3** [landgreen/n-gon#369]
It's easy to soft-lock yourself on the fourth level of the training. You just simply stand on the button and throw the block. 
You can also do this on the fifth level. But it is harder.

Video proof:
https://github.com/user-attachments/assets/11971c37-78eb-4780-b31a-bc21a5f4d777

**Comment by landgreen** [comment]
well, I don't think this matter that much, but it was easy to fix so I made a new block spawn
