### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by dotbot123** [landgreen/n-gon#372]
in subway, in the moving doors part if you stand under the door when it closes it stops at standing height, which is fine, but if you crouch, the hitbox closes to crouch height but the door is visually stopped at standing height.

**Comment by c-rxxp-y** [comment]
not really an issue, happens with all collision related to this. The way the player hitbox collides with the map, you can walk into a player-height room, but after crouching you cant uncrouch due to the game thinking theres "not enough room"

**Comment by landgreen** [comment]
yeah I think I'm just gonna say the doors stop because they sense you, not because they hit you.
