### ISSUE TITLE
hiding start screen buttons

### ISSUE THREAD

**Issue by c-rxxp-y** [landgreen/n-gon#374]
I'm trying to add a new button (like experiment) to the start page, although after its click it doesn't disappear after the game starts. any thoughts on how I do this?

**Comment by AnnonymousNerd87** [comment]
find the code for experiment and copypaste it, editing where necessary

**Comment by landgreen** [comment]
I'd search for the ID from start button and copy everything it does

    <svg class="SVG-button SVG-button-splash" id="start-button" width="82" height="45" stroke='none' fill='#333' font-size="30px" font-family="Arial, sans-serif" onclick="simulation.startGame()">
        <text x="10" y="32">start</text>
    </svg>

so search for: start-button
