### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by dotbot123** [landgreen/n-gon#378]
I did something and now I'm almost invincible

[Screen recording 2024-12-11 10.44.47 AM.webm](https://github.com/user-attachments/assets/f455bde4-57da-4792-b59a-792d0a22df8c)

**Comment by dotbot123** [comment]
wait, what? i didn't know that

**Comment by dotbot123** [comment]
nope, happens everywhere

**Comment by AnnonymousNerd87** [comment]
check the pause menu

**Comment by dotbot123** [comment]
[Screen recording 2024-12-11 11.59.21 AM.webm](https://github.com/user-attachments/assets/fda39898-1c1f-4ffb-a0e2-a132fb4a547e)

**Comment by AnnonymousNerd87** [comment]
something you did made your damage taken drop down to 0.25x, it should be
1.25x

**Comment by AnnonymousNerd87** [comment]
that's weird

**Comment by landgreen** [comment]
no bugs here.  You are on easy mode on level 0 and level 1  so you don't take much damage

**Comment by dotbot123** [comment]
ohhhhh
