### ISSUE TITLE
A very minor bug, but still a bug nonetheless

### ISSUE THREAD

**Issue by The-Rock-21** [landgreen/n-gon#379]
If you pause and during a round and you try to look for your tech/junk, and you type the letter p, the game just unpauses without actually narrowing down the tech that you have that start with the letter p or has the letter p in it.

**Comment by AnnonymousNerd87** [comment]
if you type another letter first, then you can delete it and type p without
it unpausing. This is the kind of thing which is just kind of annoying to
fix and small enough not to be necessary because you can just scroll down

**Comment by landgreen** [comment]
I found this bug a couple months ago and fixed it...  not sure why it's back.  Maybe I rewrote the pause check.   Oh well I fixed it again.  Thanks.

this is the fix if you are curious
if (document.activeElement !== document.getElementById('sort-input')) {}
