### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by jo9182** [landgreen/n-gon#38]
Anytime I hold down at least one key for half a second the game freezes; it then immediately unfreezes after letting go of the key(s). I am playing on the most recent version on Why? difficulty.

Edit: What causes the bug

**Comment by dotbot123** [comment]
check your wifi and OS. this has not happened to me

**Comment by jo9182** [comment]
Wifi shouldn't matter at all, and I am currently running it on the most recent version of chromeOS.

**Comment by landgreen** [comment]
spoiler.  The key they are holding down is P
(which pauses the game)

Seriously though I've never heard that bug.
Let me know if you have any more clues for hunting it down.

**Comment by jo9182** [comment]
I have only gotten it to happen on chromebooks. This has stopped affecting my personal chromebook recently but one of my friends does slow down but does not freeze when holding down multiple keys, and I haven't been able to find out how to recreate it on my personal chromebook.
