### ISSUE TITLE
Palantír shouldn't be a JunkTech

### ISSUE THREAD

**Issue by Invincible-Atlas** [landgreen/n-gon#381]
The JunkTech Palantír should just be a normal tech as it is actually useful.

**Comment by AnnonymousNerd87** [comment]
It's a bit underpowered though, and also it isn't the only useful junk.
Reinforcement learning is very useful in my opinion, but would need a
significant buff to be viable as a tech.

**Comment by AnnonymousNerd87** [comment]
Junk can be useful and still junk, like how circular symmetry gives a
damage buff but makes movement and aiming much harder

**Comment by landgreen** [comment]
The curse of JUNK tech is that they can be the best techs in the game if you play them right.

**Comment by Invincible-Atlas** [comment]
> Junk can be useful and still junk, like how circular symmetry gives a damage buff but makes movement and aiming much harder
Yeah, but Palantír has no downsides, and while I admit it is a bit underpowered, it has great synergy potential with drones and/or pilot wave. Maybe it could be made a drone guntech or a pilot wave fieldtech?

**Comment by AnnonymousNerd87** [comment]
I also feel like having at least one good junk tech is good because it
encourages experimentation, and it's niche enough to not be a full tech.
Like reinforcement learning, it's good sometimes, but junk% is still
overall a penalty. Unless you have junkdna
