### ISSUE TITLE
Extreme lag in later levels

### ISSUE THREAD

**Issue by Transistorsis** [landgreen/n-gon#4]
In later levels (e.g. level 30) there is lag such that the frame rate drops to less than one frame per second. Based on the profile that I took in Chrome, it looks like all the lag is taking place in the Matter.js engine. So, there may not be that much that can be done without rewriting it.

Here is the profile that I got:
[Chrome N-gon profile.zip](https://github.com/landgreen/n-gon/files/5038835/Chrome.N-gon.profile.zip)

**Comment by landgreen** [comment]
added 2x difficulty scaling after completing each map.  This should make it impossible to get past level 20 without cheating.
