### ISSUE TITLE
Patch notes webhook

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#53]
Could you use this webhook on commits to publish patch notes to the n-gon community discord? https://discord.com/api/webhooks/1122603497926434866/HU5_cwQzYWGkxAGp_dZAMISCVAOGjQeTclPAObbnmoBWNyH8akAOz27AS_N3l1SEPTRD

**Comment by landgreen** [comment]
I don't understand what it means to "use" this.  Does it need to go somewhere?

**Comment by kgurchiek** [comment]
Here’s a guide I found (skip to step 2): https://gist.github.com/jagrosh/5b1761213e33fc5b54ec7f6379034a22

just set it to send push events so we don’t get messages for things like new stars.

**Comment by landgreen** [comment]
Looks like you can do this without me.

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications

**Comment by kgurchiek** [comment]
How would I make github notifications forward to the discord webhook? (I don't want to make an email bot)

**Comment by landgreen** [comment]
I don't know.

**Comment by kgurchiek** [comment]
Could you add the webhook as shown in the guide so that it'll post the updates to the discord?

**Comment by landgreen** [comment]
Looks like you can do this without me.

https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications

**Comment by kgurchiek** [comment]
That just sends notifications to my github account, right? Then it wouldn't automatically go to discord
