### ISSUE TITLE
Experiment selection mouse tools

### ISSUE THREAD

**Issue by Ant-Throw-Pology** [landgreen/n-gon#55]
Idea:
In the Experiment mode selection screen:
Ctrl+clicking a tech gives you however many of that tech are needed to get to the max count of that tech, and
Shift+clicking a tech removes all of it, regardless of how many you already have.

Perhaps you could do this by removing the "onclick" attribute in build.populateGrid (line 851) and instead add a click listener to the element at the same time that you add the description dataset attribute (line 887), and in the listener, use the ctrlKey and shiftKey attributes of the MouseEvent object passed to the listener.

**Comment by landgreen** [comment]
I don't think there is a need for this feature.
