### ISSUE TITLE
Ambient Sounds and Music

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#57]
Idea: Ambient Sounds
Walking, shooting, etc.

Maybe music on certain maps? Enhances user experience.
Could use something like https://aitestkitchen.withgoogle.com/experiments/music-lm

**Comment by landgreen** [comment]
The player can listen to any music they want in a different tab.  For example if you you open youtube and search for your favorite songs then switch tabs back to n-gon.
