### ISSUE TITLE
Add boss: beamerBoss

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#59]
beamerBoss(x, y, radius = 75 + Math.ceil(Math.random() * 15)) {
        mobs.spawn(x, y, 3, radius, "rgb(255,0,190)");
        let me = mob[mob.length - 1];
        me.isBoss = true;
        me.repulsionRange = 100000;
        me.laserRangeOne = 430
        me.laserRange = 0;
        me.accelMag = 0.0002 * simulation.accelScale;
        me.damageReduction = 0.034 / (tech.isScaleMobsWithDuplication ? 1 + tech.duplicationChance() : 1)
        me.frictionStatic = 0;
        me.friction = 0;
        me.drawAngle = 0;
        spawn.shield(me, x, y, Infinity);
        me.do = function () {
            me.drawAngle += 0.1;
            Matter.Body.setAngularSpeed(this, 0.01)
            me.laserRange = Math.abs((me.laserRangeOne * Math.sin(simulation.cycle * 0.015)));
            this.seePlayerByLookingAt();
            this.checkStatus();
            this.attraction();
            this.repulsion();
            for(let i = 0; i < this.vertices.length; i++) {
                this.harmField(this.vertices[i].x, this.vertices[i].y);
            }
            ctx.save()
            ctx.translate(this.position.x, this.position.y)
            ctx.rotate(this.drawAngle)
            this.drawCore(0, 0, 3, this.radius / 3, this.radius / 3)
            ctx.restore()
        };
        me.harmField = function (x, y) {
            ctx.setLineDash([125 * Math.random(), 125 * Math.random()]);
            // ctx.lineDashOffset = 6*(simulation.cycle % 215);
            if (this.distanceToPlayer3(x, y) < this.laserRange) {
                if (m.immuneCycle < m.cycle) {
                    m.damage(0.0003 * simulation.dmgScale);
                    if (m.energy > 0.1) m.energy -= 0.003
                }
                ctx.beginPath();
                ctx.moveTo(x, y);
                ctx.lineTo(m.pos.x, m.pos.y);
                ctx.lineTo(m.pos.x + (Math.random() - 0.5) * 3000, m.pos.y + (Math.random() - 0.5) * 3000);
                ctx.lineWidth = 2;
                ctx.strokeStyle = "rgb(255,0,170)";
                ctx.stroke();

                ctx.beginPath();
                ctx.arc(m.pos.x, m.pos.y, 40, 0, 2 * Math.PI);
                ctx.fillStyle = "rgba(255,0,170,0.15)";
                ctx.fill();
            }
            ctx.beginPath();
            ctx.arc(x, y, this.laserRange * 0.9, 0, 2 * Math.PI);
            ctx.strokeStyle = "rgba(255,0,170,0.5)";
            ctx.lineWidth = 1;
            ctx.stroke();
            ctx.setLineDash([]);
            ctx.fillStyle = "rgba(255,0,170,0.03)";
            ctx.fill();
        }
        me.distanceToPlayer3 = function (x, y) {
            const dx = x - player.position.x;
            const dy = y - player.position.y;
            return Math.sqrt(dx * dx + dy * dy);
        }
        me.drawCore = function (cx, cy, spikes, outerRadius, innerRadius) {
            outerRadius *= (1 + 0.5 * Math.cos(simulation.cycle * 0.015));
            innerRadius *= (1 + 0.5 * Math.sin(simulation.cycle * 0.015));
            var rot = Math.PI / 2 * 3;
            var xs = cx;
            var y = cy;
            var step = Math.PI / spikes;

            ctx.strokeSyle = "#000000";
            ctx.beginPath();
            ctx.moveTo(cx, cy - outerRadius)
            for (i = 0; i < spikes; i++) {
                xs = cx + Math.cos(rot) * outerRadius;
                y = cy + Math.sin(rot) * outerRadius;
                ctx.lineTo(xs, y)
                rot += step

                xs = cx + Math.cos(rot) * innerRadius;
                y = cy + Math.sin(rot) * innerRadius;
                ctx.lineTo(xs, y)
                rot += step
            }
            ctx.lineTo(cx, cy - outerRadius)
            ctx.closePath();
            ctx.lineWidth = 5;
            ctx.strokeStyle = 'darkred';
            ctx.stroke();
            ctx.fillStyle = 'crimson';
            ctx.fill();
        }
    },

**Comment by Whyisthisnotavalable** [comment]
Something like this would be cool.

**Comment by Whyisthisnotavalable** [comment]
Also, apart from having a bigger radius, bosses should look slightly different from the normal mob counterparts.

**Comment by Whyisthisnotavalable** [comment]
Do you like the idea?

**Comment by landgreen** [comment]
Looks neat.  I'm not accepting community mobs, but you could add it to a level.
