### ISSUE TITLE
Experiment mode 

### ISSUE THREAD

**Issue by MagicalR2D2** [landgreen/n-gon#62]
If a gun or field technology is made unavailable (by selecting a mutually selecting tech) it is still unclickable after the other tech is deselected

**Comment by Whyisthisnotavalable** [comment]
Is that a bug?

**Comment by landgreen** [comment]
yeah, not sure this is a bug, but if you can give a specific example it might make more sense

**Comment by MagicalR2D2** [comment]
An example would be if "pulse" was selected (which would make dye laser unselectable), if pulse is then un selected, dye laser still cannot be selected

**Comment by landgreen** [comment]
I can't reproduce this. 

while I have pulse
<img width="1936" alt="Screenshot 2023-08-02 at 3 52 51 PM" src="https://github.com/landgreen/n-gon/assets/21106570/0de0ecbb-c92c-47a5-aff6-0b6b87c4e7d6">
after pulse is removed
<img width="1936" alt="Screenshot 2023-08-02 at 3 53 01 PM" src="https://github.com/landgreen/n-gon/assets/21106570/c0104cd6-d9c5-42ad-beb4-7ce71a8ce095">
