### ISSUE TITLE
Option for community mods?

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#67]
People might not find mods for n-gon, so they could be in a "mods section" in settings, or somewhere else in the info div. 
For example, a mod could be: https://github.com/Whyisthisnotavalable/n-scythe

**Comment by landgreen** [comment]
I don't have any plans to add support for mods beyond the open source and hackable way I wrote n-gon.  Maybe someone could make a webpage that list them.

**Comment by Whyisthisnotavalable** [comment]
I don't follow.

**Comment by Whyisthisnotavalable** [comment]
If someone made a map with all the mods, someone might not turn on community maps to see them.

**Comment by LinuxRocks2000** [comment]
> I don't have any plans to add support for mods beyond the open source and hackable way I wrote n-gon. Maybe someone could make a webpage that list them.
If somebody did make a well-maintained page for n-gon mods, would you link to it in the official game?
