### ISSUE TITLE
Experiment guns are shorter than other selections

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#72]
Could you make it so that it doesn't look like this:
<img width="1273" alt="Screen Shot 2023-08-07 at 6 12 08 PM" src="https://github.com/landgreen/n-gon/assets/77077277/d825a340-7964-473f-9baf-bb311e03b9fb">

**Comment by Whyisthisnotavalable** [comment]
or make each selection different, so leave a gap between where fields go to guns, tech, etc

**Comment by Ant-Throw-Pology** [comment]
there are also gaps elsewhere in the experiment list

**Comment by Ant-Throw-Pology** [comment]
i did a thing once where i set the height of `.card-text` to 100% and that got rid of the gaps, but it made all the items on the top row super tall

**Comment by Whyisthisnotavalable** [comment]
personally, I'd prefer the old experiment design

**Comment by landgreen** [comment]
you can enable images to fix.
