### ISSUE TITLE
Concave objects used to work

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#73]
They actually used to work, but you needed to render their parts, not their vertices.

If you don't want to bring back decomp, please remove `<script src="lib/decomp.min.js"></script>` from the html file.

**Comment by landgreen** [comment]
They seemed to work, but we've found in the past there were several rare bugs caused by making complex objects.  So I just don't bother partly to not deal with that class of bugs, and also stylistic consistency.
