### ISSUE TITLE
n-documentation

### ISSUE THREAD

**Issue by Whyisthisnotavalable** [landgreen/n-gon#75]
Could you put [this](https://n-documentation.glitch.me/) somewhere in the about section of n-gon?

**Comment by Whyisthisnotavalable** [comment]
It could probably increase the chance of more community maps being created.

**Comment by landgreen** [comment]
Sorry, I am only looking for community maps, and bug reports.  If I include instructions for making community maps I'd want to write it myself and streamline the process.

**Comment by Whyisthisnotavalable** [comment]
Is there anything you would add to the documentation though?

**Comment by landgreen** [comment]
I'm not looking for anything except bugs reports and community maps.

**Comment by Whyisthisnotavalable** [comment]
I doesn't seem like you'll write instructions for making a community map..
