### ISSUE TITLE
Suggestion: CPT Symmetry nerf

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#78]
CPT Symmetry should stop all energy regen for 2 seconds after rewinding.

I just played a game on hard mode where I got CPT Symmetry and 3 causality bots. I was pretty much invincible, since as soon as I got hit I got some dynamo bots which almost immediately brought me back to full energy to get hit again, and then I got even more bots, until I had an army of bots that obliterated any enemy (even the final boss). This could be even more op with pauli exclusion to make you invincible until you've regenerated energy just in case you rewind into an enemy. This could be easily and reasonably balanced by either making causality bots not spawn dynamo, or just prevent all energy regen for 2 seconds or so after rewinding. I personally think the latter is better because you can get some insane energy regen builds with field emitter or molecular assembler coupling, which would still make CPT Symmetry op.

**Comment by Whyisthisnotavalable** [comment]
I bet landgreen gonna say "I'm not looking for anything except bugs reports and community maps."

**Comment by LinuxRocks2000** [comment]
CPT is terrible except in very niche high-energy runs; this is a feature more than a bug imho

**Comment by kgurchiek** [comment]
I had default energy regen and it made hard mode a breeze when my previous best run ever in hard mode didn't even get halfway through the boss fight

**Comment by kgurchiek** [comment]
Which is why I also offered the suggestion of making causality bots unable to create dynamo bots, which is what makes it so op for CPT

**Comment by LinuxRocks2000** [comment]
That's reasonable, self-powering tech is the definition of overpowered
