### ISSUE TITLE
Invulnerable blue triangle mob spawns in Detours

### ISSUE THREAD

**Issue by ezralevinson** [landgreen/n-gon#8]
Build URL for issue: [https://landgreen.github.io/sidescroller/index.html?&gun0=missiles&gun1=laser&tech0=Higgs%20mechanism&tech1=electrostatic%20discharge&tech2=nitroglycerin&tech3=overcharge&tech4=energy%20conservation&tech5=renormalization&tech6=fragmentation&tech7=diffuse%20beam&tech8=output%20coupler&tech9=undefined&tech10=undefined&tech11=undefined&tech12=undefined&tech13=undefined&tech14=undefined&tech15=undefined&field=metamaterial%20cloaking&difficulty=2](https://landgreen.github.io/sidescroller/index.html?&gun0=missiles&gun1=laser&tech0=Higgs%20mechanism&tech1=electrostatic%20discharge&tech2=nitroglycerin&tech3=overcharge&tech4=energy%20conservation&tech5=renormalization&tech6=fragmentation&tech7=diffuse%20beam&tech8=output%20coupler&tech9=undefined&tech10=undefined&tech11=undefined&tech12=undefined&tech13=undefined&tech14=undefined&tech15=undefined&field=metamaterial%20cloaking&difficulty=2)

In the Detours level, a blue triangle spawns which cannot be damaged (at least not with laser or explosive damage from missiles). This has happened twice now for me. Hasty pre-death screenshot attached:
![Screen Shot 2021-02-28 at 4 46 34 PM](https://user-images.githubusercontent.com/77641389/109446170-4199c400-79e5-11eb-8f36-949c2c1b38f3.png)

**Comment by landgreen** [comment]
I think this was fixed, let me know if it happens again
