### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#82]
Generalist only locks gun with the Q and E keys not the number keys.

**Comment by Masbirb** [comment]
Sound bot upgrade does not count as a bot upgrade I.E you can have upgraded sound bots and upgraded laser bots

**Comment by Masbirb** [comment]
Also picking up gun techs after you have all guns just delete the gun tech but not activating cancel effects like commodity exchange.

**Comment by landgreen** [comment]
"Generalist only locks gun with the Q and E keys not the number keys."  fixed, thanks

**Comment by landgreen** [comment]
ok, I made the cancel/research menu pop up even when there are no possible gun options, so you can click cancel for the buffs.
