### ISSUE TITLE
Boss mobs see you at the beginning of the level

### ISSUE THREAD

**Issue by TheFurrySlayer** [landgreen/n-gon#84]
When I start a new game and go to the first level, sometimes the boss can see you through walls. Normally, this is fine, but 
when it happens I'm on the beginning of the game when I have barely one tech and not full health. Plus, I think that it could be a feature for harder difficulties, but on a new game, it is just unfair. Also, I understand some bosses have the ability to see through walls.  The level that this most commonly happens is warehouse.  Finally, I have died many times because my weapon is bad with no upgrades and has not enough damage output to kill the boss before it kills me.

**Comment by Whyisthisnotavalable** [comment]
This seems like a feature not a bug

**Comment by kgurchiek** [comment]
I think the difficulty is intentional, it makes it a bit harder to start and earn your way to get more tech. I personally don't think it's too unbalanced

**Comment by TheFurrySlayer** [comment]
The thing is that I barely have enough damage at the start to kill the boss. And the bots upgrades seem to be rare (at least for me.)

**Comment by TheFurrySlayer** [comment]
> This seems like a feature not a bug
I didn't mean this like it was a bug, just an annoying thing that has happened to me many times.

**Comment by kgurchiek** [comment]
If the game is too hard, play on a lower difficulty until you get better at it, then work up to a harder mode.

**Comment by TheFurrySlayer** [comment]
The game isn't too hard, it's that I think bosses that have the ability to see to you anywhere shouldn't be able to spawn in the 1st level (at least on easier difficulties)

**Comment by Masbirb** [comment]
I think that it is a bug if a boss that shouldn't see through walls sees you immediately when you start a level.

**Comment by Masbirb** [comment]
Have you ran into any other bugs.

**Comment by TheFurrySlayer** [comment]
I don't think it is a bug.

**Comment by TheFurrySlayer** [comment]
Also I think the black hole should not be affected by your field, because for me, the black hole is just a pushover.

**Comment by Masbirb** [comment]
Yeah I kind of agree but maybe it is because your projectiles kind of home in to it due to its gravity.

**Comment by landgreen** [comment]
I haven't had issues with bosses seeing you, but I'll keep it in mind for the future.
