### ISSUE TITLE
Levels broken on loading

### ISSUE THREAD

**Issue by des-boot** [landgreen/n-gon#85]
<img width="552" alt="image" src="https://github.com/landgreen/n-gon/assets/63741810/0c67edf0-9add-47e7-8828-541b8ef4a03f">
![image](https://github.com/landgreen/n-gon/assets/63741810/30474724-3246-49c2-bace-00366c9f8c5a)
ground is intangible, ground from older levels appears. This bug has been happening far more commonly recently

**Comment by Masbirb** [comment]
I have had several of my runs ended due to this bug like at least 5.

**Comment by landgreen** [comment]
Is it always a bug in the "dojo" community level?
(
based on the level.js:25954
        boss.onHit = () => {
            boss.modeSwitch = -1; // After striking the player, always switch modes
            oldOnHit.call(boss);
        };
)

**Comment by landgreen** [comment]
looks like this is dojo based on other bug reports
