### ISSUE TITLE
Quality of Life improvements/Ideas

### ISSUE THREAD

**Issue by TheFurrySlayer** [landgreen/n-gon#86]
I have some ideas to make n-gon better.
First,  adding a tech/option where you can select what missiles/drones/bots attack, for example, you should be able to choose whether drones attack shielded enemies first. Plus, bots/drones/spores/worms/fleas should have an option or better yet, a tech that lets them warp to you.
Also, an option to disable/enable blocks being picked up, not that I never use blocks (Especially when I have bremsstrahlung and cherenkov radiation). Really, the only reason I said this is because on the final level, there are barely any blocks, but the final boss pushes them into you, and when I'm trying to deflect all the enemies, I really dislike it when I accidentally fire a block instead of deflecting, and this happens to me on highrise too. To add on, I think it would be cool to make a level where you have to stack blocks to continue. 
Finally, the dashing enemies are able to dash through everything, including shields, which, non-dashing bosses aren't able to get through, and it's kind of annoying and doesn't make sense. I don't know if there is a way to remove it, but if there is I would like that, but I think bosses that use dashing should be able, as it would make the game balanced. (So you can't just hide behind a shield and kill everything with no damage taken.)
One last thing: making the MACHO not be able to interact with the boost pads (?) jump pads (?), because on satellite, sometimes I have the MACHO and it just goes into space when I use the jump pads (?), and it takes like a minute for it come back, and now especially with dark star, because it has very useful ability. (Not that the MACHO was ever bad, I always use it in experiment mode.) 
If any of the ideas here don't work, or aren't able to be implemented, I'm fine with that.
Edit: I'm not trying to spam the issues tab, I just have been replaying n-gon after a few updates, so I wanted to say some ways that I think n-gon could improve.
Another edit because I forgot about this: I was playing n-gon, then left the tab to do something else on my computer. My computer lagged for a bit, and when I opened the game again, the n-gon robot (?) was stuck in place and could only look around, and the enemies were able to detect me, but they couldn't move. When I reloaded the tab everything was. I don't what happened but the game sort of froze, just a weird glitch I found and want to tell you about.
The last edit for this: I would really like it if there is a way to pass factory without negative mass, because I get bombarded by enemies, and I get knocked off and fall into the void.
Okay, the last edit (really): A tech that: "Makes lens 50° larger, moves 50% slower, and drains 100% more energy". I don't know, okay.
Sorry for this massive block of text.

**Comment by TheFurrySlayer** [comment]
This is just unfair.
![Screenshot 2023-10-01 11 59 51 AM](https://github.com/landgreen/n-gon/assets/127251433/77133c88-99e3-4110-9e0c-6c9ac8aaa06b)
![Screenshot 2023-10-01 11 53 24 AM](https://github.com/landgreen/n-gon/assets/127251433/81771db0-210d-4801-9af8-dd9b480a8d16)

**Comment by landgreen** [comment]
thanks, I'll keep these ideas in mind.
