### ISSUE TITLE
Flux pinning description

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#87]
The flux pinning descriptions qualification say just a field that can block but the field emitter which can block is not compatible so please change the requirement description or requirement.

**Comment by landgreen** [comment]
Field emitter is already correctly stunning targets for me with flux pinning.  Let me know if you can figure out how I can reproduce this.

**Comment by Masbirb** [comment]
You cannot get flux pinning with field emitter but the requirement description says all you need is a field that can block, not a nonbasic field (a field that you need a field power-up to get) that can block.

**Comment by landgreen** [comment]
ok I understand now.  The field emitter doesn't unlock any field upgrades.  This is intentional because I don't want players to get this upgrade before they get a field.
