### ISSUE TITLE
Rail gun oddity's

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#88]
1. Rail gun and smelting (shoot more harpoons) when used together use  the same amount of ammo.
2. Bitter electromagnet (slow charge but more damage) is compatible with Capacitor Bank (Fast charging)
3. Maybe add a fast rail gun upgrade that reduces damage and velocity but gives more ammo and lets you charge faster named Low voltage coils?

**Comment by landgreen** [comment]
I'll keep these ideas in mind next time I rework rail gun.
