### ISSUE TITLE
A weird bug. 

### ISSUE THREAD

**Issue by TheFurrySlayer** [landgreen/n-gon#90]
There's a bug where you can not bounce on the jump pad (?) if you crouch and and walk on top of it. I don't know what causes this. Also, every weapon's projectile seems to go wild when it is inside slime.

**Comment by Masbirb** [comment]
The jump pad thing may not be a bug but what is the slime you are talking about, the stuff from reservoir (The map that slowly floods with water?)

**Comment by TheFurrySlayer** [comment]
You're right. I'm talking about the thing from reservoir.

**Comment by landgreen** [comment]
This is intentional, so you can not bounce if you want.

**Comment by Batnonhrattata** [comment]
Yo furryslaya
