### ISSUE TITLE
Tungsten Carbide tech

### ISSUE THREAD

**Issue by Masbirb** [landgreen/n-gon#93]
A tech that requires tungsten carbide and makes an explosion (maybe radiation so no conflict with shaped charge) when you land, the explosion is larger based on how far you drop but makes you take more fall damage.
A tech that requires tungsten carbide and when you touch on mobs they take damage (maybe add an effect that lets jump off of enemies)

**Comment by Masbirb** [comment]
I came up with this because I want all bodies have tech that goes with them.

**Comment by kgurchiek** [comment]
It would be kinda fun to jump on mobs like Mario, that could definitely be an independent tech though, it isn't really tied to tungsten carbide like the other suggestion is
