### ISSUE TITLE
The Perfect Diamagnetism training obstacle is impossible

### ISSUE THREAD

**Issue by kgurchiek** [landgreen/n-gon#97]
I assume you're supposed to have infinite energy for that level, but you don't have enough to go through the winding fall

**Comment by kgurchiek** [comment]
Apparently it is _possible_, but it's very hard, which doesn't make much sense for a training map intended to teach brand new players how to play the game. This also doesn't reflect actual gameplay, I think it should wither be removed or replaced with a much easier version. If it were to be redone, I think it would make sense to be a long horizontal jump rather than a fall, because that would more accurately represent using it in actual gameplay.

**Comment by Masbirb** [comment]
I have never passed that Training level so it may. A problem may also be an update changed Perfect Diamagnetism energy drain or how fast you move when "Parachuting".

**Comment by Masbirb** [comment]
Also a better question is why does perfect Diamagnetism drain energy on this one stage in particular.

**Comment by landgreen** [comment]
if "Richard0820" wants to nerf this I'd be happy to make the update.

**Comment by 136166** [comment]
I vote we nerf it! I find it irritating and rather tricky! the deepest I have gotten is near the bottom!
