### ISSUE TITLE
Issue with boss spawning

### ISSUE THREAD

**Issue by des-boot** [landgreen/n-gon#98]
![image](https://github.com/landgreen/n-gon/assets/63741810/57023868-736e-40bd-99c8-756ea8af24ad)
![image](https://github.com/landgreen/n-gon/assets/63741810/69244a63-d3ae-4487-8d92-7295c70e7c72)
![image](https://github.com/landgreen/n-gon/assets/63741810/9b3abff1-49c5-4b80-92b7-46d56245c61d)
![image](https://github.com/landgreen/n-gon/assets/63741810/b2c30976-c008-47f6-af16-471c225d061c)
these both happened in the same playthrough, and has been happening much more often recently

**Comment by kgurchiek** [comment]
does this only happen on community maps?

**Comment by des-boot** [comment]
> does this only happen on community maps?

it seems like it does, but its odd just how much it happens

**Comment by Masbirb** [comment]
It may be that both of those levels always have a boss in them in one  place like downpour has some hidden bosses but I am not certain about the other map.

**Comment by landgreen** [comment]
I don't know how to fix this, but it it ever happens to me I can try to track it down.

**Comment by Loiccoder** [comment]
im sorry this is unrelated, how do i get to see code like that on the first and last images? i am not familiar with github. this game intrigues my by the amount of hidden mechanics i somehow mastered without understanding them, and would like to learn how the game works

**Comment by kgurchiek** [comment]
Open your browser's dev tools (usually by holding down ctrl, shift, and i at the same time) and go to the "console" tab

**Comment by des-boot** [comment]
I screenshotter with windows+shift+X, then pasted the image in

**Comment by landgreen** [comment]
probably fixed
